### PR TITLE
LPS-86236

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @hhuijser and @arthurchan35,

Did you guys send this pull request to me to get a SME review?

Best.

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @arthurchan35,

I read [LPS-79312](https://issues.liferay.com/browse/LPS-79312) and also [LPP-32097](https://issues.liferay.com/browse/LPP-32097) and I believe I understand your intention, however why you want to create a Calendar Admin Portlet? What exactly is the issue you want to solve?

In addition, I think the discussion with the Staging team about your findings is still in progress according to this [comment](https://issues.liferay.com/browse/LPP-32097?focusedCommentId=1619173&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1619173), am I right?

I'll wait for your answers, before we move on with this pull request.

Thanks in advance for your answers!

**Comment by arthurchan35** [comment]
Hi @natocesarrego ,
The real reason behind this PR is that my work on LPS-86233 (which is to revolve portletPreferences contains 0,3,0 entries after publishing) is blocked because of this instance level Calendar is being able to export import portlet data.
Conceptually an instance portlet that displays on a layout should only be able to export import its configuration/metadata stuff, but not portlet data, which is a job for an admin. That is what I learned from LPS-79312.

Here Calendar admin, indeed, may not do any actual stuff, may not even show up in site admin. It's sole purpose at this moment is to release the job of exporting/importing portlet data from instance calendar portlet.

Yes, the SME is still in process. What happened was probably that Hugo asked to get a confirmation, so I created a SME, then I texted him saying I have contacted SME.
He probably misinterpreted it as I have got confirmation.

**Comment by natocesarrego** [comment]
Hi @arthurchan35,

Honestly, in my opinion, create the Calendar Admin Portlet _only_ to address the need raised by you isn't the best option. First of all, I believe the Calendar scenario, absence of Admin Portlet, should be shared with the Staging team for we hear the team's opinion, maybe, there is another Portlet with the same behavior which has already solved this issue. Therefore, the first question that must be answered is _how the fix for LPS-79312 should be applied in a scenario where there isn't Admin Portlet?_ With this answer in mind, I think we'll be ready to move on with the fix.

By the way, did you and Hugo send this pull request to me to get the SME's opinion or your goal was reach the Product Team?

Thanks.

**Comment by arthurchan35** [comment]
@natocesarrego,
Unfortunately, I pinged staging team in SME again on Monday but still have not heard from them for this matter.
However this Admin portlet is not just only to address the need raised by myself.
1. It is conceptually wrong to allow display portlet to export/import portlet data.
2. A portlet, ie Calendar Portlet, that is both DATA_LEVEL = SITE(because it exports/imports portlet data) and portletPreferences = uniquePerLayout(because it is display portlet) will generates PortletPreference entries of ownerId = 0, ownerType = 3, plid = 0, which are invalid entries.

Not sure about Hugo, I will ask him once he is back in office. I originally sent PR to him and started an SME discussion, I was hoping there would a response from SME so that I will tell Hugo to forward PR to whoever should review it.

**Comment by arthurchan35** [comment]
@natocesarrego 
Thank you very much!
And Mate made a comment in the SME saying:
"From a technical standpoint yes we should be separating. But do we have an issue caused by this? Is calendar not working due to this? If calendar working as expected i don't think it's necessary to change it."

Seems like He did not go through everything provided in the SME, so I made another comment to list reasons why it is a problem.
Still waiting for a response for this one.

It will be great Calendar SME can help review it too, may I know who should I ping in SME?

**Comment by natocesarrego** [comment]
Glad to hear we had an update on the SME request, @arthurchan35! Let's wait for the new Mate's reply. 🙂 

In addition, I'm the Calendar SME. 😄 Currently, the Calendar Portlet is assigned to the Workflow team, hence once I'm the SME of Workflow, I'm also in charge of Calendar.

Best.

**Comment by arthurchan35** [comment]
ci:reopen

**Pull request closed without merging**
