### PR TITLE
LPS-109799 Adding the cancel button in edit form instance record screen

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-109799

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@marcosapmf, I labeled this pull as **blocked** once it's depending of the GDPR story get merged.

**Comment by marcosapmf** [comment]
ci:test:sf

**Pull request closed without merging**
