### PR TITLE
LPS-95361 Prepare workflow for Site Member role

### PR DESCRIPTION
**Pull request by hudakl**
Hi Renato,

Please find my solution suggestion for LPS-95361 in this pull.

Could you pleases review my changes?

Thank you,
Laci

### CODE REVIEW

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @hudakl,

From what I could see, your implementation address the current issue, however I've detected some source format issues. Can you please check them?

I'll run the source format tests to help you see the issues and fix them.

Best.

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by hudakl** [comment]
Hi Renato,

I've added an SF commit to fix the source format issues and rebased the fix.

Regards,
Laci

**Comment by natocesarrego** [comment]
Thanks, @hudakl!

I'll run the source format tests again. 🙂

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/186. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
