### PR TITLE
LRQA-67145

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by natocesarrego** [comment]
ci:test:forms-functional

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @natocesarrego, can you please check if these failures are related to your changes? Thanks

**Pull request closed without merging**
