### PR TITLE
LPS-100290 baseline

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-100290

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Good job, @marcosapmf. 😄

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/403. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
