### PR TITLE
LPS-103224 Fixes for some of the test errors detected in pr natocesarrego#374

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-103224

Hi @natocesarrego @inacionery

As I said in https://issues.liferay.com/browse/LPS-103224?focusedCommentId=2107254&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2107254 we have a Spanish customer waiting for this DDM improvements.

I have downloaded and done some testing using https://github.com/natocesarrego/liferay-portal/pull/374 code and I have fixed some of the errors detected in the integration tests

There are some errors that I wasn't able to fix yet:

- Some tests fails because they compare the returned information from the query with the expected indexed information. The problem is nested fields are not returned in the information that comes from Elasticsearch query
- Other tests that check sorting by ddm fields are also failing because we are sorting using the old ddm fields.

Perhaps it is necessary to ask help to the search team as some of this issues are related to search infrastructure.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by natocesarrego** [comment]
Hi @jorgediaz-lr,

Since yesterday, I've been testing and analyzing the proposed DDM indexation improvement in light of your comments and I agree with your conclusions about the related test failures. 🙂 Below, I'll describe more technically my findings regarding the test failures in order to share them with the Search team. Once I get some answer from the Search team, I'll notify you and the other stakeholders.

Thanks.

### **Technical analysis of related test failures reported by Search test suite:**

**1. Test failure** 
- com.liferay.document.library.search.test.DLFileEntryIndexerIndexedFieldsTest.testIndexedFields

**Cause**

The fields associated to the HTTP Headers aren't retrieved by the search. These expected fields are created by the method [populateHttpHeaders](https://github.com/liferay/liferay-portal/blob/317e35c1be51ddba2b6d5a0658824a3ee7d4698f/modules/apps/document-library/document-library-test/src/testIntegration/java/com/liferay/document/library/search/test/DLFileEntryIndexerIndexedFieldsTest.java#L248-L257) and they look like this:
```
ddm__text__[Structure ID]__HttpHeaders_CONTENT_TYPE
ddm__text__[Structure ID]__HttpHeaders_CONTENT_ENCODING
```
_____________________________________________________________________________________________________

**2. Test failure** 
- com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDMBooleanField
- com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDMBooleanFieldRepeatable
- com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDMIntegerField
- com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDMNumberField
- com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDMNumberFieldRepeatable
- com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDMRadioField
- com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDMRadioFieldKeyword
- com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDMTextField
- com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDMTextFieldKeyword
- com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDMTextFieldRepeatable
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMBooleanField
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMBooleanFieldRepeatable
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMDateField
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMIntegerField
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMNumberField
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMNumberFieldRepeatable
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMRadioField
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMRadioFieldKeyword
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMTextField
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMTextFieldKeyword
- com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMTextFieldRepeatable

**Cause**

From what I could realize, all tests above are failing for the same reason, e.g., they are building an `AssetEntryQuery` whose [order column](https://github.com/liferay/liferay-portal/blob/317e35c1be51ddba2b6d5a0658824a3ee7d4698f/modules/apps/dynamic-data-mapping/dynamic-data-mapping-test-util/src/main/java/com/liferay/dynamic/data/mapping/test/util/search/TestOrderHelper.java#L245-L246) won't work to perform the expected ordering. Consequently, the ordering isn't attended due this column and all tests fail.

**Comment by jorgediaz-lr** [comment]
Hi @natocesarrego 

About first Test failure, one clarification:

- com.liferay.document.library.search.test.DLFileEntryIndexerIndexedFieldsTest.testIndexedFields

I checked Elasticsearch index and information was correctly indexed in new nested "ddmFields" fields.
The problem is that nested fields are not returned by Elasticsearch query.

Thank you

**Comment by lipusz** [comment]
ci:test:search:95b88a6929706a525c801b5ce91ce7bf45da2d0e

**Comment by lipusz** [comment]
ci:test:relevant:95b88a6929706a525c801b5ce91ce7bf45da2d0e

**Comment by lipusz** [comment]
ci:test:search-es7:95b88a6929706a525c801b5ce91ce7bf45da2d0e

**Comment by lipusz** [comment]
Triggered tests on latest stable Search hash.

**Comment by jorgediaz-lr** [comment]
Hi @natocesarrego @lipusz 

I have rebased the branch to latest master and added @BryanEngler changes from https://github.com/BryanEngler/liferay-portal/commits/2020_04_09_LPS_103224_nested_fields_tests

I have checked that after adding that commits com.liferay.document.library.search.test.DLFileEntryIndexerIndexedFieldsTest.testIndexedFields test is no longer failing.

So the only problem remaining is sorting using the nested fields that causes the failure in the tests that starts with:
 - com.liferay.document.library.search.test.DLFileEntrySearchTest.testOrderByDDM*
 - com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDM*

Regards,
Jorge

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by natocesarrego** [comment]
Exactly, @jorgediaz-lr, before start the paternity leave, Bryan let me know about it, but now we need Search team assistance to address the remaining failures.

Thanks for your hard work on it. We're getting close. 🙂

**Comment by arboliveira** [comment]
Please see: https://github.com/natocesarrego/liferay-portal/pull/501

**Pull request closed without merging**
