### PR TITLE
LPS-101943 Fix placeholder bug in ie11 for textarea tag

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:forms

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
@carolmariaabb it seems test is broken. Please see last error report. Sending to command to run tests again.

**Pull request closed without merging**
