### PR TITLE
[TECHNICAL SUPPORT] LPS-100416 Non-Repeatable text fields show incorrect translation on label at first load

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

Please review it.

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @NemethNorbert,

This pull request has the same solution of your last pull (natocesarrego#163), in light of this I'm worried if this pull is addressing the issue previously raised [here](https://github.com/natocesarrego/liferay-portal/pull/163#issuecomment-526601050). Can you please confirm it to me?

Thanks in advance.

**Comment by NemethNorbert** [comment]
> Hi @NemethNorbert,
> 
> This pull request has the same solution of your last pull (#163), in light of this I'm worried if this pull is addressing the issue previously raised [here](https://github.com/natocesarrego/liferay-portal/pull/163#issuecomment-526601050). Can you please confirm it to me?
> 
> Thanks in advance.

I could not reproduce the reported issue anymore, however I was still able to reproduce the issue this PR was intended to solve. I should have included that in the first comment, sorry about that

**Comment by natocesarrego** [comment]
No problem, @NemethNorbert. I'll review it on next week.

Thanks.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79071. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
