### PR TITLE
[Technical support] LPS-68216

### PR DESCRIPTION
**Pull request by brandizzi**
Hey Adam

Could you help review this ?

Thanks
John.

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @yuhai and @zxdgoal,

Adam has forwarded some pull requests for me review and I'll start to process it soon. I'll try to give you a feedback tomorrow or on next Monday at the latest.

Thanks.

**Comment by yuhai** [comment]
Hi @natocesarrego ,

Thanks for your help.

Best Regards,
Hai

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/750. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
@yuhai and @zxdgoal, a simple and clear pull request. Congrats. 😄

**Pull request closed without merging**
