### PR TITLE
LPS-106870 change debounce delay

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Good to go. Just waiting CI outcomes.

Thanks.

**Comment by natocesarrego** [comment]
Hi @carolmariaabb,

I'm afraid that this pull is causing new failures on CI. I analyzed the CI results of this pull and compared with the last execution of CI (March, 12th) and I concluded that there is a chance of the following failures be related to this pull:

- https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/370376/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitFormWithRequiredTextField_/
- https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/263692/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitFormWithCustomTextContainingValidation_/
- https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/344460/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitFormWithRequiredMultiLineTextField_/
- https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/344461/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_ViewRepeatableTextFieldLabel_/
- https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/362206/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitFormWithAllFieldTypesAndThreePages_/
- https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/372254/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsJumpToPage_ViewRuleAfterLabelEdit_/
- https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/236994/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitFormWithRequiredRadioField_/
- https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/370377/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitFormWithMultipleFieldsAndViewEntriesViaDescriptiveDisplay_/
- https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/370377/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitFormWithMultipleFieldsAndViewEntriesViaDescriptiveDisplay_/
- https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/370377/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitFormWithMultipleFieldsAndViewEntriesViaDescriptiveDisplay_/
- https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/333442/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitWithRequiredDateField_/
-https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/248884/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitFormWithRequiredCheckboxField_/

@cvanut, can you please double check these failures to make sure we won't break CI?

Thanks guys!

**Comment by cvanut** [comment]
Hi @natocesarrego and @carolmariaabb 
I analyzed the tests that failed in this PR, and here are the **results**:

`SubmitFormWithRequiredTextField:` **Passing** on CI since March 12th.
`SubmitFormWithCustomTextContainingValidation: `**Passing** on CI since March 12th.
`SubmitFormWithRequiredMultiLineTextField:` **Passing** on CI since March 12th.
`ViewRepeatableTextFieldLabel:` **Passing** on CI since March 12th.
`SubmitFormWithAllFieldTypesAndThreePages:` **Passing** on CI since March 12th.
`ViewRuleAfterLabelEdit:` **Passing** on CI since March 12th.
`SubmitFormWithMultipleFieldsAndViewEntriesViaDescriptiveDisplay` **Passing** on CI since March 12th.
`SubmitWithRequiredDateField:` **Passing** on CI since March 12th.

Thus, I believe the fails are related to this PR.

**Comment by natocesarrego** [comment]
Thanks, @cvanut. @carolmariaabb, can you please check the CI failures? If you need any assistance, please talk to me, @cvanut or @brunofariasdeo.

Thanks.

**Comment by carolmariaabb** [comment]
> Thanks, @cvanut. @carolmariaabb, can you please check the CI failures? If you need any assistance, please talk to me, @cvanut or @brunofariasdeo.
> 
> Thanks.

Okay, @natocesarrego!

**Comment by natocesarrego** [comment]
Hey @cvanut and @brunofariasdeo,

After analyze together with @carolmariaabb the related failures, we understand that, probably, all related failures demand test fixes on Poshi's side, therefore I'd like to forward this pull to one of you in order to you implement these fixes.

@carolmariaabb, can you please share with the guys what are the possible cause of the related failures? They'll need it to perform their job.

**Reminder:** @cvanut and @brunofariasdeo, you should work on this task as a top priority, once there is a customer waiting for this fix. 😉 We can discuss more about this task offline if you guys need some assistance. 🙂 

Thanks.

**Comment by natocesarrego** [comment]
Pull request sent to @cvanut to implement test fixes.

**Pull request closed without merging**
