### PR TITLE
LPS-63229 Provide more details about exception and change log level to a less critical level.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
Your pull request test has been aborted. We are sorry of the inconvenience but QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/402. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/b4e38e3bfcfc~2...b4e38e3bfcfc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
