### PR TITLE
LRQA-67375

### PR DESCRIPTION
**Pull request by natocesarrego**
@gleicelisbino, the scroll removal didn't fix the test failures, I'm trying a new fix.

After our daily meeting today, let's investigate why the CI commands aren't working on your GitHub user. :wink:

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by gleicelisbino** [comment]
@natocesarrego Okay! Thank you so much!

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
ci:reevaluate:1167401_8473

**Comment by natocesarrego** [comment]
ci:test:forms

**Pull request closed without merging**
