### PR TITLE
LPS-103921 Partial revert "LPS-103549 Remove deprecated stuff from dy…

### PR DESCRIPTION
**Pull request by mclomello**
…namic-data-mapping". This commit partially reverts 8369c25165391bcfad0923c4f8bbc45885838423.

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80311. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
