### PR TITLE
LPS-116665 Improve accessibility in Forms

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @natocesarrego ,

Here's the pull request including the change you suggested [here](https://github.com/natocesarrego/liferay-portal/pull/753#discussion_r469443404). I've built it on top natocesarrego#774 to be sure there's no missing commits. I've rebased master as well.

About the solution in this last commit, I struggled to find a readable way to do it because since we are having more and more conditions I think the code is less and less readable. My first idea was to use a ternary operator, but then we would have had a ternary operator inside another ternary operator and I don't think it's a good idea in terms of readability.

If you think there is a better, easier way to do it, feel free to modify it.

Thanks.

Regards.

/cc @carolmariaabb

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Thanks for your hard work on this pull, @antonio-ortega and @carolmariaabb. 🙂 I'm ready to forward it! 🚀

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
