### PR TITLE
[TECHNICAL SUPPORT] LPS-85658 Web Form Paragraph is mandatory

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @natocesarrego ,

[LPS-85658](https://issues.liferay.com/browse/LPS-85658)

I decided to just set the optional attribute to true for 'parahraph' before we hide the field from the user.

Please review my changes,
Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
https://github.com/natocesarrego/liferay-portal/pull/127

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Good job, @NemethNorbert! 👏 

You did a simple and elegant solution!

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/160. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/1958eeb2f55a~1...1958eeb2f55a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
