### PR TITLE
LPS-121043 Fix test

### PR DESCRIPTION
**Pull request by alinedoleron**
https://issues.liferay.com/browse/LPS-121043

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@alinedoleron, please see https://github.com/natocesarrego/liferay-portal/pull/841#discussion_r493834838.

**Comment by alinedoleron** [comment]
> @alinedoleron, please see [#841 (comment)](https://github.com/natocesarrego/liferay-portal/pull/841#discussion_r493834838).

Hi @natocesarrego, I didn't find no explanation. It's a little hard to find this things about Recharts. I looked for this id on github and it seems to do the same thing on the examples I've seen. It always shows the first item from a list. 
See this examples:
https://github.com/search?l=HTML&q=recharts_measurement_span&type=Code

And this, specifically, it shows Jan, that it seem to be January.
https://github.com/benjamingr/delta-differ/blob/78b3308b88599f667121b536fb2c6a9bc361dc70/benchmark/fixures/number-people-open.html

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
