### PR TITLE
LPS-119818 Create poshi test to test the case of removing a field which belongs to a rule

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-119818

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:close

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
ci:close

**Comment by alinedoleron** [comment]
ci:stop

**Pull request closed without merging**
