### PR TITLE
LPS-107707 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@natocesarrego sending this back you as it might be real errors here

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/321. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
