### PR TITLE
LPS-97841 Fix behavior when guest users only have add form record permission

### PR DESCRIPTION
**Pull request by mclomello**

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78985. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
