### PR TITLE
LPS-68687

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey @natocesarrego 
Could you please help to review this fix as a high priority? one ee customer is waiting for this fix? it is kind of urgent for customer.

Thanks,
Dale

**Comment by natocesarrego** [comment]
Hi @daledotshan,

I'll review this right now, don't worry. 😉

Regards.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/331. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/07d40a2~1...07d40a2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
