### PR TITLE
LPS-120480 Centralize auto save message and do not break line when opening the control panel

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issue: https://issues.liferay.com/browse/LPS-120480

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hey @alinedoleron, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
@natocesarrego, no test is applicable to this case, since it's only a css change.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
