### PR TITLE
LPS-90833 [New Form Builder] The plus icon (repeatable) is overlapping a long label

### PR DESCRIPTION
**Pull request by mateusgomes01**
Fixes repeatable plus button overlap on long labels.

The fix was achieved by creating a new `ddm-label-repeatable` css class, which changes the label behavior so that it isn't overlapped by the plus and minus icons when the repeatable flag is true on the form component

### CODE REVIEW

**Comment by mateusgomes01** [comment]
ci:test

**Comment by natocesarrego** [comment]
ci:test:stop

**Comment by natocesarrego** [comment]
Hi @mateusgomes01, ideally, we shouldn't trigger the command `ci:test` once it'll run all tests existing in portal, instead let's run only `ci:test:relevant` and `ci:test:sf`. :wink: I'll trigger this commands to you. :slightly_smiling_face:

I'll start to review this pull right now.

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
