### PR TITLE
LPS-116590 make the necessary changes to guarantee that project template generate works on 7.3 properly

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-116590

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-portal/pull/175. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
