### PR TITLE
LPS-97802 using DDMFormTestUtil to avoid duplicated code

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-97802

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:forms

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Waiting https://github.com/natocesarrego/liferay-portal/pull/360 be merged to start review.

**Pull request closed without merging**
