### PR TITLE
LPS-105059 'Manage templates' dropdown is not updated after adding a new template

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @natocesarrego ,

Can you review this pull request, please?

It's a bit hacky so let me explain it a little bit.

- The original callback should update our dropdown but it is never called. 
- It should be called [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L1454) when eventName is triggered. Since we are not explicitely passing any eventName, then we take the [default](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L1369-L1371) one, _selectStructure_. But that event _selectStructure_ is never triggered in our workflow.
- My first idea was using [selectEntityHandler](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L1036) API since we can pass a container and an event to be triggered, just following [the pattern](https://github.com/liferay/liferay-portal/blob/master/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp#L70-L75) we use in many places in portal. So I could trigger _selectStructure_ event for our form.
- But that does not work here because we don't have any ['.selector-button'](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L1041) in our view-template.jsp
- So, we've decided to execute the code within the callback when the dialog is destroyed.

Let me know whether you have any doubt.

Thanks.

Regards.

/cc @robertoDiaz, @crodriguezy

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @antonio-ortega,

I'll review this pull in the beginning of the next week.

Best.

**Comment by robertoDiaz** [comment]
Hey @natocesarrego 

A customer is waiting for this fix and it is blocking other fixes as well.

Are you able to prioritize this? 

If not, can you send it to the PT and ask them to review it?

Thanks in advance.

Best regards.

**Comment by natocesarrego** [comment]
Hi @robertoDiaz,

I'll review it today. :)

Best.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @antonio-ortega and @robertoDiaz,

After analyze your proposed fix, I've the following comment to do:
- Why don't you include the `eventName` parameter in the [config object](https://github.com/liferay/liferay-portal/blob/3e55b126b1c166229085b5dae2b266d7f6077c47/modules/apps/dynamic-data-mapping/dynamic-data-mapping-taglib/src/main/resources/META-INF/resources/template_selector/page.jsp#L99-L112)? From what I could understand, this is the issue's root cause, right? If so, you can set the `eventName` parameter with the desired value and the mentioned callback will be executed. Once the modified code is encapsulated in the taglib code, then I don't see, at first, any problem to create a specific `eventName` to handle the template selector use case.

Best.

**Comment by antonio-ortega** [comment]
Hi @natocesarrego ,

Which eventName shall we pass? The default one, selectStructure, is never triggered and if we create a custom eventName we need to trigger it as well at some point. 

The root cause of this issue is that we need to trigger the event (default or a custom one) that's going to execute our callback at some point, but we couldn't find the way to do it because:

- My first idea was using selectEntityHandler API since we can pass a container and an event to be triggered, just following the pattern we use in many places in portal. So I could trigger selectStructure event for our form.
- But that does not work here because we don't have any '.selector-button' in our view-template.jsp
- So, we've decided to execute the code within the callback when the dialog is destroyed.

Thanks,

Regards.

**Comment by natocesarrego** [comment]
Hey @antonio-ortega,

I did a deeper analysis in the code and I just see two alternatives to address the current issue:

1. Include the parameter `eventName` with a custom value, like **saveTemplate**, and trigger this event through the `Liferay.fire` method at some point, for instance, before the dialog destroy event.
2. Use the solution proposed by you.

In regards to your solution, I just have a comment to do: can you please only attach the callback to the event if the callback isn't undefined? Please check this [line](https://github.com/liferay/liferay-portal/blob/b4ff05acd61ff7c63863fcc99fc42a300603637c/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L1454).

Antonio, let me know your thoughts about this comment and then we decide together the best way to move on with this pull request. 🙂 

Thanks.

**Comment by antonio-ortega** [comment]
Hi @natocesarrego ,

Following your proposal I've sent you natocesarrego#200.

Feel free to close this pull request if you consider better the other option.

Thanks!!

Regards.

**Comment by natocesarrego** [comment]
Hi @antonio-ortega,

Let's continue with your last proposed fix (natocesarrego#200). 😉

Thanks.

**Pull request closed without merging**
