### PR TITLE
LPS-83662 Site Content Reviewer role can be deleted despite Workflow Definition associated with it

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @natocesarrego 

Thank to your suggestion, I could add a method to check if the `KaleoDefinition` the `Role` is associated with is `active`.

Could you please take a look at the solution?

It disables the Delete action menu item and the checkbox for the row checker if the Role has an active workflow associated with it, or it there is currently a pending process for the workflow even if it is unpublished.

Alternatively, I could add the check when the Role is about to be deleted (in `RolesAdminPortlet`, in `deleteRole()` and `deleteRoles()`), so the validation would only take place when we actively choose a Role for deletion.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
ci:retest

**Comment by natocesarrego** [comment]
Yes, I can check it @IstvanD.

Regarding your solution which disables the checkbox, I've just one note: this solution can lead the user to an undesired understanding of the possibility to delete the Site Content Reviewer role. By default, the roles from portal, like Site Administrator, can't be deleted, hence the checkbox near the role is disabled, however it's not true for the Site Content Reviewer. Disabling the checkbox near this role, will omit from the user all the reasons which can avoid the deletion on this role.

Therefore, I believe that a solution which shows an error message like: _This role can't be deleted because it's associated to a Workflow definition_, would be a better option, once it explains and also teaches the user how to proceed to delete this role. Actually, this kind of error message is already being used through the portal, for instance, when the user tries to remove a structure which has a template associated to it, please take a look to this mentioned message below:

screen shot 2018-07-24 at 11 06 41 am

Can you please adapt your current solution according to this note?

Thanks in advance.

**Comment by IstvanD** [comment]
Hey @natocesarrego 

Yes, this explanation makes sense.
I'll change the solution to the one you suggested.

Best regards,
István

**Comment by natocesarrego** [comment]
Thanks, @IstvanD!

**Pull request closed without merging**
