### PR TITLE
LPS-111072 adding fieldset and legend tag

### PR DESCRIPTION
**Pull request by rijema**

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @rijema and @linolaoj,

When the `fieldset` tag is added, then the UI around the Forms fields is changed a little, right? Something like the following:

Screen Shot 2020-04-01 at 15 40 17

If this assumption is correct, then we'll need to discuss this proposed fix with the Forms Design before move on with this pull and probably make some CSS changes.

Best.

**Comment by linolaoj** [comment]
Hi @natocesarrego ,
I sent you a new pull request adding a commit to update a test. 
(https://github.com/natocesarrego/liferay-portal/pull/441)
Please see [this comment on LPP-36800](https://issues.liferay.com/browse/LPP-36800?focusedCommentId=2121987&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2121987) more details.

cc: @Sharryxue

Thanks!

**Comment by natocesarrego** [comment]
Hey @linolaoj,

Can you please close the https://github.com/natocesarrego/liferay-portal/pull/441 and update this pull with the test commit added by you? My goal is keep all history of this fix in the same pull. 😉 

In addition, I'll reach Forms designer soon for we discuss the best alternative regarding this proposed fix.

Thanks.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Hi @natocesarrego ,
I've closed https://github.com/natocesarrego/liferay-portal/pull/441. 
@rijema , is going to push the commit.

Thanks!

**Comment by natocesarrego** [comment]
Hi @cvanut and @brunofariasdeo,

Apparently, Forms test suite reported related failures, can you please double check and implement the necessary test fixes?

Thanks in advance.

**Comment by natocesarrego** [comment]
Additionally, the last commit of this pull request updates a *.path file (portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/TextInput.path) to fix some Poshi test, can you guys please check it too, @cvanut and @brunofarias?

**Comment by natocesarrego** [comment]
Hey @linolaoj,

Can you please provide more details to QA guys about your last commit?

Thanks.

**Comment by linolaoj** [comment]
Hi, @cvanut, @brunofarias,
the commit https://github.com/natocesarrego/liferay-portal/pull/422/commits/2b929e2f0330a6e44c715b656f88ce9e2a8f3b79 was added to fix the test StagingDMWithVariation#StagingDemoDocumentsAndMedia
The test was failing with the message:
`Element is not present at "//div[label[contains(.,'Maximum File Size')]]//input[@type='text']"`

Please let me know if you need more details.
Thanks!

**Comment by natocesarrego** [comment]
Hi @rijema and @linolaoj, I'll close this pull request, once @brunofariasdeo will do the necessary test fixes in other pull, please track https://github.com/brunofariasdeo/liferay-portal/pull/15 to be updated with its progress.

Thanks.

**Pull request closed without merging**
