### PR TITLE
LPS-116596 rename in order to guarantee the naming consistency

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related issue: https://issues.liferay.com/browse/LPS-116596

Changes made as requested [here](https://github.com/natocesarrego/liferay-portal/pull/665).

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Good job, @carolmariaabb! Feel free to trigger `ci:forward` if no relevant failure get reported.

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
