### PR TITLE
LPS-97967 Only basic and common properties remain unchanged when switching between field types from the Sidebar

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84455. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84456. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/bd7ab5bf7310~1...bd7ab5bf7310) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84486. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/46429416bbd6~1...46429416bbd6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
