### PR TITLE
LPS-71251

### PR DESCRIPTION
**Pull request by eperezg**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:retest

**Comment by natocesarrego** [comment]
Hi @eperezg,

You can send this pull straight to the Calendar team if you prefer or you want me to review it before send to the team?

Regards.

**Comment by eperezg** [comment]
I've resended here: https://github.com/brandizzi/liferay-portal/pull/393.

Regards

**Comment by natocesarrego** [comment]
Ok, @eperezg.

Regards.

**Pull request closed without merging**
