### PR TITLE
[TECHNICAL SUPPORT] LPS-131983 WCAG error for missing label association with input fields in Liferay Forms

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-131983](https://issues.liferay.com/browse/LPS-131983),
The WCAG problem is we are not providing an aria-labelledby attribute to our input fields and their label's aria-describedby attribute is missing a corresponding id on the input fields. This issue was observed with the date picker and the text fields using the forms.

Please review my changes,

Thanks.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
Hey @NemethNorbert, can you please check the reported failures?

The unit tests failures seems to be related.

Thanks.

**Comment by NemethNorbert** [comment]
Hey @natocesarrego,

I locally built my branch and tested my changes. I did not see any problem, however the tests are failing due to the id and aria-labelledby changes I made.

**Comment by natocesarrego** [comment]
Thanks, @NemethNorbert. I'll close this pull. Once you fix the tests please resend.

**Pull request closed without merging**
