### PR TITLE
LPS-82829 Take into account when the week doesn't start on Sunday

### PR DESCRIPTION
**Pull request by hudakl**
Hi Renato,

Could you please review my changes for LPS-82829?

Thank you,
Laci

### CODE REVIEW

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Good job, @hudakl! 👏 

Your pull looks good to me!

I just have one question: can you please explain a little bit more the logic implemented by you in the method **getWeeksInMonth**? I'm not sure if I could understand the solution completely.

Best.

**Comment by hudakl** [comment]
Hi Renato,

I found that for a Javascript date object numbers are assinged to the days of the week. 0-6 interval is assigned to the Sunday-Monday interval. In the database, for the first day of the week we store this number. 

My logic rotates the numbering in accordance with what we consider the beginning of the week, e.g. 0-6 will be assigned to Monday-Sunday interval. If we substract the first-day-of-the-week-number from the current day's number we get the rotated value for some of the days. Of course there could be negative values this way. To these we just need to add 7 to get the correct rotated number.

Does this explain the logic?

Thanks,
Laci

**Comment by natocesarrego** [comment]
Thanks for your explanation, @hudakl!

In addition, the issue reported by CI is not related. I'm forwarding your pull right now.

Best.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/72. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
