### PR TITLE
LPS-133661 Make visible the error message of the required fields

### PR DESCRIPTION
**Pull request by marcelabc**
Related Issue: https://issues.liferay.com/browse/LPS-133661

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @marcelabc, can you please check if these failures are related to your changes? Thanks

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by natocesarrego — COMMENTED** [review]
@marcelabc, should we do the same for the field `Search Location`?

**Comment by marcelabc** [comment]
@natocesarrego What do you mean about "do the same"? Could you please be more specific? 
In this PR, I'm removing a feature flag of a finished story. The search location story is not ready to delete the feature flag :)

**Comment by marcelabc** [comment]
@natocesarrego I think I know what do you mean. I forgot to enable in the Search Location field as well. Is it?

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
@marcelabc, will we release the story which allows the user edit the required error message on the coming GA release (GA3), right?

If so, can you please make sure that Mariana Huggins is aware of it?

Thanks in advance

**Pull request closed without merging**
