### PR TITLE
LPS-test test

### PR DESCRIPTION
**Pull request by marcosapmf**
Related Issue: https://issues.liferay.com/browse/LPS-test

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @marcosapmf, can you please fix the source formatter issues and resend? Thanks

**Comment by natocesarrego** [comment]
ci:stop

**Comment by natocesarrego** [comment]
ci:help

**Comment by liferay-forms** [comment]
Hey @marcosapmf, can you please check if these failures are related to your changes? Thanks

**Pull request closed without merging**
