### PR TITLE
LPS-126593 - Set the default value taking into account the Workflow defined for the current form

### PR DESCRIPTION
**Pull request by brunofariasdeo**
Related Issues: 
https://issues.liferay.com/browse/LPS-126593

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
