### PR TITLE
LPS-81710 Remove Matching Existing DDMFormFieldValues

### PR DESCRIPTION
**Pull request by brianikim**
Hello @natocesarrego ,

https://issues.liferay.com/browse/LPS-81710

This is a new PR to handle master side of the fix for LPS-81710.

Explanation of fix is in: https://github.com/natocesarrego/liferay-portal-ee/pull/30

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @natocesarrego ,

The failures do not seem related, but please let me know if you think otherwise.

Sincerely,
Brian Kim

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/94. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
