### PR TITLE
LPS-121426 Adjust tooltip symbol

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issue: https://issues.liferay.com/browse/LPS-121426

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
Hey @alinedoleron, did you have a chance to analyse if we could create some tests for this pull?

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@alinedoleron, can you please test your fix on IE 11 too? This way we can avoid future rework on this fix. 😉 

Thanks.

**Comment by alinedoleron** [comment]
> @alinedoleron, can you please test your fix on IE 11 too? This way we can avoid future rework on this fix. 😉
> 
> Thanks.

Tested on IE with success.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
