### PR TITLE
[TECHNICAL-SUPPORT] LPS-78206 fixing disable inputs when readOnly

### PR DESCRIPTION
**Pull request by rolandpakai**
Related links: https://issues.liferay.com/browse/LPS-78206

Hi @natocesarrego,

could you please review my changes.

Thanks, Roland

### CODE REVIEW

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
ci:test

**Comment by natocesarrego** [comment]
Nice job, @rolandpakai! 😃👍 

I'll just wait the CI result and if there are no related failures, then I'll forward it to the Product Team.

Best.

**Comment by rolandpakai** [comment]
@natocesarrego Thanks for the Review and the CI:test!

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/pedroqueiroz94/liferay-portal/pull/undefined. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/8ad2e624e544~1...8ad2e624e544) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
