### PR TITLE
LPS-83171 Do not extract the global group id from the map. It also contains regular live groups that could drive the targetGroupId variable to get the wrong value (in this case the live group instead of the staged group)

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test

**Comment by robertoDiaz** [comment]
ci:test

**Comment by natocesarrego** [comment]
Hey @robertoDiaz,

Have you sent this pull to me because you want a SME double check?

Best.

**Comment by robertoDiaz** [comment]
Yes

Or if you prefer you could fwd it to the PT

Regards

**Comment by natocesarrego** [comment]
Thanks for the clarification, @robertoDiaz.

I'll review it soon.

Thanks.

**Comment by robertoDiaz** [comment]
Hi, do you have any update on this?

Thanks!

**Comment by natocesarrego** [comment]
Hi @robertoDiaz,

I planned to review it today. Sorry for the little delay to review it, but I'm currently facing a high load.

Thanks.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hey @robertoDiaz,

Despite the fix for this issue requires a change in the DDM code, I understand that would be important send this pull request to the WEM team review, because it's an issue which very related to Journal Article. Furthermore, I don't see any problem with your solution. 🙂 

Best.

**Comment by robertoDiaz** [comment]
In fact the error is not in the Journal code, the problem here is that the structures are been imported in the wrong group.

Maybe WCM team do not need to review it, just been notified seems to be enough.

Anyway, if you prefer to send the pr to them,  feel free to do it.

Thanks!

**Comment by natocesarrego** [comment]
Hi @robertoDiaz,

I'll send it for the DDM team review and also mention Eudaldo.

Thanks.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/pedroqueiroz/liferay-portal/pull/164. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
