### PR TITLE
LPS-117482 Code refactoring

### PR DESCRIPTION
**Pull request by alinedoleron**
https://issues.liferay.com/browse/LPS-117482

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/707. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/37d2a580fda7~1...37d2a580fda7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
