### PR TITLE
LPS-82502 Overlapping Calendar Events

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @natocesarrego 

In case you are not the reviewer for Calendar, please ignore the pull request.
Unfortunately I could not found an up-to-date documentation on the members of the Calendar Engineering team like the one for the Forms team.

The issue is that no matter how small is time frame, the minimum size of the event's rectangle is of a half hour event. If event1 starts at say 11:53, and ends at 12:00, it will be covered entirely by event2 which start at say 12:00.

The event's rectangle height cannot be shortened because the name label would hang over the frame.

Normally, if an event is overlapped by a later event, the later event's width will be reduced half a column.
However, in the above case, event2's width will not be reduced, since it starts just after event1 ended.

The intersection detection logic is implemented in the `intersects()` function in **aui-scheduler-view-day.js**
The approach I used for solving the issue is to override the function in `scheduler_models.js` where `SchedulerEvent` is extended, by extending the timeframe of the event (endDate + 30 minutes) whom with other event's are compared for collision.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by natocesarrego** [comment]
Hi @IstvanD,

Currently, the Calendar Portlet is assigned to the Workflow team. Yeah, it sounds strange, but it's how it's organized. I've created a Grow article similar to the Forms Grow article you've mentioned and you can see it [here](https://grow.liferay.com/people/Workflow+team+-+Support+wiki). My goal is keep these two articles updated and make them good references for the TSEs.

If, for some reason, you miss any information in these articles or need any other information, you can reach me through email or Hangouts. I'll be glad to help you. 🙂 

Best.

**Comment by IstvanD** [comment]
Hey @natocesarrego 

Good to know that, I'll save that article too to my bookmarks.

I'll send the pull request to the reviewer of that component then.

Thanks and have a pleasant weekend,
István

**Comment by natocesarrego** [comment]
Please bookmark it and share with the TSEs from Hungary. 😉 

Have a nice weekend too!

**Comment by IstvanD** [comment]
Thanks, I've shared them with the Hungarian TSEs.

**Pull request closed without merging**
