### PR TITLE
LPS-95488 Cannot search for Workflow Task if the asset's name is an asset type

### PR DESCRIPTION
**Pull request by rgusztus**
Hi @natocesarrego!

 Could you please review this pull request?

Thank you in advance!

Best Regards,
Robert

### CODE REVIEW

**Comment by rgusztus** [comment]
ci:test:search

**Comment by rgusztus** [comment]
ci:test:search

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @rgusztus,

Your idea to fix the issue seems to be right for me, but I don't feel 100% comfortable that it'll not impact in other parts of Workflow due to my poor knowledge about this specific code (Workflow / Search). Therefore, if CI doesn't raise any issue related to your pull, I'll forward it to the Workflow team for you get a better review.

Best.

**Comment by rgusztus** [comment]
Hi @natocesarrego 

 Great, thank you!

Regards,
Robert

**Comment by natocesarrego** [comment]
ci:test:stop

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @rgusztus,

CI seems to be facing issues right now, thus I'll wait a little bit to run CI again.

Thanks for your patience.

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/188. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
