### PR TITLE
LPS-109042 some fields don't have options

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Good job, @linolaoj! 👏 😄 

I'll just wait CI outcomes and if everything looks good, then I'll forward your pull.

Thanks.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86052. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
