### PR TITLE
LPS-126168

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-126168

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Hi @adolfopa, I included a condition to just add the `FileItemSelectorCriterion` if the field is not in the Forms portlet.
I tested with `DM` and `Journal` and it works according to [LPS-125994](https://issues.liferay.com/browse/LPS-125994).

Thanks!

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
