### PR TITLE
LPS-101555 Show clear button when adding any type of file to form

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
submitted to BChan at https://github.com/brianchandotcom/liferay-portal/pull/83298

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
