### PR TITLE
LPS-105460 Keep transient fields in case of invalid captcha input

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:forms

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:forms

**Comment by rafaprax** [comment]
subimitted to BChan at https://github.com/brianchandotcom/liferay-portal/pull/83406

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
