### PR TITLE
LPS-94401 Enable move cursor on App Builder sidebar

### PR DESCRIPTION
**Pull request by brunofariasdeo**
https://issues.liferay.com/browse/LPS-94401

### CODE REVIEW

**Comment by brunofariasdeo** [comment]
ci:test:sf

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by brunofariasdeo** [comment]
Hi @natocesarrego,
As I was looking for a solution for this issue, I've identified that the [grab cursor](https://cdn0.iconfinder.com/data/icons/cursor-3/64/Artboard_24-512.png) is not support by Internet Explorer.
I have set the [move cursor](https://static.thenounproject.com/png/72154-200.png) as a workaround, and both Aline and Felipe agreed that it was fine to proceed with this solution - only for IE.
Thanks!

**Comment by natocesarrego** [comment]
Amazing job (fix and communication with Felipe and Alininha), @brunofariasdeo! 😄 👏

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
