### PR TITLE
[TECHNICAL SUPPORT] LPS-97871 Filtering and ordering options in workflow tasks become disabled if selecting a filter with zero results

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @natocesarrego,

[LPS-97871](https://issues.liferay.com/browse/LPS-97871) / [PTR-1063](https://issues.liferay.com/browse/PTR-1063) 

Please review it.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/phcp/liferay-portal/pull/22. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/0f74cc0a4010~1...0f74cc0a4010) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
