### PR TITLE
[TS] LPS-103224 - Elasticsearch "Limit of total fields has been exceeded" error is produced if you have a lot of DDM Structures

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-103224

Hi @natocesarrego 

@arboliveira has reviewed your PR https://github.com/arboliveira/liferay-portal/pull/856 and he said it can be sent to upstream

I have rebased it to latest master (I had to regenerate buildLang)

I have also added a little explanation to the breaking changes file as it can cause problems to the customers that have custom developments that execute queries using ddm_* fields, have a look to it in the last commit [`c50d5e2` (#701)](https://github.com/natocesarrego/liferay-portal/pull/701/commits/c50d5e26b6b842c113d132f30110130ef3b517ed)

Thank everybody for the effort solving this issue

/cc: @lipusz @BryanEngler

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
It seems there are problems with source formating, see https://liferay.slack.com/archives/C1SJ64S9X/p1595844198074300

**Comment by natocesarrego** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
