### PR TITLE
LPS-63229 Improving data provider search security

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-63229

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86729. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/44524ae5b420~2...44524ae5b420) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/389. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/5867f3fb23dd~2...5867f3fb23dd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
