### PR TITLE
LPS-97233 Show data providers when changing to staging

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
https://github.com/carolmariaabb/liferay-portal/pull/10

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Great job, @carolmariaabb! 👏

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84324. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
