### PR TITLE
LPS-106870 dispatch event after value is set unless autocomplete is enabled

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @linolaoj,

Your pull looks good to me, but I'd like to hear the opinion of @brunobasto, once this fix changes an important code of Text field.

Bruno, can you please check Lino's solution? It's a small fix. 😉 

Thanks in advance.

**Comment by brunofarache** [comment]
@natocesarrego this is a weird bug in IE11. we need to be evaluate if it's worth including this fix since it rarely happens.

**Comment by natocesarrego** [comment]
Closing pull request, once the LPS-106870 will be escalated to Forms team analyze and find out the best way to address the reported issue.

**Pull request closed without merging**
