### PR TITLE
LPS-116665 Fix accessibility issues in Forms

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @natocesarrego ,

Can you have a look at this PR, please?

It's fixing the four cases listed in LPS-116665

1. There are wrong translations into Spanish
2. Labels and inputs are not related
3. Contrast color is insufficient in paragraph field
4. Asterisk for required fields is not accessible

Let me know if have any question about it.

Thanks,

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @antonio-ortega, how are you?

I'll forward your pull to @carolmariaabb, once she has been working on issues, answering PTRs and also fixing tests associated to Accessibility in Forms and I believe she is more than capable to review it. 🙂 

@carolmariaabb, can you please review this pull?

Thanks in advance.

**Comment by natocesarrego** [comment]
Pull request forwarded to https://github.com/carolmariaabb/liferay-portal/pull/163. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
