### PR TITLE
LPS-102643 Problem saving decimal metadata with italian locale

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @natocesarrego,
I resend the pull as you asked. :)
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @MarcellGyopos,

I think the liferay-continuous-integration bot isn't properly configured to your repo/account and, probably, this is the reason for your CI commands no trigger the CI.

Best.

**Comment by natocesarrego** [comment]
Hey @MarcellGyopos,

Can you please run locally the command `ant format-source-current-branch` in `[PATH_LIFERAY_PORTAL_CODE]/liferay-portal/portal-impl`? This command will look for the SF issues associated only to the files modified by you in the current branch. Using this command we'll will get rid of the SF issues. 😉 

Best.

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego,
I forget to push the SF commit from the previous pull request before you started the CI:SF. 
But if you check it, I pushed it right after the failed results. :)

Anyway, did you test it without the other "regression" commit?
Best,
Marci

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Hi @MarcellGyopos,

I didn't test it locally yet, because I was waiting we get rid of all SF issues. If CI reports no more failures related to SF, then I'll proceed to the local tests. 😉 

Best.

**Comment by natocesarrego** [comment]
Green light for local tests!

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hey @MarcellGyopos,

I just tested your fix locally and, as you told me previously, the fix didn't worked as expected. In light of this, if we use the first commit of your previous pull, then this fix will work, but, probably, the [LPS-93619](https://issues.liferay.com/browse/LPS-93619) will be reintroduced.

Have you considered this problem? If so, how have you planned to solve it?

Best.

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego,
I think Lianne's commit is fixing the whole problem. I think, with her LPS we can put back the old value.
Best.

**Comment by natocesarrego** [comment]
Can you please share what commit is that, @MarcellGyopos?

Thanks.

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego,
The way I see it, the LPS-100797 makes it safe to use again the defaultLanguageId.
May I suppose it wrong?
Best regards,
Marci

**Comment by natocesarrego** [comment]
Hey @MarcellGyopos,

Do you mean that this pull only demands the [LPS-100797](https://issues.liferay.com/browse/LPS-100797) to work as expected, is it right?

Thanks in advance for your clarification.

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego,
Today a met with a really similar problem. Just as we can put a decimal number into a decimal field, we can do the same in the number field. What do you think about extending the method setDDMFieldLocalizedValue()'s if statement to (type.equals(FieldConstants.DOUBLE) || type.equals(FieldConstants.NUMBER))?
Best regards.

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego ,
I think yes, because of this snippet `if (defaultEditLocale == null) {
				defaultLanguageId = LocaleUtil.toLanguageId(ddmForm.getDefaultLocale());
			}
			else {
				defaultLanguageId = LocaleUtil.toLanguageId(defaultEditLocale);
			}`
prevent the issue. Furthermore I sent 2 SDHs to the costumers  which contain this code and there is no wrong feedback. 
Best.

**Comment by natocesarrego** [comment]
Hi @MarcellGyopos,

Your suggestion to include the **Number** field to the `if` statement of your proposed fix makes sense to me.

In regards to use the [LPS-100797](https://issues.liferay.com/browse/LPS-100797) with this pull request, honestly, I believe I already did and the issue wasn't solved, but I'll double check and I let you know the result.

Best.

**Comment by natocesarrego** [comment]
Hey @MarcellGyopos,

I just tested the fix of this pull on top of the most recent version of master, which has the LPS-100797 merged, and unfortunately the issue still happens, when I input **1,0**, then **10.0** is rendered.

Can you please check it, Marcell?

Thanks in advance.

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego ,
I've checked it too. I get the same. Something is changed..

**Pull request closed without merging**
