### PR TITLE
LPS-130714 Ignore Forms#SubmitFormWithRequiredConfirmationTextField Poshi test

### PR DESCRIPTION
**Pull request by brunofariasdeo**
Related Issue: https://issues.liferay.com/browse/LPS-130714

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by brunofariasdeo** [comment]
ci:stop

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@brunofariasdeo, please trigger `ci:forward` once the tests pass.

Thanks.

**Comment by brunofariasdeo** [comment]
ci:forward

**Pull request closed without merging**
