### PR TITLE
J cords lps 74454 revised

### PR DESCRIPTION
**Pull request by joshuacords**
Forwarding to you at Jonathan's [request](https://github.com/jonathanmccann/liferay-portal/pull/1409#issuecomment-327822243)
https://issues.liferay.com/browse/LPS-74454
https://issues.liferay.com/browse/LPP-26631

I deprecated instead of changing original deleteCalendarBookingInstance methods. I also addressed the issues present with tests.

Older Notes:
Deleting an instance or multiple instances (with Following option) of a recurring calendar booking will now notify participants.
The children of the calendar event were found through different logic than what deletes the events because changing the deleteCalendarBooking method here and elsewhere would create cascade of changes to the portlet.
Originally I found that the best pattern to follow would be:
-Users aren't notified if the deleted event is in the past.
-User is notified with Deleted template if 1 occurrence is deleted
-User is notified with Updated template if multiple occurrences are deleted
However, our framework doesn't have the supporting methods necessary to easily implement this. In particular calendarBooking.getStartTime() is not updated when the first event in a recurring series is deleted. As such, I just to the Delete Notification Template when a user deletes 1 or more instances of a Calendar Booking. This breaks with the implementation a little, but it doesn't seem worth the effort to follow it perfectly in this case.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:reopen

**Comment by natocesarrego** [comment]
Hi @joshuacords,

Thanks for sending this pull to me. 😃

Is there any special reason for you send this pull to me instead of send it straight to the PT? Generally, the TSEs send a pull to me only if they want to get a second opinion about their fixes, on the other hand they send it straight to the PT. Therefore, would you like to get a second opinion about this pull or do you feel fine to send it to the PT?

Thanks.

**Comment by joshuacords** [comment]
Hello @natocesarrego, I'm pretty sure Jon wanted a second opinion on these changes. (He's out of the office today.) Would you be able to review them?

**Comment by natocesarrego** [comment]
Hi @joshuacords,

Sure I can take a look on this pull, however it won't be fast, because I'm currently facing a high load of SME requests (pulls and tickets). But, don't worry I'll review it ASAP.

Thanks.

**Comment by joshuacords** [comment]
I appreciate it!

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @joshuacords,

I've executed the steps to reproduce of the LPS-74454 and the notification email is being sent, however the link included in the notification email redirects the user to view an event having the data (start time and end time) of the first event of the recurrence. Imagine the scenario described in the LPS-74454, which you have 6 instances in the recurrence, and you delete just the second instance, then the link in the email should redirect the user to a page having the data of the deleted instance and not the first instance.

Additionally, do you mind to create an unit/integration test to check the scenario of this ticket?

Best.

**Comment by joshuacords** [comment]
Hello @natocesarrego, thanks for reviewing this. I'm going to look into how to change the notification. I'll also attempt creating a test, but I don't have much experience in that area. As far as the deprecated with no replacement - my understanding is that a regular deprecated method needed to have some sort of body leftover that called the new method, which isn't possible in this case. Do you know of an example in the portal where that is not the case and methods with added/changed parameters are deprecated with replacement?

**Comment by natocesarrego** [comment]
Ok, @joshuacords. Regarding the test creation, you can take a look in one of the existent integration tests and use it as a base to implement yours. 😉 

In addition, I've taken a look in the code and I've found an example exactly as yours and it has a direct replacement, please see this [code](https://github.com/liferay/liferay-portal/blob/7227093900666b12759b383063ac60a03956fa6c/modules/apps/forms-and-workflow/calendar/calendar-service/src/main/java/com/liferay/calendar/service/impl/CalendarBookingLocalServiceImpl.java#L277-L299).

Best.

**Comment by joshuacords** [comment]
Thanks for finding this @natocesarrego!

**Comment by natocesarrego** [comment]
You're welcome, @joshuacords.

**Comment by joshuacords** [comment]
I will be sending a new PR when I've made the changes.

**Comment by joshuacords** [comment]
Resent here: https://github.com/natocesarrego/liferay-portal/pull/96

**Pull request closed without merging**
