### PR TITLE
LPS-74698

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @natocesarrego,

Please, could you review this PR and tell me if the back URL after clicking in Workflow notifications should point to the list of notifications as this PR suggests or, by contrast, should point to the list of workflow tasks (or neither of both)?

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:retest

**Comment by natocesarrego** [comment]
Hi @dacousalr,

In my opinion, the fix suggested by your pull is correct and makes a lot of sense to me, however I'll need to double check with the Product Team Designer if the back button should point to the notifications list or not.

By the way, thanks for this fix. 😉 

Best.

**Comment by dacousalr** [comment]
Thanks @natocesarrego,

Unfortunately, it seems that, although this fix looks good, it is not aligned with the behaviour of the rest of components which use notifications.

I am going to close this temporarily until the decision be made.

Thanks again

**Comment by natocesarrego** [comment]
Hi @dacousalr,

I've just talked with the PT Designer and she believes that the both options, back to notifications list and back to Workflow Tasks, won't be the ideal solution. In addition, she has mentioned that she is already discussing with the Lexicon team about some UX improvements to be done in Workflow. After that discussions, the Workflow team will be better prepared to address these UX issues. For now, she has suggested for you remove the back button, once the user can back to notification through the back button of the Browser or use the Side Bar Menu to do it.

If you need anything else please let me know.

Regards.

**Comment by dacousalr** [comment]
Thank you so much @natocesarrego,

I will do it so for Workflow.

Thanks again

**Pull request closed without merging**
