### PR TITLE
[TS] LPS-101544

### PR DESCRIPTION
**Pull request by matthewchan1**
https://github.com/natocesarrego/liferay-portal/pull/170

Hello @natocesarrego, 

I think these changes should handle our problem with some Select options "disappearing". I realized we were adding placeholder values constantly when getting options, and never removing them. Eventually this causes strange behavior for array indexing, but this fix ought to clear up the error.

### CODE REVIEW

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by matthewchan1** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Good job, @matthewchan1! 👏 😄 

I know you needed to send more than one pull request to make your solution be accepted, but let's see what you got with that:

- You learned a little bit more about how the things work in DDM front-end.
- Your solution is fixing **two** issues instead of just one.

Thanks for your hard work!

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78840. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/889fd636b8e6~1...889fd636b8e6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
