### PR TITLE
LPS-102643 Problem saving decimal metadata with italian locale

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @natocesarrego 
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @MarcellGyopos,

Can you please check this SF issue? Please run the SF check locally. 😉 

Thanks.

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego,
Fixed it, thank you.

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Hi @MarcellGyopos,

This pull still contains SF issues. 😞

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego,

I don't have sf issues in my local branch.
SF outcome:

> Configuration on demand is an incubating feature.
> 
> Task :apps:dynamic-data-mapping:dynamic-data-mapping-taglib:formatSource
Dependency 'com.liferay:com.liferay.source.formatter:1.0.934', published Mon Nov 04 22:16:49 CET 2019, is older than the latest one available ('com.liferay:com.liferay.source.formatter:1.0.941', published Tue Nov 19 10:49:30 CET 2019), but not yet expired
> 
> BUILD SUCCESSFUL in 14s
> 1 actionable task: 1 executed

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Thanks for double check this SF issue, @MarcellGyopos. 😉

**Comment by natocesarrego** [comment]
Hi @MarcellGyopos,

According to our discussion on the [PTR-1276](https://issues.liferay.com/browse/PTR-1276), I remember that this fix is dependent of the backport of the [LPS-100797](https://issues.liferay.com/browse/LPS-100797), however this backport is still **In Review** status, hence we can't proceed with this pull request until this backport is merged. 😞 Unfortunately, we can't use the first commit of this pull to fix the [LPS-100797](https://issues.liferay.com/browse/LPS-100797).

Once the mentioned backport is completed, please resend this pull without the first commit.

Thanks.

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego ,
Without the first commit, we send en_US Local value for DDMFormValuesToFieldsConverterImpl.setDDMFieldLocalizedValue(Field ddmField, String type, Value value) regardless of the DDM value language. Without it, the rest will not work.

The other commit has not been committed to 7.1.x yet, because it was rejected by regression due to a faulty test case (https://github.com/liferay/liferay-portal-ee/pull/17111). I understand, why we have to wait for the other pull, but why I have to left the first commit? 

Best regards,
Marci

**Comment by natocesarrego** [comment]
Yes, I can, @MarcellGyopos. 🙂 

From what I could understand from [our discussion](https://issues.liferay.com/browse/PTR-1276?focusedCommentId=1992643&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1992643) in the PTR-1276, the proposed fix for LPS-102643 requires the fix for [LPS-100797](https://issues.liferay.com/browse/LPS-100797) to address the issue reported in LPS-102643 and I also understood that the first commit of this pull is, actually, an alternative solution for the [LPS-100797](https://issues.liferay.com/browse/LPS-100797). Thus, I asked you to remove the first commit based on my current understanding.

Is my current understanding correct? If not, can you please share your thoughts regarding the dependencies of the LPS-102643?

Thanks.

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego ,

Yes, LPS-102643 is building on LPS-100797. But, in my opinion, LPS-100797 is insufficient. If I don't send the first commit to you, the rest of the code that you wrote before is going to do nothing. I suggest you try it locally, leave the first commit and use only the second from LPS-102643.  You will see it will not work. After LPS-100797 we need to revert back the 139. line value in start.jsp to "defaultLanguageId" , because LPS-100797 changed the logic.
Best.

**Comment by natocesarrego** [comment]
I see your point, @MarcellGyopos, and I'll try it locally when you send the new pull. But, if we use the first commit of this pull, then we, probably, will reintroduce the [LPS-93619](https://issues.liferay.com/browse/LPS-93619). Therefore, we need to consider it too.

Thanks.

**Pull request closed without merging**
