### PR TITLE
LPS-69112

### PR DESCRIPTION
**Pull request by brandizzi**
Hey @brandizzi,

Attached is an update for http://issues.liferay.com/browse/LPS-69112.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hey @natocesarrego, any update on this? It's for a customer ticket which has been open for a while.

Thanks!

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hey @dustinryerson,

Once your PR is exclusively CSS and SASS, I'm taking I little bit more time to review that once those things are not in my day by day, ok? But, don't worry because I'm working on this now.

Regards.

**Comment by dustinryerson** [comment]
Thank you for the update, @natocesarrego! I appreciate your time on this.

**Comment by natocesarrego** [comment]
Hi @dustinryerson,

You've done a really nice job, congrats! 🎉 🎉 

I was looking to the new Calendar layout and I would like to make some comments. Please see it below:

1. When I resize the browser window to see how the Calendar fits in a small window, I've seen that the button **Today** has become a little bit minor than its neighbors after this new layout, please take look:

button today a little bit minor during resize

   There is any way to fix that?

2. Another behavior which I think that could be improved, in my opinion, should be the inclusion of a bigger padding or margin between the button **Today** and the buttons related to the time (Day, Week, etc) when the Calendar is taking 70% of the page (30/70 layout). Please take a look:

add a little big padding calendar 70

A nice example of padding or margin I've seen is the one you've used when the Calendar takes 30% of the page (30/70 layout), please see:

nice padding calendar 30

I'll wait yout considerations about my comments, ok? 😉 

Thanks.

**Comment by dustinryerson** [comment]
Hey @natocesarrego, thanks!

1. For the first question you had, what page layout was being used, and what side was it on (i.e. 30 or 70 of a 30/70 page layout).
2. For the second part you pointed out, I noticed in the screenshot that the buttons are not styled how I originally intended them to be styled. This may have been caused by 8f7a764.

Can you forward me this pull request? That way I can address the things you mentioned as well as fix the button styling to what I originally intended it to be when the calendar portlet is on the 70 side of a 30/70 page layout, when I first sent the pull to Jon.

Once I make the changes needed I'll send a new pull straight to you for review.

Does that sound ok?

Thanks for your time on this!

**Comment by natocesarrego** [comment]
Hi @dustinryerson,

> For the first question you had, what page layout was being used, and what side was it on (i.e. 30 or 70 of a 30/70 page layout).

Answer: I've used the 1 column layout and I've got this result when I was resizing the browser window to smaller sizes until the smaller one.

> For the second part you pointed out, I noticed in the screenshot that the buttons are not styled how I originally intended them to be styled. This may have been caused by 8f7a764.

Ok.

Yes, I can forward it back to you and then you send it back to me.

Thanks you too. 😄

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/dustinryerson/liferay-portal/pull/91. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/9fd18af~1...9fd18af) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Resent: https://github.com/natocesarrego/liferay-portal/pull/55

**Pull request closed without merging**
