### PR TITLE
[TS|Master] LPS-127758 - additional pull request

### PR DESCRIPTION
**Pull request by rijema**
Related Issue: https://issues.liferay.com/browse/LPS-127758

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
Good night, @natocesarrego . Here it is the follow up pull requested here #100716, this additional commit is ordering the DDMFormDisplayContext constructor and the affected classes :)

Renato, could you forward to Brian, please? I couldn't send directly to him according to liferay-continuous-integration feedback.

Let me know if any change is needed.

Thank you!

**Comment by rijema** [comment]
Good night, @brianchandotcom @natocesarrego . Here it is the follow up pull requested here #100716, this additional commit is ordering the DDMFormDisplayContext constructor and the affected classes :)

Renato, could you forward to Brian, please? I couldn't send directly to him according to liferay-continuous-integration feedback.

Let me know if any change is needed.

Thank you!

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
