### PR TITLE
LPS-163645 Move to Instance Settings the properties related to the user's public and private layouts

### PR DESCRIPTION
**Pull request by torresvictor100**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@torresvictor100, there is a chance of this pull have related test failures, because of that I'm re-running the tests. In addition, please edit the commit messages replacing the LPS-163628 by the LPS-163645 and LPS-163646, since the LPS-163628 is actually the task and not the subtask. Check the image below:

image

Thanks in advance

**Comment by torresvictor100** [comment]
ci:test:relevant

**Pull request closed without merging**
