### PR TITLE
LPS-106120 Use default site language when creating new records

### PR DESCRIPTION
**Pull request by JavierMoral**

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82534. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Good job, @JavierMoral! 🙂

**Pull request closed without merging**
