### PR TITLE
LPS-115096 Sort annotations alphabetically

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Great re-work on this pull, @alinedoleron! Congrats! 😄

I'll just update the last commit message to make it more clear, ok?

Thanks.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/661. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
