### PR TITLE
LPS-82500

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/86050

**Comment by natocesarrego** [comment]
Ok, @brianchandotcom. @carolmariaabb, can we talk about it later?

Thanks.

**Comment by carolmariaabb** [comment]
> Ok, @brianchandotcom. @carolmariaabb, can we talk about it later?
> 
> Thanks.

Ok @natocesarrego!

**Comment by natocesarrego** [comment]
Pull request forwarded to https://github.com/carolmariaabb/liferay-portal/pull/25. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
