### PR TITLE
LPS-73152 Organizing schema versions in Calendar service module

### PR DESCRIPTION
**Pull request by achaparro**
Hi @natocesarrego,

I want to send you this pull request as Calendar SME.

We need to keep schema versions number 1.0.* for those upgrade processes which can be backported to ee-7.0.x. Current upgradeSchema process hasn't been backported (this is correct) but it has the schemaVersion 1.0.6. Right now we need to add a new upgrade process for current Liferay 7 and DXP users and we can not because there are no free schemaVersion numbers to keep consistency between Liferay 7/DXP schemaVersion and future release. 

For that reason I have moved upgradeSchema class from 1_0_6 path to 2_0_0.

Please, talk to the calendar team (@brandizzi) to take into account this in the future. 

Also, let me know if you have any question about this.

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by natocesarrego** [comment]
Hi @achaparro,

I'll take a look on it. Thanks.

By the way, is this a new decision regarding the upgrade processes or not? I mean the fact to keep it using the pattern 1.0.*.

In addition, is there any documentation describing this rule?

Regards.

**Comment by achaparro** [comment]
Hi @natocesarrego,

Answering your questions:

> By the way, is this a new decision regarding the upgrade processes or not? I mean the fact to keep it using the pattern 1.0.*.
More than a decision, it's a natural way to avoid upgrade problems in the future. If we don't reserve versions for upgrade processes we need to backport customer won't be able to upgrade in the future since the schema versions won't match with future releases or some upgrade processes will be skipped.

> In addition, is there any documentation describing this rule?
I am preparing a complete documentation for rules with upgrade processes. For sure, I will include this. I will announce it in Loop soon.

Thanks.

**Comment by natocesarrego** [comment]
Thanks for all the clarifications, @achaparro. 😃 

I'll forward this pull and the natocesarrego#85 to @brandizzi and talk to him about this rule.

Thanks for letting me know about this. 😉 

Regards.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/423. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
