### PR TITLE
LPS-116665 Fix form fields paths in tests

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-116665

Hi @carolmariaabb ,

Here you can see the changes to avoid orphaned form labels in Single and Multiple selection fields in forms.

We are getting a step closer to what is required although it is not perfect yet and it is not as it was suggested in PTR-1845. The changes suggested in that PTR must be applied in Radio and Checkbox components in Clay which will widely modify their markup. Due to that, I think it is safer to apply this changes for now, and we might face the race of the changes in a separate issue for Clay.

Thanks.

Regards.

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@carolmariaabb, I'll re-run the relevant suite to double check if the reported failure is related or not.

Thanks.

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@carolmariaabb, the test **Forms#SubmitFormWithMultipleFieldsAndViewEntriesViaDescriptiveDisplay** failed on the last 2 executions of the relevant suite, can you please check if it's related to this pull?

Thanks in advance.

**Comment by carolmariaabb** [comment]
ci:test:app-builder

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:app-builder

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Hi @natocesarrego ,

I closed it to try to understand why the `SharedAppBuilder#ReuseExistingFormViewFields` test is failing.

Thanks!

**Pull request closed without merging**
