### PR TITLE
[TECHNICAL SUPPORT] LPS-110205 Use request shared attributes

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-110205

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:forms

**Comment by rodrigopaulino** [comment]
ci:test:app-builder

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86630. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
