### PR TITLE
LPS-109490 Adds _localizedValue as a new property to avoid conflict with localizedValue

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by patriciajeanperez** [comment]
ci:test:revelant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
@natocesarrego sent to https://github.com/brianchandotcom/liferay-portal/pull/85549 as this affects app builder and we need to fix before the release.

**Pull request closed without merging**
