### PR TITLE
LPS-106870 - Test fixes

### PR DESCRIPTION
**Pull request by brunofariasdeo**

### CODE REVIEW

**Comment by natocesarrego** [comment]
Good job, @brunofariasdeo. 😄

**Comment by natocesarrego** [comment]
ci:forward

**Comment by brunofariasdeo** [comment]
Hi @natocesarrego,
Once ci:test:sf has failed, I have made some changes in order to be complaint with Source Format syntax.
Thanks!

**Comment by brunofariasdeo** [comment]
ci:forward

**Pull request closed without merging**
