### PR TITLE
LPS-121532 buildLang

### PR DESCRIPTION
**Pull request by natocesarrego**
Related Issue: https://issues.liferay.com/browse/LPS-121532

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @georgel-pop-lr,

I did few changes to your original pull and because of that I decided to test it locally to make sure it remains working as expected. During my local test, I realized the following:

1. If there is a form with 2 pages, for example, the first one having a required field and the second, without a required field then the message **Indicates required fields** is displayed on both pages, is this behavior intended? Should we display this message even on pages without required fields?

2. The message **Indicates required fields** apparently isn't following the alignment of its neighbor elements, please check the image below:

Screen Shot 2020-11-10 at 12 40 58

Additionally, I feel that the message is very close to the page's title too.

Regarding item number 2, I just sent a message to Forms team designer to get his opinion. 🙂 

@georgel-pop-lr, I know this pull is taking longer than expected during the review process, but honestly I see this as an opportunity to improve Forms and I'm doing my best to make it happen. Thanks for your patience along this review process.

**Comment by georgel-pop-lr** [comment]
> stly I see this as an opportunity to improve Forms and I'm doing my best to make it happen. Thanks for your patience along this review process

Hi @natocesarrego,

Don't worry if takes longer, your points are valid, I guess this message should be added only if the page has required fields, I thought that adding it to PageRenderer would verify each page individually. 
About the second item, I guess you are right is not well aligned, I guess is missing some kind of class.

Do you want me to take a look on any of this two items? 

Regards.

**Comment by natocesarrego** [comment]
Good to know, @georgel-pop-lr! 🙂

Let's do the following: tackle just the first item and the second one will be handled by Forms team. 😄 

Thanks.

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Hi guys, I've sent a [PR](https://github.com/natocesarrego/liferay-portal/pull/909) fixing the margins and paddings. Can I close this one, @natocesarrego?

**Pull request closed without merging**
