### PR TITLE
LPS-123366 sf

### PR DESCRIPTION
**Pull request by brunofariasdeo**
Related Issue: https://issues.liferay.com/browse/LPS-123366

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by brunofariasdeo** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @brunofariasdeo, can you please check if these failures are related to your changes? Thanks

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Good job, @brunofariasdeo! 😄 👏 🎉

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
