### PR TITLE
LPS-106502 Do not allow invalid punctuation for "Field Name"

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:test:close

**Comment by jeyvison** [comment]
ci:close

**Comment by jeyvison** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/83018

**Pull request closed without merging**
