### PR TITLE
LPS-104032 Fix regression bug in data provider caused by reference changes

### PR DESCRIPTION
**Pull request by mclomello**
@natocesarrego could u please review this pr?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80973. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
