### PR TITLE
LPS-122220 buildLang

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issue: https://issues.liferay.com/browse/LPS-122220

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/alinedoleron/liferay-portal/pull/176. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/6e6ad201cd4d~2...6e6ad201cd4d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
