### PR TITLE
LPS-111810 Add portletNamespace property for elements sets

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/468. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/ea896642a752~1...ea896642a752) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
