### PR TITLE
LPS-101943 Fix placeholder bug in ie11 for textarea tag

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @carolmariaabb , can you please move/adapt this fix for the Text.soy file and resend? 

Thx

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
