### PR TITLE
[Technical Support] LPS-69112

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @jonmak08 @brandizzi

https://issues.liferay.com/browse/LPS-69112

### CODE REVIEW

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @dustinryerson,

Thanks for include the two suggestions I've made to you. I've checked the both behaviors and they look great now. Nice job! 😄

However, I've identified a little misaligned after these last modifications in the layout 50/50 and the layout 30/70 (in both 30 and 70). I'll share some images to you see what I mean. Please take a look:

**Expected align:**

(layout 1 column)

calendar layout 1 column

**Actual align:**

(layout 50/50)

calendar 50 - layout 50 50

(layout 30/70 - using 30%)

calendar 30 - layout 30 70

(layout 30/70 - using 70%)

calendar 70 - layout 30 70

Can you please take a look on that? Sorry to delay the delivery of this to our customer, but I'm really trying to do the best to the Calendar. I hope you don't mind to fix this little misaligned. 😉

I'll let this PR opened for you just update it instead of send a new one, ok?

Thanks.

**Comment by dustinryerson** [comment]
@natocesarrego thanks for your diligence to make the calendar portlet the best it can be. No worries about the additional changes!

I've updated the branch with the latest commits to master and have rebased the commits for 	LPS-69112 on top. I've also added c171203 to fix the alignment issues.

Thanks!

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/350. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hey @dustinryerson,

Thanks for this modifications. 😄

I'm sure Adam will be very happy with the new look of Calendar!

Thanks.

**Comment by dustinryerson** [comment]
Thanks @natocesarrego!

**Pull request closed without merging**
