### PR TITLE
LPS-95258 add missing class

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
@carolmariaabb, your pull looks good, there is just a little source format issue, please check its correction when I forward this pull to Brian. 😉 Now, I'll wait CI results and if everything looks good, then I'll forward this pull.

Thanks.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86051. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/189c12cfb9bb~1...189c12cfb9bb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
