### PR TITLE
[TECHNICAL SUPPOR] LPS-118306 buildLang

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-118306

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@rodrigopaulino, can you please re-send due to conflicts?

Thanks.

**Pull request closed without merging**
