### PR TITLE
[Master] LPS-111072 Accessibility - Fieldset and Legend tags

### PR DESCRIPTION
**Pull request by rijema**

### CODE REVIEW

**Comment by rijema** [comment]
Hi @natocesarrego .

Here is the pull request about the LPS https://issues.liferay.com/browse/LPS-111072 .
I reincluded the commits reverted. 

Thanks.

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@rijema, are you able to tell me why your commits associated to this ticket were reverted?

Thanks in advance.

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by rijema** [comment]
Hi @natocesarrego 

Yes, sure I can explain to you! I talked to Matuzalém, engineer that took out the commits, and he explained to me that it was because it caused regression in the tests when they were migrating the fields and some visual regressions, that was the reason. As they didn't want to block their job, they ended up reversing these changes. In this pull request I’m reintroducing these commits, with a new regeneration of the snapshots.

**Comment by rijema** [comment]
I tried replicate the default title of the last commits, but if I did something wrong, please let me know! Thanks.

**Comment by natocesarrego** [comment]
Thanks for your explanation, @rijema. 🙂 Can you please re-send due to the rebase conflicts?

**Pull request closed without merging**
