### PR TITLE
LPS-116779 rename local variable

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-116779

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/706. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/3506bac99c3e~2...3506bac99c3e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
