### PR TITLE
LPS-119818 Create test to broken rules

### PR DESCRIPTION
**Pull request by alinedoleron**
https://issues.liferay.com/browse/LPS-119818

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:app-builder

**Comment by natocesarrego** [comment]
@alinedoleron, after our discussion today during daily meeting, I understand that I should wait to review this pull, am I right?

Thanks.

**Comment by alinedoleron** [comment]
Yes, @natocesarrego. I'm updating my environment to check if there're some changes that affected this PR. If you prefer I can close it.

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
new pr: https://github.com/natocesarrego/liferay-portal/pull/827

**Pull request closed without merging**
