### PR TITLE
LPS-104943 data source type might be type json

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @carolmariaabb,

Can you or @linolaoj please clarify why the property `dataSourceType` sometimes can be a JSON? In which use case it occurs?

Thanks.

**Comment by linolaoj** [comment]
Hi @natocesarrego ,
at [SelectDDMFormFieldTypeSettings.java#L102](https://github.com/liferay/liferay-portal/blob/7fac4c77baa75c8d429ffd7c35211025296fc4ed/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/java/com/liferay/dynamic/data/mapping/form/field/type/internal/select/SelectDDMFormFieldTypeSettings.java#L102)
the predefined value is an Array. But at [Select/Select.es.js#L245](https://github.com/liferay/liferay-portal/blob/7fac4c77baa75c8d429ffd7c35211025296fc4ed/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/Select/Select.es.js#L245) it is tested if the value is an Array or a String. 
I will look further to clarify which cases it is a String or Array.

Thanks!

**Comment by linolaoj** [comment]
@natocesarrego , 
When the user saves the form, json array is used to represent dataSourceType.
When the user publish/unpublish the form, string is used to represent dataSourceType.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82040. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
