### PR TITLE
LPS-121426 Do not cut legend circle for long texts

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issue: https://issues.liferay.com/browse/LPS-121426

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @alinedoleron, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@alinedoleron, is this fix addressing this same issue on Firefox and IE?

Thanks.

**Comment by alinedoleron** [comment]
> @alinedoleron, is this fix addressing this same issue on Firefox and IE?
> 
> Thanks.

I've tested only Firefox and it's ok.

**Comment by alinedoleron** [comment]
I'm sending a new pr because I saw the same issue on tooltip. https://github.com/natocesarrego/liferay-portal/pull/891

**Pull request closed without merging**
