### PR TITLE
LPS-120227 unit tests

### PR DESCRIPTION
**Pull request by marcosapmf**
Related Issue: https://issues.liferay.com/browse/LPS-120227

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @marcosapmf, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @marcosapmf, can you please check if these failures are related to your changes? Thanks

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @marcosapmf, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
Good job, @marcosapmf! 😄 

Is this same issue happening with the Select from List field?

Thanks.

**Comment by marcosapmf** [comment]
> Good job, @marcosapmf! 😄
> 
> Is this same issue happening with the Select from List field?
> 
> Thanks.

@natocesarrego, from what I see, it's not happening with other fields, just for Text

**Comment by natocesarrego** [comment]
Great, @marcosapmf! 😄 Thanks for your confirmation. 😉

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @marcosapmf, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @marcosapmf, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @marcosapmf, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@marcosapmf, can you please rebase this pull with the latest master, resend to your repo and trigger `ci:forward` by your own?

Thanks.

**Comment by natocesarrego** [comment]
I'm asking this because, unfortunately, this pull is unlucky against CI challenge. 😁

**Pull request closed without merging**
