### PR TITLE
LPS-78301 Weekday abbreviations in the recurrence dialog are not localized	

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @natocesarrego 

I added language keys for weekday abbreviations in the Calendar event recurrence dialog.
I also added German translation since the customer who reported the issue expected that translation.

Could you please take a look at this solution?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
Hey @natocesarrego 

I was wondering if you could find the time to take a look at this pull request.
Please tell me if you need any help or explanation.

Thank you,
István

**Comment by natocesarrego** [comment]
Hi @IstvanD,

As I mentioned on Loop, last Friday I was on PTO and hence the pull request reviews get delayed. But, don't worry, because I'll review it today.

Thanks for your patience. 😃

**Comment by natocesarrego** [comment]
Hi @IstvanD,

Unfortunately, this proposed solution only attends the needs of the English and German speakers, once the _buildLang_ execution hasn't translated the new language keys (_abbreviation.FR, abbreviation.MO, etc_) and I believe it won't be able to do it. Therefore, in order to address this issue, I suggest you use the three characters of the existent language keys related to weekdays, please check them [here](https://github.com/liferay/liferay-portal/blob/7c53cef0aff286a452eafa178976d1965ac39c3c/modules/apps/forms-and-workflow/calendar/calendar-web/src/main/resources/content/Language.properties#L188-L194). Following this instruction, you can fix this issue with something like this:

```
<%
String weekdayLabelKey = StringPool.BLANK;
String weekdayLabel = StringPool.BLANK;
String weekdayLabelAbbreviated = StringPool.BLANK;

for (Weekday weekday : weekdaysArray) {
	weekdayLabelKey = "weekday" + StringPool.PERIOD + weekday.getValue();

	weekdayLabel = LanguageUtil.get(request, weekdayLabelKey);

	weekdayLabelAbbreviated = weekdayLabel.substring(0, 3);
%>

	<aui:input checked="<%= weekdays.contains(weekday) %>" id="<%= weekday.getValue() %>" label="<%= weekdayLabelAbbreviated %>" localizeLabel="false" name="weekdays" type="checkbox" value="<%= weekday.getValue() %>" />

<%
}
%>
```
The code above gets the existent weekday keys, translates to the correct language and gets the first three characters of the translated keys. In addition, this solution makes sure the `aui:input` taglib won't translate the input's label (`localizeLabel="false"`), because it's already translated.

I checked this solution locally using three different languages and it works, however if you've any question or feedback, please let me know.

Best.

**Comment by IstvanD** [comment]
Hi @natocesarrego 

Many thanks!
I tested your version of the solution, and it is working great!
One thing of concern I find though is to determine how many characters should we abbreviate to, as it differs language to language.
For example, in English and German it is two, for Portuguese it's three, for Hungarian it varies depending on the day.
But maybe three would indeed be the most expressive and short enough at the same time.

What do you think?

Best regards,
István

**Comment by natocesarrego** [comment]
Hi @IstvanD,

You're welcome! 😉 

Additionally, I had the same concern as you about the number of characters to use and I believe three could handle the majority or all the cases, but, honestly, I'm one hundred percent sure. This is a corner case related to language and I think that we've two options:

1. Check all available languages to make sure this current implementation attends all the cases.
2. Raise this concern to other guys from Support to get some help.

What do you prefer?

If you prefer the option 1, we can share this check like: considering an alphabetic order, I can check the first half and you, the second half.

Best.

**Comment by IstvanD** [comment]
Hi @natocesarrego 

I have checked the languages, and found that it unfortunately it doesn't suits to Hebrew and Arabic, and as well as other languages that doesn't have the left-to-right, latin writing styles with Latin characters.

That means that maybe we should indeed introduce new language keys for abbreviations.

**Comment by natocesarrego** [comment]
Hey @IstvanD,

After your analysis, did you find just this left-to-right issue?

If so, we can try to address it checking the writing direction of the current language and if it's left-to-right, we take the first three characters, otherwise if it's right-to-left, then we take the last three characters or the complete weekday. In case we use the complete weekday, we just need to check if the layout can handle this change, i.e. doesn't break.

In addition, I'm trying to avoid the creation of the abbreviation language keys, because it won't be translated by **buildLang** and it can bother much more customers than the current solution.

Best.

**Comment by IstvanD** [comment]
Hey @natocesarrego 

I checked whether there is a programmatic way to determine the writing direction, but I could find no such information from the locales.
My intention is to abbreviate the weekday names only for the latin-1 and latin-2 character sets, and leave it alone for other charset for safety.
However, for every language, if I query the character set for the current locale, I get "UTF-8".

**Comment by natocesarrego** [comment]
Hi @IstvanD,

I've discussed this issue with the Brazil's Localization Lead to get a deep understanding of our translation process and, after all the discussion, I understand that the best option would be avoid the use of the abbreviations, due to the peculiarities of the supported languages. Therefore, I believe our best shot is use the already existent language keys: **weekday.FR**, **weekday.MO**, etc. I've already tested this solution using the apparently more complicated languages and it works without break the layout.

Therefore, I'll close https://github.com/natocesarrego/liferay-portal/pull/113 and wait another pull with this new proposed solution.

Thanks for your patience and contribution to address this issue. 😉

**Comment by IstvanD** [comment]
Hi @natocesarrego 

Thank you for taking the time to discuss this issue.
I submitted the pull request https://github.com/natocesarrego/liferay-portal/pull/114

Best regards,
István

**Comment by natocesarrego** [comment]
Hi @IstvanD,

Thank you too for the discussion and the fix.

Best.

**Pull request closed without merging**
