### PR TITLE
LPS-74301 Store parameters in request body to avoid 414 (Request-URI Too Long) error caused by many calendarIds

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey @natocesarrego,

Here's an updated fix based on your recommendation here: https://github.com/natocesarrego/liferay-portal/pull/90#discussion_r135327529

The request was already a POST, I just had to put the parameters in the body (payload) rather than in the URL (queryParameters).

Please let me know if you have any questions, and thank you again for your help with this!

https://issues.liferay.com/browse/LPS-74301

/cc @brandizzi

### CODE REVIEW

**Comment by natocesarrego** [comment]
Nice job, @dustinryerson! 😄 

Have you had chance to see my [comment](https://github.com/natocesarrego/liferay-portal/pull/90/commits/ec545a06be55053592834eeb57cfd1b42d3b7116#r135328676) regarding the ternary operator?

**Comment by dustinryerson** [comment]
Thanks!

I'm honestly not sure when BChan allows ternary operators vs. if/else statements. I've seen ternary operators used in some Liferay JavaScript files. I just figured if he didn't like them he'd change them to if/else statements. Either way I think this pull should be fine since I didn't add any new ternary operators.

Please let me know if you have any questions, and many thanks for the review!

**Comment by natocesarrego** [comment]
Ok, @dustinryerson.

I'll forward your pull to Adam. Can you please send a pull with the two commits related to this fix?

Pleasure to talk to you one more time.

Thanks.

**Comment by dustinryerson** [comment]
@natocesarrego the commit on this pull request (3604d4b) is the only commit needed for this fix.

Thanks!

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/453. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Thank you @natocesarrego!

**Pull request closed without merging**
