### PR TITLE
LPS-71029

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/392. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Nice job, @dacousalr !

Thanks.

**Comment by dacousalr** [comment]
Thanks to you, @natocesarrego!

**Pull request closed without merging**
