### PR TITLE
[TS|Master] LPS-127758 using admin user to check if form was published

### PR DESCRIPTION
**Pull request by rijema**
Hello, @natocesarrego. It's been a while, huh?

Thank you for pointing that changes on the last pull request, I've included in this one.
I sent it to your particular profile because you're already handling with this case. Let me know if I actually need to send to the liferay-forms user or if more changes are needed.

I also tested after the newest changes. No change in the current (and expected) behaviour :)

Results:
D5CBF2E9-BE2A-4700-9019-93471C41F6EC

Hasta luego!

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
Yeahh! Thanks for your detailed explanation, @rijema. :slightly_smiling_face: I'll forward it right now. Thanks.

**Comment by natocesarrego** [comment]
ci
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by rijema** [comment]
Locally tested: build successful with these Poshi tests.

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:reevaluate:1057401_7911

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
