### PR TITLE
LPS-110620 reactivating test from DDMFormInstanceStagingTest

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-110620

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@marcosapmf, a simple pull like this can be sent straightforward to Brian. 😉 

cc @carolmariaabb, this is an example of a simple pull that can be forwarded to Brian.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
