### PR TITLE
LPS-121765 Check the options quantity before and after removing an option and remove useless runAllTimers

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issue: https://issues.liferay.com/browse/LPS-121765

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hey @alinedoleron, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
@natocesarrego , I removed the
`act(() => {
			jest.runAllTimers();
		});
`
for both cases and it didn't make any difference so I'll let the test without it. I know it is used to wait until the timers being executed but in this case it seem to be useless. 
I've done this, just for testing, in other tests that was created by other people in this same file and the tests passed. So maybe there are other unnecessary cases. But I'll just do this on the test I wrote so I do not take the risk of breaking anything.

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/882. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Good job, @alinedoleron! I just updated the last commit message to remove the info related to run the timers, once it makes sense just for you and me during the review process. 😉

**Pull request closed without merging**
