### PR TITLE
LPS-83662 Site Content Reviewer role can be deleted despite Workflow Definition associated with it

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @natocesarrego 

As you suggested in https://github.com/natocesarrego/liferay-portal/pull/122#issuecomment-407422135, I adjusted the solution so that it runs a validation if a role deletion is attempted.

Could you please check if it OK this way?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by natocesarrego** [comment]
For sure, @IstvanD! 🙂

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Excellent job, @IstvanD! 😄 👏

I've needed to re-run _buildLang_, because in your original pull the language keys weren't fully translated. I'm sending the pull back to you for you forward it to the Product Team. Besides, I've realized that when the error messages related to the role validation are displayed, then the tab which lists a set of roles, like _Site Roles_, are switched to the _Regular Roles_ tab, please see the GIF below:

lps-83662

Can you please take a look to this behavior before forward it to the PT?

Thanks in advance.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/69. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/a2396676e26c~2...a2396676e26c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
