### PR TITLE
LPS-109545

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natocesarrego,

Attached is an update for http://issues.liferay.com/browse/LPS-109545.

> https://issues.liferay.com/browse/LPS-109545
> https://issues.liferay.com/browse/LPP-35461

> Problem: `updateDDMFormInputValue` gets called twice and when SPA is turned off this causes noticeable problems.

> Solution: Consolidate calls under `_onLiferaySubmitForm`

> FYI: https://issues.liferay.com/browse/LPS-50905 added the second call, but the preview ability is no longer available.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by joshuacords** [comment]
Hi guys, it looks like there's problems with the fix: 
LocalFile.FormRules#ConfigureRequireRule
LocalFile.Forms#SubmitFormWithRequiredTextField 
LocalFile.Forms#AddFormInGlobal
... etc.

**Comment by joshuacords** [comment]
@natocesarrego do you know when you'll be able to review this?

**Comment by joshuacords** [comment]
Hello @natocesarrego, could we have an update on this?

**Comment by natocesarrego** [comment]
Hi @jonmak08 and @joshuacords,

From what I could see from your solution, apparently, it's good to go and it can be forwarded, but before move on with it, I'd like to ask you the following:

1. When the event `submitForm` is fired, then is an event `submit` fired subsequently? Otherwise, the `ddmFormValuesInput` will be out of date and it can cause side effects.
2. Once this change can impact all DDM clients, like Web Content, Document and Media, DDL, etc, then would be important we run all tests (ci:test). Have you already done that? If not, can you please run it?

Thanks.

**Comment by jonmak08** [comment]
Hey @natocesarrego,

> 1. When the event `submitForm` is fired, then is an event `submit` fired subsequently? Otherwise, the `ddmFormValuesInput` will be out of date and it can cause side effects.

Why would `ddmFormValuesInput` be out of date, when it is called from within `_onLiferaySubmitForm`?

**Comment by joshuacords** [comment]
Full ci:test has not been run. Running now.

**Comment by joshuacords** [comment]
ci:test

**Comment by natocesarrego** [comment]
Hi @jonmak08,

The `ddmFormValuesInput` is updated through the method `updateDDMFormInputValue` which is invoked from the methods `_onSubmitForm` and `_onLiferaySubmitForm`, the event handlers attached to the events `submit` and `submitForm`, respectively. Therefore, once the proposed fix removes the event handler attached to the `submit` event, then I'm wondering if update the `ddmFormValuesInput` only when the event `submitForm` is fired is enough to make sure the `ddmFormValuesInput` will be updated. Do you guys can confirm that when the event `submitForm` is fired, then a subsequently event `submit` is fired too? Could I clarify my question now, @jonmak08?

Thanks.

**Comment by natocesarrego** [comment]
Hey @joshuacords,

I just did a quick check on the test results and it looks good to go, what do you think?

Best.

**Comment by natocesarrego** [comment]
Ok, @joshuacords. Thanks for your clarification. 🙂 I'll forward your pull right now.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86176. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
