### PR TITLE
LPS-73153 Leave micro digit in schema version for those upgrade processes we need to backport

### PR DESCRIPTION
**Pull request by achaparro**
Hi @natocesarrego,

For the same reason than here:
natocesarrego#84

We need to change the schema version for some upgrade processes in master.

Please, let me know if you have any question regarding it.

Thanks.
@JosemariaMunoz

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by natocesarrego** [comment]
Hi @achaparro,

According to your first comment on natocesarrego#84, I've understood the pattern 1.0.* should be kept on the upgrade processes that could be backported to 7.0.x, right? So, why this pull isn't following this pattern? The answer is because the modified class can't be backported?

Regards.

**Comment by achaparro** [comment]
Hi @natocesarrego,

> I've understood the pattern 1.0.* should be kept on the upgrade processes that could be backported to 7.0.x, right? 

Yeah, that's the rule.

> So, why this pull isn't following this pattern? The answer is because the modified class can't be backported?

The answer is because those upgrade processes are not fullfilling the previous rule. The classes 
com.liferay.calendar.web.internal.upgrade.v1_0_2.UpgradePortletId()
com.liferay.calendar.web.internal.upgrade.v1_0_3.UpgradeEventsDisplayPortletId()

Belong to an story or technical task so can't be backported, however they have been defined as micro schema version change 1.0.*

Please, let me knopw if you have any question regarding it.

Thanks

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/424. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
