### PR TITLE
LPS-118606 Create const to max size label

### PR DESCRIPTION
**Pull request by alinedoleron**
Related issue: https://issues.liferay.com/browse/LPS-118606

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@alinedoleron, please check conflicts and SF issue and re-send.

Thanks.

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
