### PR TITLE
LPS-114468 Make sure that the focused field has not changed before the evaluation is finished

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/596. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/e98d58f3f0e3~1...e98d58f3f0e3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
