### PR TITLE
LPS-104943 Avoid possible NPE

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
https://github.com/natocesarrego/liferay-portal/pull/210

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @carolmariaabb,

The failures reported by CI seems to be related to this fix, can you please double check if the failures are indeed related? The failed tests can be found in https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/355880/.

Thanks.

**Pull request closed without merging**
