### PR TITLE
LPS-101943 Fix placeholder bug in ie11 for textarea tag

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84684. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/bb075cad6c3e~1...bb075cad6c3e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
