### PR TITLE
LPS-100290 baseline

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
@marcosapmf, can you please check this last problem raised by CI?

**Comment by marcosapmf** [comment]
@natocesarrego it was missing to run gw baseline. I just sent you a new PR [here](https://github.com/natocesarrego/liferay-portal/pull/426) :)

**Comment by natocesarrego** [comment]
Thanks, @marcosapmf! I'm closing this pull. 😉

**Pull request closed without merging**
