### PR TITLE
LPS-198028 Fix the upgrade process to migrate structure's old references

### PR DESCRIPTION
**Pull request by alberttgomes**
[LPS-198028](https://liferay.atlassian.net/browse/LPS-198028)

### CODE REVIEW

**Comment by alberttgomes** [comment]
ci:test:sf

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Good job, @alberttgomes!

Can you please just replace the word `references` with `versions` in the commit message?

Since this is the term used in the code :slightly_smiling_face:

**Comment by alberttgomes** [comment]
> Good job, @alberttgomes!
> 
> Can you please just replace the word `references` with `versions` in the commit message?
> 
> Since this is the term used in the code 🙂

Will do

**Comment by natocesarrego** [comment]
Manually forwarded to BPM Team: https://github.com/liferay-forms/liferay-portal/pull/2344

**Pull request closed without merging**
