### PR TITLE
LPS-118120 using method that also filter by status

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@linolaoj, can you please check if the reported semantic version issue is related to this pull?

Thank you in advance.

**Comment by linolaoj** [comment]
@natocesarrego, the error is not happening on my local branch, I'm going to run the tests again. I'll investigate further if it is still on the next test result.

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@linolaoj, I'll close this pull once CI reported the same semantic versioning problem.

Thanks.

**Comment by linolaoj** [comment]
resent at https://github.com/natocesarrego/liferay-portal/pull/728

**Pull request closed without merging**
