### PR TITLE
[TECHNICAL SUPPORT] LPS-112106 SF

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-112106

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:app-builder

**Comment by rodrigopaulino** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Hi @rodrigopaulino,

The `Liferay.Session` object instantiated [here](https://github.com/liferay/liferay-portal/blob/f4d12b797e93f46e4f9af1e711ec3a3a88ebab13/portal-web/docroot/html/common/themes/session_timeout.jspf#L30) is actually an Alloy component created [here](https://github.com/liferay/liferay-portal/blob/f4d12b797e93f46e4f9af1e711ec3a3a88ebab13/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/session.js#L38), hence can you please investigate if we can listen to any event from this component or get some info from it to make sure that the `Liferay.Session` was initialized?

If we succeed, then we won't need to add a timer. However, if there are no way to check if the mentioned object was initialized through this suggestion, please re-send you current fix.

Thanks.

**Pull request closed without merging**
