### PR TITLE
LPS-118608 Use method to remove empty values from an array

### PR DESCRIPTION
**Pull request by alinedoleron**
Issue: https://issues.liferay.com/browse/LPS-118608

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
