### PR TITLE
LPS-123363 Add unit test

### PR DESCRIPTION
**Pull request by carolmariaabb**
Hi @natocesarrego, I am sending you this PR for a previous review, however, I believe it would be better to send it to Master after we have completed the implementation of the field.

Related Issue: https://issues.liferay.com/browse/LPS-123363

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@carolmariaabb, this pull looks great! 😄 Do you want me to hold it here or can I close it for now?

**Comment by carolmariaabb** [comment]
> @carolmariaabb, this pull looks great! 😄 Do you want me to hold it here or can I close it for now?



> @carolmariaabb, this pull looks great! 😄 Do you want me to hold it here or can I close it for now?

You can close for now @natocesarrego. Thanks 😊

**Pull request closed without merging**
