### PR TITLE
[TS] LPS-105571

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-105571

Hi Renato,
Please let me know if I should send this review to someone else.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @ChrisKian,

I can review your pull, no problem. 🙂

In regards to the steps described in [LPS-105571](https://issues.liferay.com/browse/LPS-105571), I'm not sure if I realized what is the exact issue, can you please clarify to me? I recorded a video with the steps to reproduce and everything looks correct to me. Please check it below:

LPS-105571

Thanks.

**Comment by ChrisKian** [comment]
Hi @natocesarrego,
Thanks for showing me your reproduction steps,  However, you are missing the final step:
1. Once saved as "Test ES", edit the content again by changing the Spanish translation to "Test", or whatever the site-default language's content is
2. Click Publish
3. Re-edit the content, verify the Spanish translation's content is not "Test"

Let me know if that reproduces the issue for you, otherwise I can create a screen recording.  Thanks!

**Comment by natocesarrego** [comment]
Thanks a lot for your clarification, @ChrisKian, after read it, I was able to reproduce the issue. 😃 I've just added one more step to the LPS-105571 description to avoid that other developer/QA have the same difficulty that I had. 😉

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81991. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
