### PR TITLE
LPS-109959 Update settings context of focused field on handleFocusedFieldEvaluationEnded event

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
Hi @natocesarrego, I checked all the failures from [this PR](https://github.com/carolmariaabb/liferay-portal/pull/24) to confirm that they aren't related to the changes.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86423. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/e5af882454ee~1...e5af882454ee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
