### PR TITLE
LPS-135037 Verify if the portletNamespace has the DDM_FORM_PORTLET_NAMESPACE

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-135037

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
Good job! :smile:

**Comment by natocesarrego** [comment]
@mateussgn, can you please backport this fix to 7.3.x when it get merged on master?

Thanks!

**Comment by mateussgn** [comment]
> @mateussgn, can you please backport this fix to 7.3.x when it get merged on master?
> 
> Thanks!

Of course @natocesarrego!

**Pull request closed without merging**
