### PR TITLE
LPS-119917 SF

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related issue: https://issues.liferay.com/browse/LPS-119917

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/marcosapmf/liferay-portal/pull/90. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/59a2c10a943b~1...59a2c10a943b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
@marcosapmf, please fix reported failures on top of https://github.com/marcosapmf/liferay-portal/pull/90 and forward your pull to Brian.

Thanks.

**Pull request closed without merging**
