### PR TITLE
LPS-115096 Add property to set fieldName field disabled

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
Hi @cvanut and @natocesarrego,
should I remove those poshi test which has failed, or they need to me modified to the new scenario?

**Comment by cvanut** [comment]
Hi @alinedoleron and @natocesarrego , as we discussed, I guess the best idea is to disable the tests and I analyze/fix them individually for what is necessary.
This, you can disable the following tests:

- Forms#AddElementSetsWithTranslation
- Forms#EditAllFormFieldNames
- Forms#ViewDefaultFieldNamesWithPunctuationCharacters
- Forms#CreateReadUpdateDeleteImageField

The following test **should not be disable**, because it's failing due to LPS-112062
- Forms#EditAllFormFieldsTypesUsedBySystemSettings

Aline, you can see how to disable (ignore) tests in [this document](https://docs.google.com/document/d/1Jwx5pBzHKWFRRAcavUaS9vpfg6ZoPCkWM2qrDSuhz10/edit#heading=h.nadfd6rhmb3u). In summary, you have to add:
` @ignore = "true" to the top of your functional test`

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
ci:test:app-builder

**Comment by natocesarrego** [comment]
ci:test:app-builder

**Comment by natocesarrego** [comment]
Hey @alinedoleron,

Just to let you know, this pull doesn't introduce any issue to App Builder. 🙂 

Thanks.

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
New pr: https://github.com/natocesarrego/liferay-portal/pull/632

**Comment by cvanut** [comment]
Hi @alinedoleron , just to make sure, so I can create tickets to fix the tests.
Did you disable the following tests in this PR?

- Forms#AddElementSetsWithTranslation
- Forms#EditAllFormFieldNames
- Forms#ViewDefaultFieldNamesWithPunctuationCharacters
- Forms#CreateReadUpdateDeleteImageField

thank you!

**Comment by alinedoleron** [comment]
Hi @cvanut, I've sent this new pr https://github.com/natocesarrego/liferay-portal/pull/632/files which also disable those tests.

**Pull request closed without merging**
