### PR TITLE
[TECHNICAL SUPPORT] LPS-118627 Predefined value viewed appropriately from an element set

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-118627

/cc @rijema

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
@natocesarrego, you can check the CI results [here](https://github.com/rodrigopaulino/liferay-portal/pull/33)

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Thanks for sharing it, @rodrigopaulino. 😄 However, I still need to re-run the tests due to the command `ci:forward`, otherwise the pull can't be forwarded to Brian.

Thanks.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
