### PR TITLE
LPS-115095 Only render initial empty option when needed to prevent unnecessary re-render.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
ci:help

**Comment by natocesarrego** [comment]
ci:test:app-builder

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
