### PR TITLE
LPS-106398 Validate form field type grid in case of empty option

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @carolmariaabb,

Your fix makes a lot of sense to me, although this same validation is already implemented [here](https://github.com/liferay/liferay-portal/blob/4f583afa37cd9d4f35cc2115ccb793c923342f3d/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/java/com/liferay/dynamic/data/mapping/form/field/type/internal/grid/GridDDMFormFieldValueValidator.java#L45-L75), please check it. This validation is invoked [here](https://github.com/liferay/liferay-portal/blob/4f583afa37cd9d4f35cc2115ccb793c923342f3d/modules/apps/dynamic-data-mapping/dynamic-data-mapping-validator/src/main/java/com/liferay/dynamic/data/mapping/validator/internal/DDMFormValuesValidatorImpl.java#L195-L213) during the validation of all `DDMFormValues`, therefore I believe we can work to reuse this existent validation. Can you please try to do it?

Thanks.

**Comment by carolmariaabb** [comment]
> Hi @carolmariaabb,
> 
> Your fix makes a lot of sense to me, although this same validation is already implemented [here](https://github.com/liferay/liferay-portal/blob/4f583afa37cd9d4f35cc2115ccb793c923342f3d/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/java/com/liferay/dynamic/data/mapping/form/field/type/internal/grid/GridDDMFormFieldValueValidator.java#L45-L75), please check it. This validation is invoked [here](https://github.com/liferay/liferay-portal/blob/4f583afa37cd9d4f35cc2115ccb793c923342f3d/modules/apps/dynamic-data-mapping/dynamic-data-mapping-validator/src/main/java/com/liferay/dynamic/data/mapping/validator/internal/DDMFormValuesValidatorImpl.java#L195-L213) during the validation of all `DDMFormValues`, therefore I believe we can work to reuse this existent validation. Can you please try to do it?
> 
> Thanks.

Hi @natocesarrego,

I will ! Thanks.

**Pull request closed without merging**
