### PR TITLE
LPS-102616 only check for non proxy if proxy was set

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @brunofarache

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79195. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/333c8b6db559~2...333c8b6db559) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
