### PR TITLE
LPS-118759 check template uses react before writing provide capability

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-118759

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
This last pull is ok to me, @marcosapmf. 🙂 Please check the reported failures, fix them and forward your pull to Lawrence.

Thanks.

**Comment by marcosapmf** [comment]
> This last pull is ok to me, @marcosapmf. 🙂 Please check the reported failures, fix them and forward your pull to Lawrence.
> 
> Thanks.

Ok @natocesarrego, I'm going to do that right now. Thanks to you

**Pull request closed without merging**
