### PR TITLE
LPS-110394 Add test for column resize handler

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
Your pull request test has been aborted. We are sorry of the inconvenience but QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/399. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/400. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
