### PR TITLE
LPS-84622 add test for hyphens case

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @natocesarrego   could you take a look at the new test I added?  I just copied the previous test and just changed the project name to include a hypen `foo-bar`.  But the rest of the test asserts are the same so of course it fails. :)  Heres it the test I ran

`gw test --tests "*testBuildTemplateFormField71WithHyphen"`

Could you try that and update the test in ProjectTemplatesTest.testBuildTemplateFormField71WithHyphen"

**Comment by natocesarrego** [comment]
Hi @gamerson,

I tried to create the unit test to check the scenario with hyphen, but I faced an issue. Did you have the chance to check this [comment](https://github.com/gamerson/liferay-portal/pull/192#issuecomment-417801889)?

Thanks in advance.

**Comment by gamerson** [comment]
hey @natocesarrego   If the method _buildTemplateWithGradle() is creating a bad packagename for your case, we just need to switch to using a different method

```
		File gradleProjectDir = _buildTemplateWithGradle(
			destinationDir, "form-field", "foo-bar", "--package-name",
			"com.foo.bar", "--liferayVersion", "7.1"); 
```

**Comment by natocesarrego** [comment]
Nice to know, @gamerson! I'll try that!

Thanks.

**Pull request closed without merging**
