### PR TITLE
LPS-73741 remove unapproved calendar bookings from list

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Excellent job, @linolaoj! 😄 

By the way, the broken Calendar test reported by CI is not related with your pull, so I'll just talk to Adam about this pull and decide if I'll forward it to him or to BChan.

Thanks.

**Comment by natocesarrego** [comment]
Hi @linolaoj,

I've just talked to Adam and he's fine about your fix. By the way, do you have bandwidth to implement an unit or an integration test? This would be nice to make sure it won't break other any other part of Calendar and also anticipate bugs.

Thanks.

**Comment by linolaoj** [comment]
Hi @natocesarrego, 
glad that fix is ok! 
I'll send you a new pull including the tests.
Thanks!

**Comment by natocesarrego** [comment]
Thanks, @linolaoj.

**Pull request closed without merging**
