### PR TITLE
LPS-69157

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:stop

**Comment by natocesarrego** [comment]
Hey @mbowerman, can you please add a test to this PR?

Thanks.

**Comment by mbowerman** [comment]
Hi @natocesarrego,

I've added the test and resent it to you at https://github.com/natocesarrego/liferay-portal/pull/51.

**Comment by natocesarrego** [comment]
Ok, @mbowerman. So, I'll close this PR.

Thanks.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/liferay-forms/liferay-portal/pull/55. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/e5b2156f7558~2...e5b2156f7558) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
