### PR TITLE
LPS-107363 Fix import staged model for data provider instance

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
https://github.com/carolmariaabb/liferay-portal/pull/14

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
@leoadb any ideas about how to fix this bug without a major breaking change? cc @carolmariaabb @natocesarrego

**Comment by leoadb** [comment]
@brunofarache I'm afraid there is no way to avoid the breaking change because a interface from the API was updated and that interface is generated so we can't add a default implementation for that. :(

**Comment by brunofarache** [comment]
@leoadb that's what I thought. Seems to be a missing feature and not really a bug fix.

**Comment by natocesarrego** [comment]
I think we need to discuss about that, @brunofarache. 😉

**Comment by brunofarache** [comment]
@natocesarrego with Leo’s confirmation, it’s more clear to me we can’t fix that without a breaking change. We just need to check with @brianchandotcom if that’s acceptable.

**Comment by natocesarrego** [comment]
Hey @carolmariaabb,

Just to let you know, I contacted Brian Chan to decide how to proceed with your proposed solution and I'm waiting his answer. Once he answer me, I talk to you.

Thanks.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/477. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/3c336d31a6b9~2...3c336d31a6b9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
