### PR TITLE
LPS-112711 Include lastPublishDate column into DDMDataProviderInstance table when upgrading

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
ci:forward

**Comment by achaparro** [comment]
Hey @carolmariaabb, @natocesarrego,

I had the same issue than in here:
https://issues.liferay.com/browse/LPS-112711

And I realized about this pull. Checking the pull I noticed this change:
https://github.com/natocesarrego/liferay-portal/pull/539/files#diff-5790066a535f8382e11039da7bb322feR43

I don't know if you need to change that file for one reason but we should never modify table definitions belonging to previous upgrades such **v3_0_0/util/DDMDataProviderInstanceTable.java**
Those files show the definition of that table at a specific moment in time, for the schema version 3.0.0 in this case. If we add the lastPublishDate which belongs to the version 3.5.0, we can create the field (depending on the database) before requiring it and that causes issues.

Please, can you review this?

Thanks.

**Comment by natocesarrego** [comment]
Thanks a lot for your valuable review, @achaparro. 😄

@carolmariaabb, do you think you already have all information that you need to update the code according to @achaparro's review?

Thanks.

**Comment by carolmariaabb** [comment]
> Thanks a lot for your valuable review, @achaparro. 😄
> 
> @carolmariaabb, do you think you already have all information that you need to update the code according to @achaparro's review?
> 
> Thanks.

Hi @natocesarrego,

Yes, I believe I do. In fact, it was not necessary to modify the code **v3_0_0 /util/ DDMDataProviderInstanceTable.java**. 
I already made the modification and also fixed the semantic versioning problem. I'm waiting for the `ci:test:relevant` result.

Thanks @achaparro for your help.

**Comment by achaparro** [comment]
You're welcome! thanks @carolmariaabb and @natocesarrego for working on it :-)

**Pull request closed without merging**
