### PR TITLE
[TS] LPS-116665 | Add information for screen readers when a field is required

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-116665 Add information for screen readers when a field is required
Adding missing commit https://github.com/carolmariaabb/liferay-portal/pull/163/commits/de3840d7798fa5e1a0cb42a2329d7e06da0c72d8 in the last pull merged to master https://github.com/natocesarrego/liferay-portal/pull/779 
Regards.

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@carolmariaabb, can you please confirm if the lack of the commit mentioned by @georgel-pop-lr was intended? This commit was removed since https://github.com/natocesarrego/liferay-portal/pull/753.

Thanks in advance.

**Comment by carolmariaabb** [comment]
> @carolmariaabb, can you please confirm if the lack of the commit mentioned by @georgel-pop-lr was intended? This commit was removed since #753.
> 
> Thanks in advance.

Hi @natocesarrego,

I actually removed it from my branch while I was doing some tests and didn't realize that I sent it without it. Sorry about that.

I removed it because all tests with required fields were failing and I was not able to resolve all cases, including `LocalFile.SharedAppBuilder#ReuseExistingFormViewFields` (as you can see in [725#issuecomment-671864859](https://github.com/natocesarrego/liferay-portal/pull/725#issuecomment-671864859)).

Since the tests passed here [#753](https://github.com/natocesarrego/liferay-portal/pull/753) I ended up forgetting to discuss this with the team.

**Comment by natocesarrego** [comment]
No problem, @carolmariaabb. 🙂 

Therefore, we need to add the commit mentioned by @georgel-pop-lr and this [commit](https://github.com/natocesarrego/liferay-portal/pull/725/commits/00544d53ef05034dfd306fc9d79b0648895735cf) to deliver the remaining part of the whole solution?

Thanks.

**Comment by carolmariaabb** [comment]
> No problem, @carolmariaabb. 🙂
> 
> Therefore, we need to add the commit mentioned by @georgel-pop-lr and this [commit](https://github.com/natocesarrego/liferay-portal/pull/725/commits/00544d53ef05034dfd306fc9d79b0648895735cf) to deliver the remaining part of the whole solution?
> 
> Thanks.

That's right, @natocesarrego 

However, this commit will only fix the Forms test cases. I was not able to identify other tests that needed this fix.

Thanks!

**Comment by natocesarrego** [comment]
@carolmariaabb, are you concerned about test failures on App Builder due to the commit of this pull, is this true?

@georgel-pop-lr, can you please add this [commit](https://github.com/natocesarrego/liferay-portal/pull/725/commits/00544d53ef05034dfd306fc9d79b0648895735cf) to this pull for we run the appropriated tests?

Thanks guys!

**Comment by carolmariaabb** [comment]
> @carolmariaabb, are you concerned about test failures on App Builder due to the commit of this pull, is this true?
> 
> @georgel-pop-lr, can you please add this [commit](https://github.com/natocesarrego/liferay-portal/pull/725/commits/00544d53ef05034dfd306fc9d79b0648895735cf) to this pull for we run the appropriated tests?
> 
> Thanks guys!

Exactly, Renato.

**Comment by georgel-pop-lr** [comment]
> @carolmariaabb, are you concerned about test failures on App Builder due to the commit of this pull, is this true?
> 
> @georgel-pop-lr, can you please add this [commit](https://github.com/natocesarrego/liferay-portal/pull/725/commits/00544d53ef05034dfd306fc9d79b0648895735cf) to this pull for we run the appropriated tests?
> 
> Thanks guys!

Hi @natocesarrego,
I tried to get the commit but the branch is not longer accessible so is not possible to cherry-pick it, not sure if @carolmariaabb still have this branch on his local.
Regards.

**Comment by carolmariaabb** [comment]
> > @carolmariaabb, are you concerned about test failures on App Builder due to the commit of this pull, is this true?
> > @georgel-pop-lr, can you please add this [commit](https://github.com/natocesarrego/liferay-portal/pull/725/commits/00544d53ef05034dfd306fc9d79b0648895735cf) to this pull for we run the appropriated tests?
> > Thanks guys!
> 
> Hi @natocesarrego,
> I tried to get the commit but the branch is not longer accessible so is not possible to cherry-pick it, not sure if @carolmariaabb still have this branch on his local.
> Regards.

Hi @georgel-pop-lr ,

I just restored the `carolmariaabb:pr-181` branch.  

Could you try again? Thanks!

**Comment by georgel-pop-lr** [comment]
> > > @carolmariaabb, are you concerned about test failures on App Builder due to the commit of this pull, is this true?
> > > @georgel-pop-lr, can you please add this [commit](https://github.com/natocesarrego/liferay-portal/pull/725/commits/00544d53ef05034dfd306fc9d79b0648895735cf) to this pull for we run the appropriated tests?
> > > Thanks guys!
> > 
> > 
> > Hi @natocesarrego,
> > I tried to get the commit but the branch is not longer accessible so is not possible to cherry-pick it, not sure if @carolmariaabb still have this branch on his local.
> > Regards.
> 
> Hi @georgel-pop-lr ,
> 
> I just restored the `carolmariaabb:pr-181` branch.
> 
> Could you try again? Thanks!

Hi @carolmariaabb,

Still, not able to, if you go to the commit itself says "This commit does not belong to any branch on this repository." so is impossible to cherry-pick if there is no branch.

Regards.

**Comment by carolmariaabb** [comment]
> > > > @carolmariaabb, are you concerned about test failures on App Builder due to the commit of this pull, is this true?
> > > > @georgel-pop-lr, can you please add this [commit](https://github.com/natocesarrego/liferay-portal/pull/725/commits/00544d53ef05034dfd306fc9d79b0648895735cf) to this pull for we run the appropriated tests?
> > > > Thanks guys!
> > > 
> > > 
> > > Hi @natocesarrego,
> > > I tried to get the commit but the branch is not longer accessible so is not possible to cherry-pick it, not sure if @carolmariaabb still have this branch on his local.
> > > Regards.
> > 
> > 
> > Hi @georgel-pop-lr ,
> > I just restored the `carolmariaabb:pr-181` branch.
> > Could you try again? Thanks!
> 
> Hi @carolmariaabb,
> 
> Still, not able to, if you go to the commit itself says "This commit does not belong to any branch on this repository." so is impossible to cherry-pick if there is no branch.
> 
> Regards.

Hi @georgel-pop-lr,

I just sent you a PR [georgel-pop-lr#6](https://github.com/georgel-pop-lr/liferay-portal/pull/6) whit this commit.

Could you check if everything is all right and forward it to @natocesarrego ? 

Thanks!

**Comment by georgel-pop-lr** [comment]
> > > > > @carolmariaabb, are you concerned about test failures on App Builder due to the commit of this pull, is this true?
> > > > > @georgel-pop-lr, can you please add this [commit](https://github.com/natocesarrego/liferay-portal/pull/725/commits/00544d53ef05034dfd306fc9d79b0648895735cf) to this pull for we run the appropriated tests?
> > > > > Thanks guys!
> > > > 
> > > > 
> > > > Hi @natocesarrego,
> > > > I tried to get the commit but the branch is not longer accessible so is not possible to cherry-pick it, not sure if @carolmariaabb still have this branch on his local.
> > > > Regards.
> > > 
> > > 
> > > Hi @georgel-pop-lr ,
> > > I just restored the `carolmariaabb:pr-181` branch.
> > > Could you try again? Thanks!
> > 
> > 
> > Hi @carolmariaabb,
> > Still, not able to, if you go to the commit itself says "This commit does not belong to any branch on this repository." so is impossible to cherry-pick if there is no branch.
> > Regards.
> 
> Hi @georgel-pop-lr,
> 
> I just sent you a PR [georgel-pop-lr#6](https://github.com/georgel-pop-lr/liferay-portal/pull/6) whit this commit.
> 
> Could you check if everything is all right and forward it to @natocesarrego ?
> 
> Thanks!

Hi @carolmariaabb,

I was able to do it now, the commit is pushed. 

Regards.

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:app-builder

**Comment by liferay-forms** [comment]
Hey @georgel-pop-lr, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@carolmariaabb, can you please help me analyze the CI results?

Thanks.

**Comment by carolmariaabb** [comment]
Sure, @natocesarrego !

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Hi @natocesarrego, I fixed the tests and resent here [liferay-forms#6](https://github.com/liferay-forms/liferay-portal/pull/6).

**Comment by natocesarrego** [comment]
Ok, I'm closing this pull and I'll check the [liferay-forms#6](https://github.com/liferay-forms/liferay-portal/pull/6).

Thanks.

**Pull request closed without merging**
