### PR TITLE
LPS-125782

### PR DESCRIPTION
**Pull request by carolmariaabb**
Hi,
As requested [here](https://github.com/brianchandotcom/liferay-portal/pull/97740#issuecomment-760397435), I tried to use `SessionMessages.contains(actionRequest)` instead of `httpServletRequest`, but that doesn’t seem to be enough to fix the bug. 
So, I tried [this](https://github.com/natocesarrego/liferay-portal/commit/0231f479bae6787fa771c6831435b2d4d63e0bfa#diff-9feb9dd3d3c66c8467871b879446727dc60bd089163c13ac9f2fade65d729a78R65) other way and it worked as expected. 
I think it is a good alternative, since the upload portlet request is used instead of the HTTP servlet request, what do you think? 

**Related Issue**: https://issues.liferay.com/browse/LPS-125782

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
@carolmariaabb, I checked Brian's comment and he advises you to use the `actionRequest`, but only if you can, if not you can keep using the `httpServletRequest`. Can you please clarify to me and consequently to Brian why use the `actionRequest` doesn't work?

I understand that your previous pull with a good explanation should be enough for Brian merge it. 😉

**Comment by carolmariaabb** [comment]
> @carolmariaabb, I checked Brian's comment and he advises you to use the `actionRequest`, but only if you can, if not you can keep using the `httpServletRequest`. Can you please clarify to me and consequently to Brian why use the `actionRequest` doesn't work?
> 
> I understand that your previous pull with a good explanation should be enough for Brian merge it. 😉

Hi @natocesarrego,

From what I understood, using `actionRequest` doesn't work because the `KEY_SUFFIX_HIDE_DEFAULT_SUCCESS_MESSAGE` key is added only in the `uploadPortletRequest` (see [DDMUserPersonalFolderUploadResponseHandler.java#L56](https://github.com/liferay/liferay-portal/blob/9563dec9e9b8cff47d0863a94585ed6be2566657/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/upload/DDMUserPersonalFolderUploadResponseHandler.java#L56) and [ItemSelectorUploadResponseHandlerImpl.java#L96](https://github.com/liferay/liferay-portal/blob/9563dec9e9b8cff47d0863a94585ed6be2566657/modules/apps/item-selector/item-selector-web/src/main/java/com/liferay/item/selector/web/internal/upload/ItemSelectorUploadResponseHandlerImpl.java#L96)), which is different from the `actionRequest`. 

Therefore, the value returned by `SessionMessages.contains(actionRequest, portletId + SessionMessages.KEY_SUFFIX_HIDE_DEFAULT_SUCCESS_MESSAGE)` is **false**.

That's why I changed from `httpServletRequest` to `uploadPortletRequest`.

**Comment by natocesarrego** [comment]
top

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
