### PR TITLE
LPS-114619 Fix Forms.testcase Poshi tests

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-115095
https://issues.liferay.com/browse/LPS-117465
https://issues.liferay.com/browse/LPS-117573

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Amazing job, @carolmariaabb and @brunofariasdeo! 😄 👏 

Thank you very much for all your energy dedicated to this task. 😉

**Pull request closed without merging**
