### PR TITLE
LPS-70434

### PR DESCRIPTION
**Pull request by jcampoy**
Hi Renato, please, try to take a look as soon as possible, this is a simple change/fix. 

Rebased to current master and tests work in my user, see: https://github.com/jcampoy/liferay-portal/pull/35#issuecomment-278320100

Best regards,
Jose

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @jcampoy,

This my next task, ok? I'll start to work on this issue soon.

Regards.

**Comment by jcampoy** [comment]
ok, thank you, I think is a simple/minimal fix and it works, let me know if you have any question.

br.
jose

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @jcampoy,

Can you please double check if the issue is fixed with your modification? I've executed the steps to reproduce the issue with different users (admin and more than one regular user) and the bug still happens. 😞 

Also, can you please add a test for it?

Thanks.

**Comment by jcampoy** [comment]
Hey @natocesarrego  

I am going to test again but I did several tests. 

Regarding tests of Site Templates with User Pages and Calendar Portlet, I can not do that for a time reason, we have several opened tickets in Support Spain and I do not have so much time, you can add it if you want.
I let you know about the reproduction.

Best regards.

**Pull request closed without merging**
