### PR TITLE
LPS-114936 limiting number of threads for hystix command

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @linolaoj,

How did you realize that not setting a static thread pool was the issue? Can you please give me more details about your investigation? I just want to understand a little more your proposed fix. 🙂 

Thanks.

**Comment by linolaoj** [comment]
Hi @natocesarrego , thank you for reviewing this. 
While I was debugging I noticed that 10 threads were being created for the Hystrix command. Usually, only one thread would actually execute the command, but if I stopped one or two threads with a breakpoint sometimes they would lose coordination and the command would be executed multiple times. The idea of the fix is to have only one separated thread to execute the Hystrix command.
Please let me know if more details are needed.
Thanks!

**Comment by natocesarrego** [comment]
One last question, how Forms QA can reproduce this issue locally?

Thanks.

**Comment by linolaoj** [comment]
Hi @natocesarrego ,
because the issue is intermittent it might be needed to repeat the steps from LPS-114936 several times. Maybe simulate a high load on the server will make it easier to reproduce.
Thanks!

**Comment by natocesarrego** [comment]
Ok, @linolaoj. I'll forward your pull, but can you please add the information of your last comment as a note on the LPS-114936 description to help Forms QA?

Thanks in advance. 🙂

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
