### PR TITLE
LPS-117227 Create method to populate options

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
@alinedoleron, please remind to add the LPS link on the pull request description in the next pull. 😉

Thanks.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/721. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/9cdc2147fe19~2...9cdc2147fe19) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
