### PR TITLE
LPS-112951

### PR DESCRIPTION
**Pull request by linolaoj**
https://issues.liferay.com/browse/LPS-112951

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Great job, @linolaoj, fixing the Poshi test. 👏 😄 

However, I've detected that there are failures related to front-end unit tests too. I'll fix them once they just require the execution of the command `yarn test --updateSnapshot` on the module `dynamic-data-mapping-form-renderer` to update the snapshots demanded by the tests.

Thanks.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/545. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/da44fd6bf7bc~1...da44fd6bf7bc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
