### PR TITLE
LPS-109805 baseline

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-109805

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
@marcosapmf, can you please try to run on your machine the tests created by you under the module `dynamic-data-mapping-service`? Maybe the failures on this pull are indeed related to this fix, can you please double check?

**Comment by marcosapmf** [comment]
Sure, @natocesarrego  :)

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
