### PR TITLE
[TECHNICAL SUPPORT] LPS-105813 Make sure to remove the original items list after evaluating

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-105813

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Hey @brunobasto, Can you please help me with this review?

Thx

**Comment by rafaprax** [comment]
Hey @rodrigopaulino , 
I talked with Timão and we are ok with the changes in the first commit but the second one is introducing a dependency to an internal state of a Clay component. Can you please try another approach to fix this issue?
My suggestion is to you expose this Clay dropdown's limitation for the Clay team/Frontend Infra so that they provide guidance on how to fix it.

Thx

**Comment by rafaprax** [comment]
ci:close

**Comment by rodrigopaulino** [comment]
I was confused when you talked to me offline about two commits, @rafaprax. But now I can see what happened. Since @natocesarrego's master branch was not updated with the latest commits, this pull request appears to have two commits that are mine. This is not the case. Only the last one has the correct LPS number. The other one has been already merged to master but I understand the confusion since they are appearing together. Even with that, your review is still valid because the last commit that needs changing is the one that fixes this behavior. Just wanted to let you know that. I'll develop your suggestion as soon as I can. :D
Many thanks for your help on this review.

**Pull request closed without merging**
