### PR TITLE
[TS] LPS-86932 Apply button of filtering DDM repeatable fields in Asset Publisher is not responsive

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @natocesarrego ,

could you please check my changes?

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Hey @rolandpakai,

Your pull request looks good to me and I'll forward it to the Product Team.

Best.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/912. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
