### PR TITLE
LPS-88009 Preferring form groupId over themeDisplay

### PR DESCRIPTION
**Pull request by balazssk**
Hi @natocesarrego 

Can you please review my change for this issue:
https://issues.liferay.com/browse/LPS-88009

Thanks and Best Regards,

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @natocesarrego ,
If I'm correct, getScopeGroupIdOrLiveGroupId would only return the live groupId, if it exists.
The problem here is that neither the JS themeDisplay, nor the backend ThemeDisplay class handles if the current portlet is staged, or not.
So if we used getScopeGroupIdOrLiveGroupId on a staged portlet on the staged site, it would link the live site's pages to the stage site's content.

**Comment by natocesarrego** [comment]
Hi @balazssk,

Your understanding is correct about the `themeDisplay.getScopeGroupIdOrLiveGroupId()`. 🙂 Additionally, when this method is invoked on both sites, live and staging, considering the issue's scenario, the result is the same, i.e., the live group is returned. Please see more details on the [StagingImpl.getLiveGroup(Group group)](https://github.com/liferay/liferay-portal/blob/9bea383e2502b33b182ef11c388e99d34289f174/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/staging/StagingImpl.java#L1710-L1721) method, which is invoked by `themeDisplay.getScopeGroupIdOrLiveGroupId()`.

After some local tests, I realized that your solution and the solution using the `themeDisplay.getScopeGroupIdOrLiveGroupId()` fix the issue, but, on the other hand, introduce a behavior which I understand that isn't expected. Consider an environment with your fix, then execute the steps to reproduce of LPS-88009 and you'll realize that, on the staging site, the Link-to-page field will have a URL targeting the page 2 of the live site.

Can you please check this scenario with your fix?

Thanks in advance.

**Comment by balazssk** [comment]
Hi @natocesarrego ,
After some testing here are my findings:
Web Content Staged | Staged / Live | Expected groupId | getScopeGroupIdOrLiveGroupId | groupIdNode
-----------------------|----------------|---------------------|-------------------------------------|----------------
yes | staged | staged group | live group | staged group
yes | live | n/a | n/a | n/a
no | staged | live | live | live
no | live | live | live | live
(hope the table renders correctly)

According to my findings, the described scenario can be fixed with both solutions, but in case WC is staged the staging WC can only link to live pages.

> Consider an environment with your fix, then execute the steps to reproduce of LPS-88009 and you'll realize that, on the staging site, the Link-to-page field will have a URL targeting the page 2 of the live site.

In my understanding if WC isn't staged, it can't link to staged pages as those links would be present on the live site instantly.

**Comment by natocesarrego** [comment]
Hi @balazssk,

Firstly, thanks for your local tests. 🙂 

In regards to your last statement:

> In my understanding if WC isn't staged, it can't link to staged pages as those links would be present on the live site instantly.

I think that would be important involve the Staging SME, for we make sure what is the expected behavior for this specific use case before we move on with any of the fixes. Does it make sense to you? Do you mind to create a PTR ticket for we add the Staging SME to this discussion?

Thanks in advance.

**Comment by moltam89** [comment]
Hi @natocesarrego ,

thanks for asking for the Staging team's opinion!

Actually we discussed this with the Staging Product Team in person and we agreed that we shouldn't be able to link pages from the Staging group when Staging is not enabled for Web Contents.

Thanks,
Tamás

**Comment by natocesarrego** [comment]
Hi @moltam89,

Thanks a lot for your contribution!

Hey @balazssk,

Thanks for your patience along this review process. 🙂 Now, I feel comfortable for we move on.

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Pull request closed without merging**
