### PR TITLE
LPS-125528 buildRest

### PR DESCRIPTION
**Pull request by marcosapmf**
Related Issue: https://issues.liferay.com/browse/LPS-125528

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @marcosapmf, your pull looks good to me, can you please forward it to Javier?

Thanks.

**Comment by marcosapmf** [comment]
Hi @natocesarrego, sure :)
Thanks very much!

**Comment by marcosapmf** [comment]
forwarded https://github.com/nhpatt/liferay-portal/pull/322

**Pull request closed without merging**
