### PR TITLE
LPS-106501 avoiding race condition

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:close

**Comment by jeyvison** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/83098

**Pull request closed without merging**
