### PR TITLE
LPS-111780 Set portlet namespace

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
@carolmariaabb, I'll re-run the forms test suite, once I realized that there is a chance of a unique related failure, https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/373760/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_SubmitFormWithRequiredRepeatingTextField_/.

In addition, your fix looks good to me. 🙂

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
@carolmariaabb, the issue reported previously didn't occur again, therefore I'll forward your pull.

Thanks.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
