### PR TITLE
LRQA-55763 Creation of Upgrades Forms component

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Good to go. Waiting CI results.

**Comment by natocesarrego** [comment]
Hey @carolmariaabb,

From what I could check, the tests results are satisfactory, but, apparently, the front-end unit tests of all modules are being invoked, therefore I'll ask Cleyton about it before forward this pull.

Thanks.

**Comment by natocesarrego** [comment]
Hey @carolmariaabb,

Just to let you know, indeed all front-end unit tests will be triggered by Forms test suite and there is no way today to avoid it, therefore I'll forward this pull.

Thanks.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
@carolmariaabb, once this pull get merged by Brian, please send a backport to 7.2.x. There is no need to create a BPR ticket, just add a comment with the link to the pull request in LRQA-55763.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85997. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
