### PR TITLE
LPS-98153 avoiding evaluate one rule more than once

### PR DESCRIPTION
**Pull request by gabrielibson**

### CODE REVIEW

**Comment by gabrielibson** [comment]
Related issue: https://issues.liferay.com/browse/LPS-98153

**Comment by gabrielibson** [comment]
Hey @natocesarrego, please verify whether this is what you were looking for. If any adjustment is necessary, please let me know.

Thanks.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/469. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/87db49ad73e8~3...87db49ad73e8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielibson** [comment]
Hey @natocesarrego, thanks for reviewing. All of your changes made sense to me and in my view they kept the code cleaner and more readable. I'll try to apply these concepts to my future submissions.

**Pull request closed without merging**
