### PR TITLE
LPS-115931 setting focus to select field after chosing an option

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hey @linolaoj,

In regards to this proposed issue / fix I've the following concerns:
- The expected result described on LPS-115931 is different from the usual behavior of the HTML tag `<select>`. When an option of a `<select>` is chosen, the options are hidden and the focus is set to the `<select>`, therefore I believe we should keep the default behavior of `<select>` on the Select From List field.
- Why are you setting the focus to the `firstChild` element after an option is selected?

Thanks.

**Comment by linolaoj** [comment]
Hi @natocesarrego ,
Even though LPS-115931 expects the focus to go to the next field, I've implemented the behavior as you describe in your comment (focus coming back to select). The _firstChild_ is a div with class _select-field-trigger_ and that was the closest to the HTML _select_ tag that I found.
Please let me know if more details are needed or if I need to change anything.
Thanks!

**Comment by natocesarrego** [comment]
Thanks for your clarification, @linolaoj. 🙂

Can you please change the expected behavior on the LPS to be consistent with your implementation?

Thanks.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
