### PR TITLE
LPS-121343 Do not edit the rule when field is moved

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issue: https://issues.liferay.com/browse/LPS-121343

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@alinedoleron, do you think we can create a test to this issue?

Thanks.

**Comment by alinedoleron** [comment]
new PR: https://github.com/natocesarrego/liferay-portal/pull/860

**Comment by alinedoleron** [comment]
> @alinedoleron, do you think we can create a test to this issue?
> 
> Thanks.

@natocesarrego, I could not create a test for this. It seem to be a case of integration test. In the new pr I just enabled the tests related to deleteField, which were disabled previously, and I also removed one outdated test.

**Pull request closed without merging**
