### PR TITLE
LPS-110324 validating form instance availability before save a form instance record

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-110324

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/432. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/00b0082b5532~1...00b0082b5532) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/446. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/017bcdd6eee4~1...017bcdd6eee4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
