### PR TITLE
LPS-112951 Organizing heading levels on the forms

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @rijema and @linolaoj,

Can you guys please give me more details about this proposed fix?

Honestly, isn't very clear to me yet the real reasons behind it. I know you guys used the WAVE tool and it reported some problems, but it's important to analyze the outcomes from a tool like that and see if the outcomes are indeed issues or just recommendations.

Thanks in advance.

**Comment by linolaoj** [comment]
Hi @natocesarrego ,
the idea of this fix is to avoid a heading level to be skipped like a `<h1> `followed by a `<h4>`.
According to WCAG this should be avoided whenever possible (https://www.w3.org/WAI/tutorials/page-structure/headings/). And WCAG 2 seems to be more strict on it (https://www.w3.org/TR/2012/NOTE-WCAG20-TECHS-20120103/G141). 
The WAVE tool reported it as an alert, not as an error.
Please let me know if more details are needed, and if this should be fixed as a bug.
Thanks!

**Comment by natocesarrego** [comment]
Thanks for your clarification, @linolaoj. 🙂 Even though, I don't see this proposed fix making a change that will attend this rule, actually, I see it making a different change. Can you please talk to me in Slack or call me for we discuss about it?

Thanks.

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
I just talked to @linolaoj and we agreed the following regarding this pull:

1. We'll run the Forms test suite to make sure that no Poshi test will be broken by these markup changes.
2. I'll compile this fix locally to check Forms UI and, if necessary, I'll ask Forms Designer opinion to decide how to proceed.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
@linolaoj,

In regards to the markup changes, no problems in UI, actually, it became better. Nice job! 😄 

Let's wait CI outcomes now.

Thanks.

**Comment by natocesarrego** [comment]
ci:help

**Comment by natocesarrego** [comment]
ci:test:app-builder

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/533. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
