### PR TITLE
LPS-125359

### PR DESCRIPTION
**Pull request by DiegoDOC**
Related Issue: https://issues.liferay.com/browse/LPS-125359

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@DiegoDOC, I resent the pull due to a SF, please see the [new pull](https://github.com/natocesarrego/liferay-portal/pull/1057) and also the [new commit](https://github.com/natocesarrego/liferay-portal/pull/1057/commits/32d699bae3021027d1c918d255627c02a0872f5d).

Thanks.

**Pull request closed without merging**
