### PR TITLE
Lps 86235 data engine data form

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @natocesarrego 

There are several portlets that are non deployable but has property set to PreferencesUniquePerLayout=true(the default value), DDL and DDMDataProvider are two of them.

This commit explicitly set it to false.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @arthurchan35, can you please clarify why you're saying that DDL Portlet isn't deployable?

**Comment by arthurchan35** [comment]
Hi @natocesarrego ,

Maybe I was not using the most proper term, but what I meant was DDL is an admin level portlet, similar to BlogsAdmin or DLAdmin, which can be accessed from site control panel page, and one can not deploy these type of portlets to pages.

If you look at BlogsAdminPortlet or DLAdminPortlet, you can see they have properly setup this property:
com.liferay.portlet.preferences-unique-per-layout=false

**Comment by natocesarrego** [comment]
Thanks for your explanation, @arthurchan35. 🙂 Your fix makes sense to me.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
