### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @gabrielwas, can you please fix the source formatter issues and resend? Thanks

**Comment by gabrielwas** [comment]
Hi Renato! So, here's the point: I need to persist a new Form while running some base methods. Usually, we have some post methods (endpoints from the REST API) that we can use. But, in that case, this method is not available (it was not implemented by the team).

But, as a workaround, I can persist this entity calling DDM methods directly. But in that case, I still need to call these util methods (`CreatorUtil` and `StructureUtil` - headless-form-impl) from the tests module (headless-form-test) in order to convert between entity and DTO.

So, here are the alternatives we have to solve it:

1 -  I was wondering if there's a way to consume these util classes from the test bundle without exposing them. I couldn't find anything similar on Portal.
2 - Implement the postForm method (I think that's not a real option rs)
3 - Expose the util classes on the headless-form-api (the way I did in this PR)
4 - Copy and paste the code from the util classes

**Comment by gabrielwas** [comment]
ci:reopen

**Pull request closed without merging**
