### PR TITLE
LPS-86327 Localize Forms paragraph

### PR DESCRIPTION
**Pull request by hudakl**
Hi Renato,

I've managed to implement the upgrade process for LPS-86327.
Could you please review my changes?

Thank you,
Laci

### CODE REVIEW

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Good job, @hudakl! I'll run the regular tests and the upgrade tests against all databases to see if everything is ok.

Best.

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:upgrade

**Comment by natocesarrego** [comment]
Hey @hudakl,

Can you please check the reported failures?

Thanks in advance.

**Comment by hudakl** [comment]
Hi Renato,

I've adjusted the test to handle the LocalizedValue.

Regards,
Laci

**Comment by natocesarrego** [comment]
Thanks for the updates, @hudakl. I'll run the CI tests again. 😉

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:upgrade

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:upgrade

**Comment by natocesarrego** [comment]
Hey @hudakl,

Can you please check the source-format issues?

**Comment by natocesarrego** [comment]
ci:test:upgrade

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by hudakl** [comment]
ci:test:sf

**Comment by hudakl** [comment]
Hi Renato,

I updated the branch to handle the SF errors.
I also checked what went wrong in the upgrade tests, but I couldn't work out how to address those issue and how to prepare the testcases for the new LocalizedValue, as I have never encountered these kinds of tests before.
Could you please give me some guidence how those work?

Thanks,
Laci

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/133. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/4581e96ec26b~1...4581e96ec26b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
