### PR TITLE
LPS-70524 Wrong date format in Calendar day view

### PR DESCRIPTION
**Pull request by brandizzi**
Hey @IstvanD, indeed it was a long time withouth a pull request ;) @renatorego is taking care of the calendar, so I am forwarding your PR to him. Thank you!

### CODE REVIEW

**Comment by brandizzi** [comment]
Renato, some points to consider here:

- It is breaking POSHI tests. May it be changing the English format as well? This is an unexpected side effect. If so, we may need to manually format dates eventually.

- This seems like a problem with Alloy UI itself. It would be nice to have an AUI ticket with that.

**Comment by natocesarrego** [comment]
ci:stop

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/386. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
