### PR TITLE
[TS] LPS-118423

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @natocesarrego ,

Can you help review this PR for a language key change to DDM? 

**Notes from @javalosjr96:**
> The issue was that the language key that the fieldset uses to display its type had not been updated and had remained as Fields Group. All that was changed was the the language key and gw BuildLang was ran.

Hopefully you're the right reviewer for these changes.

If not, can you let us know who we can forward this to?
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @ericyanLr, this is an issue from App Builder, therefore I'll forward it to the proper reviewer, ok?

Thanks.

**Comment by natocesarrego** [comment]
Pull request forwarded to https://github.com/jeyvison/liferay-portal/pull/832. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kevenleone** [comment]
Hello everyone, hope you all okay :)

I think we have a misunderstood here, with the name "Field Group" and "FieldSet" and it's very comprehensive why, but, even with the same type they are different.

Field Group, or Section (have a lot of names 🤯) and FieldSet, they both have the type: "fieldset", but the difference between then are the `ddmStructureId`

If the Field contains in `customProperties: {ddmStructureId}` so, it's a fieldSet, if not it's a FieldGroup

The fields of FieldGroup can be modified and FieldSet not.

See the picture for better understanding 
Screen Shot 2020-08-13 at 16 32 50

That's why it's not necessary to rename "fieldset-field-type-label" , so I have dropped both commits and will send a PR with the fix.

Any questions, we can talk on Slack ☺️

**Comment by kevenleone** [comment]
PR resent to: #jeyvison/841

**Pull request closed without merging**
