### PR TITLE
LPS-80771 Create poshi test to test the case of changing a field type of a field which belongs to a rule

### PR DESCRIPTION
**Pull request by alinedoleron**
Related issue: https://issues.liferay.com/browse/LPS-80771
Blocked by: https://issues.liferay.com/browse/LPS-119818

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @alinedoleron, did you have a chance to analyse if we could create some tests for this pull?

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:stop

**Pull request closed without merging**
