### PR TITLE
LPS-107883 HTML repeatable fields do not have a "draggable" icon

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @natocesarrego ,

Please review my changes. Root cause analysis is on [LPS-107883](https://issues.liferay.com/browse/LPS-107883)

Thanks,

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hey @NemethNorbert,

I finished to review your pull and now I'm just waiting the output from CI to forward it. 😉 

Thanks for your patience.

**Comment by natocesarrego** [comment]
Hi @NemethNorbert,

A pull request merged yesterday broke Forms and all its functional tests, hence I won't be able to move on with this review until the tests get fixed. The good news is that the fix was already merged to master and soon the tests will be working again.

Thanks for your patience.

**Comment by NemethNorbert** [comment]
Hey @natocesarrego,

Can move the PR forward or the tests are still failing?

Thanks,

**Comment by natocesarrego** [comment]
Hi @NemethNorbert,

Almost all failures were handled, but there are still some to be fixed. Anyway, I think we can move on for now. Let me run CI again and let's see what we get. 🙂 

Best.

**Comment by natocesarrego** [comment]
`

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84677. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/75cf3e47b872~1...75cf3e47b872) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
