### PR TITLE
LPS-113852 SF

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: [LPS-113852](https://issues.liferay.com/browse/LPS-113852).

This solution was implemented based on this [PR](https://github.com/brianchandotcom/liferay-portal/pull/86132) related to [LPS-109990](https://issues.liferay.com/browse/LPS-109990).

### CODE REVIEW

**Comment by carolmariaabb** [comment]
> /cc @carolmariaabb

Thank you @marcosapmf  🎉 😄

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
ci:forward

**Pull request closed without merging**
