### PR TITLE
LPS-110945 Delete the structure created when executing the test

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Good job, @carolmariaabb. 😄

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
