### PR TITLE
LPS-110839 setting empty value when field gets hidden

### PR DESCRIPTION
**Pull request by linolaoj**
Hi @natocesarrego ,
with this approach, the value is set to empty after the rule evaluation has changed the "visible" property. This way the form context will be also updated and the field value will be reset.
Thanks!

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Amazing job, @linolaoj! 👏 Your fix looks great, however apparently CI reported a related failure, can you please check it and re-send?

Please send the new pull on top of the pull I'll send to you in a few moments.

Thanks.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/linolaoj/liferay-portal/pull/217. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/1360d717a152~1...1360d717a152) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
