### PR TITLE
LPS-71960

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi, @natocesarrego. This fix is for a customer. Tell me if you have any questions about it. Thanks!

### CODE REVIEW

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @ricardocousolr,

Your pull it's fine for me and I'll forward it to the Calendar team.

Just to let you know, you're free to send pulls straight to the Calendar team. Although, you can send it to me, if you desire to get a second opinion or need some help to build a fix. 😉 

Best.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/397. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ricardocousolr** [comment]
Thank you @natocesarrego! I'll take your suggestion and go straight to the Calendar team when the solution doesn't demand a second opinion. 

Best.

**Pull request closed without merging**
