### PR TITLE
LPS-116665 Fix form fields paths in tests

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-116665

Hi @carolmariaabb ,

Here you can see the changes to avoid orphaned form labels in Single and Multiple selection fields in forms.

We are getting a step closer to [what is required](https://www.w3.org/WAI/tutorials/forms/grouping/#radio-buttons) although it is not perfect yet and it is not as it was suggested in PTR-1845. The changes suggested in that PTR must be applied in Radio and Checkbox components in Clay which will widely modify their markup. Due to that, I think it is safer to apply this changes for now, and we might face the race of the changes in a separate issue for Clay.

Thanks.

Regards.

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@carolmariaabb, can you please re-send due to rebase conflicts?

Thanks.

**Comment by carolmariaabb** [comment]
Resent [here](https://github.com/natocesarrego/liferay-portal/pull/725).

**Pull request closed without merging**
