### PR TITLE
LPS 90833 [New Form Builder] The plus icon (repeatable) is overlapping a long label #978

### PR DESCRIPTION
**Pull request by mateusgomes01**
Related Issue: https://issues.liferay.com/browse/LPS-90833

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:reevaluate:1147401_7969

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@mateusgomes01,

1. Please run the command `yarn test -u` on the module `dynamic-data-mapping-form-field-type` to fix the failed JavaScript Unit Tests.
2. Check if the missing element markup is really missing on test **LocalFile.FormsDataProvider#ConfigureAutocompleteWithTextFieldPoshi** using its **Poshi Summary** link.

Thanks.

**Pull request closed without merging**
