### PR TITLE
LPS-131071 Update form field template for 7.4+

### PR DESCRIPTION
**Pull request by lawrence-lee**
Related Issue: https://issues.liferay.com/browse/LPS-131071

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by lawrence-lee** [comment]
Can you help me with `package.json`? I'm not sure why I'm getting errors building, but I think I have everything else added for 7.4 except the `package.json`. 


This is my error in case it helps

```> Task :modules:foobar:npmInstall
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> core-js@2.6.12 postinstall /private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/modules/foobar/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

npm WARNadded 847 packages from 403 contributors and audited 851 packages in 26.635s
 babel-loader@8.0.6 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
found 33 vulnerabilities (3 low, 1 moderate, 29 high)
npm WARN dynamic-data-foobar-form-field@1.0.0 No description
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN dynamic-data-foobar-form-field@1.0.0 No repository field.
npm WARN dynamic-data-foobar-form-field@1.0.0 No license field.


> Task :modules:foobar:expandJSCompileDependencyComliferaydynamicdatamappingformfieldtype601
> Task :modules:foobar:expandJSCompileDependencies

> Task :modules:foobar:packageRunBuild FAILED

> dynamic-data-foobar-form-field@1.0.0 build /private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/modules/foobar
> npm run build-soy && npm run build-js && liferay-npm-bundler


> dynamic-data-foobar-form-field@1.0.0 build-soy /private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/modules/foobar
> metalsoy --externalMsgFormat "Liferay.Language.get(‘\$2’)" --soyDeps "./node_modules/clay-*/src/**/*.soy" "./node_modules/com.liferay.dynamic.data.mapping.form.field.type/META-INF/resources/+(FieldBase|components)/**/*.soy"

Compiling soy
Finished compiling soy

> dynamic-data-foobar-form-field@1.0.0 build-js /private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/modules/foobar
> babel --source-maps -d build/resources/main/META-INF/resources src/main/resources/META-INF/resources

{ Error: Cannot find module 'babel-preset-es2015'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at resolve (internal/modules/cjs/helpers.js:32:19)
    at resolveStandardizedName (/private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/modules/foobar/node_modules/@babel/core/lib/config/files/plugins.js:96:7)
    at resolvePreset (/private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/modules/foobar/node_modules/@babel/core/lib/config/files/plugins.js:44:10)
    at loadPreset (/private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/modules/foobar/node_modules/@babel/core/lib/config/files/plugins.js:63:20)
    at loadPreset.next (<anonymous>)
    at createDescriptor (/private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/modules/foobar/node_modules/@babel/core/lib/config/config-descriptors.js:179:16)
    at createDescriptor.next (<anonymous>)
    at step (/private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/modules/foobar/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/modules/foobar/node_modules/gensync/index.js:291:5) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dynamic-data-foobar-form-field@1.0.0 build-js: `babel --source-maps -d build/resources/main/META-INF/resources src/main/resources/META-INF/resources`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dynamic-data-foobar-form-field@1.0.0 build-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lawrence/.npm/_logs/2021-05-06T22_26_45_924Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dynamic-data-foobar-form-field@1.0.0 build: `npm run build-soy && npm run build-js && liferay-npm-bundler`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dynamic-data-foobar-form-field@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lawrence/.npm/_logs/2021-05-06T22_26_45_955Z-debug.log

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:foobar:packageRunBuild'.
> Process 'command '/private/var/folders/dm/_mbc_04j2bb927xn9v0y6x940000gn/T/junit2645040328018855850/gradleWorkspacetest-workspace/test-workspace/build/node/bin/node'' finished with non-zero exit value 1
```

**Comment by liferay-forms** [comment]
Hey @lawrence-lee, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
