### PR TITLE
LPS-108205 Missing field validation for integer range

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @natocesarrego 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Hey @IstvanD,

Can you please check the SF issues?

Thanks.

**Comment by IstvanD** [comment]
Hi @natocesarrego 

I'll check it.

Best regards,
István

**Comment by IstvanD** [comment]
Hi @natocesarrego 

I corrected the SF errors and pushed the changes.

Best regards,
István

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hi @natocesarrego 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by natocesarrego** [comment]
Hi @IstvanD,

I'm sorry for the delay, but since I started to play the role of Technical Lead of Forms team my pull request queue began to be very crowded. I'm working hard with the team to address this high load and I'll review it soon.

Thanks for your understanding.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84737. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/86af3a8dc011~1...86af3a8dc011) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Great job, @IstvanD! 👏 👏

**Comment by IstvanD** [comment]
Thank you very much, @natocesarrego! 👍

**Pull request closed without merging**
