### PR TITLE
LPS-112573 fix bug when save rule on forms

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-112573

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:app-builder

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
@cvanut and @brunofariasdeo, could you please check if the tests related to the issue [LPS-112573](https://issues.liferay.com/browse/LPS-112573) are still failing, taking into account this PR, and if so, the cause is the same described in [LPS-112573](https://issues.liferay.com/browse/LPS-112573)?

Thanks!

**Comment by brunofariasdeo** [comment]
ci:test:forms

**Comment by brunofariasdeo** [comment]
@carolmariaabb,
I'm running our ci:test:forms, once the previous CI result does not contain any Poshi report.

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
@carolmariaabb, when the App Builder team finish its job regarding this pull, please let me know for I move on with the review of this pull.

Thanks.

**Comment by carolmariaabb** [comment]
> @carolmariaabb, when the App Builder team finish its job regarding this pull, please let me know for I move on with the review of this pull.
> 
> Thanks.

@natocesarrego The fix is already done on this PR, by Keven. I'm not aware of any other work by the App Builder team regarding this pull.

@kevenleone

**Comment by brunofariasdeo** [comment]
@carolmariaabb 
I have noticed that FormRules#ConfigureAutofillRule is the only related test to Rules Builder that is still failing, however its current failure is related to a Data Provider creation.
Hence, the bug related to creating a rule and saving a form is no longer reproducible in this PR.

**Comment by carolmariaabb** [comment]
> @carolmariaabb
> I have noticed that FormRules#ConfigureAutofillRule is the only related test to Rules Builder that is still failing, however its current failure is related to a Data Provider creation.
> Hence, the bug related to creating a rule and saving a form is no longer reproducible in this PR.

/cc @natocesarrego

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
ci:forward

**Pull request closed without merging**
