### PR TITLE
[TECHNICAL SUPPORT] LPS-98659 Adding repeatable text fields show incorrect translation on label

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-98659](https://issues.liferay.com/browse/LPS-98659)
Please review it,

Thanks!

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
Hey @natocesarrego ,

Could you give me an update on this PR? Thanks

**Comment by natocesarrego** [comment]
Hi @NemethNorbert,

I just started to review it. 🙂 I didn't review it before, because I was focusing on the other pull request sent by you.

Best.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77234. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/309eb816bc75~1...309eb816bc75) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
