### PR TITLE
LPS-124493

### PR DESCRIPTION
**Pull request by natocesarrego**
Related Issue: https://issues.liferay.com/browse/LPS-124493

This pull removes the following modules:
- **headless-form-client:** automatically generated to consume the tests generated on module **headless-form-test**.
- **headless-form-test:** holds tests automatically generated.

The tests under **headless-form-test** were all ignored for months, from what I could see, it was done due to the addition of new unimplemented methods which were throwing exceptions, as you can see [here](https://github.com/liferay/liferay-portal/blob/eb9498666af6f54db6cdfecd96c3933151df098c/modules/apps/headless/headless-form/headless-form-test/src/testIntegration/java/com/liferay/headless/form/resource/v1_0/test/BaseFormStructureResourceTestCase.java#L209-L214), for example. Once the Forms Headless API was created by Headless Team and Brazilian Mobile Team (which doesn't exist anymore) and who demanded this API was only the mentioned Mobile Team, then doesn't make sense Forms Team put energy on this API. After all, it was deprecated since [LPS-125528](https://issues.liferay.com/browse/LPS-125528) and the ignored tests are just polluting the Deactivated Tests Report.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
