### PR TITLE
LPS-67607 DDL spreadsheet displays null instead of blank when value is null text

### PR DESCRIPTION
**Pull request by marcellustavares**
@natocesarrego, can you please evaluate @peterborkuti fix?

he left a comment at https://github.com/marcellustavares/liferay-portal/pull/1557

Thanks

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @marcellustavares,

Sure. I'll take a look on it today.

Thanks.

**Comment by natocesarrego** [comment]
@marcellustavares, unfortunately this fix will introduce another issue if it's merged to **ee-6.2.x** and a possible issue if it's merged to **master**. 😢 

Below I'll paste the code which the fix changes in order to explain better what I mean. Please see:
```
for (Field field : fields) {
	String fieldName = field.getName();
	String fieldType = field.getType();
	Object fieldValue = field.getValue(locale);

	if (fieldValue instanceof Date) {
		jsonObject.put(fieldName, ((Date)fieldValue).getTime());
	}
	else if (fieldType.equals(DDMFormFieldType.DOCUMENT_LIBRARY) &&
			 Validator.isNotNull(fieldValue)) {

		JSONObject fieldValueJSONObject =
			JSONFactoryUtil.createJSONObject(
				String.valueOf(fieldValue));

		String uuid = fieldValueJSONObject.getString("uuid");
		long groupId = fieldValueJSONObject.getLong("groupId");

		fieldValueJSONObject.put(
			"title", getFileEntryTitle(uuid, groupId));

		jsonObject.put(fieldName, fieldValueJSONObject.toString());
	}
	else if (fieldType.equals(DDMFormFieldType.LINK_TO_PAGE) &&
			 Validator.isNotNull(fieldValue)) {

		JSONObject fieldValueJSONObject =
			JSONFactoryUtil.createJSONObject(
				String.valueOf(fieldValue));

		long groupId = fieldValueJSONObject.getLong("groupId");
		boolean privateLayout = fieldValueJSONObject.getBoolean(
			"privateLayout");
		long layoutId = fieldValueJSONObject.getLong("layoutId");

		String layoutName = getLayoutName(
			groupId, privateLayout, layoutId,
			LanguageUtil.getLanguageId(locale));

		fieldValueJSONObject.put("name", layoutName);

		jsonObject.put(fieldName, fieldValueJSONObject.toString());
	}
	else if ((fieldType.equals(DDMFormFieldType.RADIO) ||
			  fieldType.equals(DDMFormFieldType.SELECT)) &&
			 Validator.isNotNull(fieldValue)) {

		fieldValue = JSONFactoryUtil.createJSONArray(
			String.valueOf(fieldValue));

		jsonObject.put(fieldName, (JSONArray)fieldValue);
	}
	else if (Validator.isNotNull(fieldValue)) {
		jsonObject.put(fieldName, String.valueOf(fieldValue));
	}
}
```
If the fix suggested is merged, then all fields which have a null value will be missing in the JSON Object that represents the DDLRecord. So, the JSON Object won't reflect the real DDLRecord. For instance, if there is a radio field (DDMFormFieldType.RADIO) and its value is null, then the _**else if**_ which treats this field type and the last _**else if**_ will be ignored. Therefore, my suggestion is keep the current code (without the fix) and just add an _**if**_ like this:
```
else {
	if (Validator.isNull(fieldValue)) {
		fieldValue = StringPool.BLANK;
	}

	jsonObject.put(fieldName, String.valueOf(fieldValue));
}
```
In this way, we'll guarantee that every field is added to the JSON Object and will treat the case of fields with null values.

**Comment by marcellustavares** [comment]
@natocesarrego, can you make sure we have a better fix?

**Comment by natocesarrego** [comment]
Sure, @marcellustavares. I've already tested the code I've suggested and it works. This suggested code is based on what is described by Pete on [LPS-67607](https://issues.liferay.com/browse/LPS-67607) as the real solver. 😉

**Comment by marcellustavares** [comment]
Thanks @natocesarrego, could you please also add a test case for this? :)

Regards,

**Comment by natocesarrego** [comment]
ci:stop

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
