### PR TITLE
Filtering roles types related to forms context, avoiding throw an exception when searching for all types of roles and there is no a correspondent resource

### PR DESCRIPTION
**Pull request by gabrielibson**

### CODE REVIEW

**Comment by gabrielibson** [comment]
ci:test:sf

**Comment by gabrielibson** [comment]
ci:test:relevant

**Comment by gabrielibson** [comment]
Related issue: https://issues.liferay.com/browse/LPS-108459

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84489. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
