### PR TITLE
LPS-133341

### PR DESCRIPTION
**Pull request by mlan0**
Related Issue: https://issues.liferay.com/browse/LPS-133341

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by mlan0** [comment]
@natocesarrego I am still going to add the unit test for LPS-134304

**Comment by natocesarrego** [comment]
@mlan0, can you please rebase your code against to the latest branch master to solve the reported conflicts?

Thanks.

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
