### PR TITLE
LPS-113445 removing form creator name from gretting

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/515. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/d73e9a3ef37f~1...d73e9a3ef37f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
