### PR TITLE
LPS-119818 Fix poshi test to find the delete button from the opened modal

### PR DESCRIPTION
**Pull request by alinedoleron**
https://issues.liferay.com/browse/LPS-119818

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:app-builder

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:app-builder

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
@alinedoleron, I understand that there is some work to be done on your side, therefore I'm closing this pull. Please run the CI commands on your repo and when everything becomes good then send me a new pull.

Thanks.

**Pull request closed without merging**
