### PR TITLE
LPS-115507 also hiding success message when redirecting to another page

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
@linolaoj, some reported failures are related to your fix, can you please fix them or ask @cvanut for help?

Thanks.

**Comment by linolaoj** [comment]
Hi @natocesarrego , @cvanut,
the success message alert should appear when the form has a success page configured? I'm asking to know if I should update the fix or the test :sweat_smile: 
Thanks!

**Comment by natocesarrego** [comment]
@linolaoj, your fix looks good to me, please remove the success alert when we've a success page configured because keep both success messages is redundant. 😉 

Thanks.

**Pull request closed without merging**
