### PR TITLE
LPS-108225 Changing mock type

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @rijema

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
@natocesarrego sent to https://github.com/brianchandotcom/liferay-portal/pull/84804

**Pull request closed without merging**
