### PR TITLE
LPS-69157 SF - Use new recurrence test util.

### PR DESCRIPTION
**Pull request by brandizzi**
Hey Renato!

I have done some changes in the PR @mbowerman sent us. I guess you may like to take a look. Could you then forward it to Brian Chan?

Thanks!

### CODE REVIEW

**Comment by natocesarrego** [comment]
Thanks for that, @brandizzi! I'll check this ASAP and forward it to Brian, although I'm not sure if he'll accept it from me, but I'll try. 😉 

Regards.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
@natocesarrego I'm back, if you need any help here, let me know!

**Comment by natocesarrego** [comment]
Hi @brandizzi,

Nice to know! I'm having a high load here in Support and this has caused a delay to review this pull, plus the fact of the big number of commits. But, don't worry, I'll finish it this week and, as soon as it's ready, I tell you. 😄 

Thanks.

**Comment by brandizzi** [comment]
Sure

If an event starts and ends in different days, using the end date will result in the event be split in the end date. For example, suppose a recurri event that starts at 11 PM and ends at 1 AM the following day. Suppose also one of its instances was edited, and only one. Now, we edit this instance title, click in save and choose "Following events." This single instance will be updated, but the next one will not, and yet a other instances after the unaltered one will be changed.

I guess a GIF can be more understandable :)

two-day-events-recurring-after-single-instance

Note that [`CalendarBookingLocalServiceTest.testUpdateAllFollowingFromSingleInstancePreservesDayTimeAcrossDays()`](https://github.com/natocesarrego/liferay-portal/pull/61/commits/05c5c2fb8aa1d6104cc08009857bfb3a1104c7e5#diff-1bc9897a249fe92c803c5adb3ecb613bR1071) ensures this issue will not happen.

**Comment by natocesarrego** [comment]
Forwarded to Brian Chan in https://github.com/brianchandotcom/liferay-portal/pull/46844.

**Pull request closed without merging**
