### PR TITLE
LPS-115095 Fix Options broken tests.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:app-builder

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
Hi @natocesarrego. It looks good to me. Something I realized is that, when I deployed the code, the Field IDs and Field Ids from options are editable. Is that correct or something has change the behavior it was previously implemented?

**Comment by natocesarrego** [comment]
The behavior didn't change, so it's a bug. I'll rebase the code, compile and see what I get.

Thank you very much for your review, @alinedoleron. 🙂

**Comment by alinedoleron** [comment]
@natocesarrego, now I think it was a cache. Because before doing the ant all to test it, I remembered now I had set that property of readOnly to false to test something.

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
