### PR TITLE
LPS-114020 setting index type for raw metadata structure

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:upgrade

**Comment by natocesarrego** [comment]
Hi @linolaoj,

I'll forwarded your pull to @leoadb, once he's helping me with the DDM and DDL pulls and, in a near future, he'll be the official reviewer of those components.

Thanks.

**Comment by natocesarrego** [comment]
Pull request forwarded to https://github.com/leoadb/liferay-portal/pull/872. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
