### PR TITLE
LPS-131757

### PR DESCRIPTION
**Pull request by DiegoDOC**
Related Issue: https://issues.liferay.com/browse/LPS-131757

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@DiegoDOC, resent [here](https://github.com/natocesarrego/liferay-portal/pull/1056), please see this [commit](https://github.com/natocesarrego/liferay-portal/pull/1056/commits/b4ecace533880a61d3672bcad61130c451d11e73).

Thanks!

By the way, good job on this pull. :wink:

**Pull request closed without merging**
