### PR TITLE
LPS-108752 buildLang

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85624. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
@carolmariaabb, Buí said to me that pull requests like this one, which changes only language keys, can be sent straightforward to Brian. Therefore, from now on, you can proceed like Buí said.

Thanks.

**Comment by carolmariaabb** [comment]
> @carolmariaabb, Buí said to me that pull requests like this one, which changes only language keys, can be sent straightforward to Brian. Therefore, from now on, you can proceed like Buí said.
> 
> Thanks.

Okay, @natocesarrego. Thanks!

**Pull request closed without merging**
