### PR TITLE
LPS-107707 Back-end test creation for the LocalizableText forms element

### PR DESCRIPTION
**Pull request by gabrielibson**

### CODE REVIEW

**Comment by gabrielibson** [comment]
Related Ticket: https://issues.liferay.com/browse/LPS-107707

**Comment by gabrielibson** [comment]
ci:test:sf

**Comment by gabrielibson** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @gabrielibson,

Can you please check the source format issues reported by CI?

Thanks.

**Comment by gabrielibson** [comment]
ci:test:sf

**Comment by gabrielibson** [comment]
ci:test:sf

**Comment by gabrielibson** [comment]
ci:test:sf

**Comment by gabrielibson** [comment]
@natocesarrego just fixed

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/701

**Comment by leoadb** [comment]
ci:close

**Pull request closed without merging**
