### PR TITLE
LPS-83443

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
The following tests didn't fail when I executed the `ci:test:forms` [here](https://github.com/carolmariaabb/liferay-portal/pull/36):
 
1. LocalFile.Forms#ChangeFieldType 
2. LocalFile.Forms#ViewRepeatableTextFieldLabel 
3. LocalFile.FormRules#ConfigureAutofillRule 

The other two also failed in this other [PR](https://github.com/natocesarrego/liferay-portal/pull/434).

**Comment by natocesarrego** [comment]
Good job, @carolmariaabb! 😄

**Comment by natocesarrego** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
Hi @natocesarrego, I fixed formatting issues. Thanks.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
