### PR TITLE
Revert "LPS-107954 Only include Success page option if enabled"

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:app-builder

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/1129. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
