### PR TITLE
LPS-118531 - Fix Javascript unit tests

### PR DESCRIPTION
**Pull request by brunofariasdeo**
https://issues.liferay.com/browse/LPS-118531

### CODE REVIEW

**Comment by brunofariasdeo** [comment]
ci:test:sf

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@brunofariasdeo, the reported failures seems to be related to your changes, can you please double check? Apparently, you just need to regenerate the snapshot through `yarn test -u`. If you need some assistance, please let me know.

Thanks.

**Pull request closed without merging**
