### PR TITLE
LPS-106398 Validate form field type grid in case of empty option

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:close

**Comment by jeyvison** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/83095

**Pull request closed without merging**
