### PR TITLE
LPS-130855

### PR DESCRIPTION
**Pull request by carolmariaabb**
Hi,
Brian asked me [here](https://github.com/brianchandotcom/liferay-portal/pull/101106#issuecomment-827052792) to move this code to a private method or class because it is getting too nested. 

However, I'm not sure if what I did is the best solution. What do you think?

Thanks!
 
Related Issue: https://issues.liferay.com/browse/LPS-130855

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
