### PR TITLE
LPS-193136

### PR DESCRIPTION
**Pull request by TamyrisTorres**
Ticket: https://liferay.atlassian.net/browse/LPS-193136

### CODE REVIEW

**Comment by natocesarrego** [comment]
Pull requested approved! :smile:

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:relevant

**Comment by TamyrisTorres** [comment]
ci:forward

**Comment by nicolas-sss** [comment]
ci:forward

**Comment by nicolas-sss** [comment]
ci:forward:force

**Comment by nicolas-sss** [comment]
ci:forward:force

**Pull request closed without merging**
