### PR TITLE
LPS-70434

### PR DESCRIPTION
**Pull request by jcampoy**
rebased to current master - urgent

### CODE REVIEW

**Comment by jcampoy** [comment]
@natocesarrego , here are the manual tests:
lps-70434-tests

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jcampoy** [comment]
Hey @natocesarrego 
any update? we are thinking in deliver this as a SDH fix, but we want to know if this will be the right behavior. 
thx!

**Comment by natocesarrego** [comment]
Hi @jcampoy,

Your fix is fine for me and also for one of the Calendar's developers. I think there is no problem to deliver a SDH. 😉 By the way, I've just sent an email for you regarding this review, can please take a look? My go is speed up the process from now on.

Thanks.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/387. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
