### PR TITLE
LPS-118120

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/752. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/760. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/47d02da875fa~2...47d02da875fa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/762. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/31451034b0e2~2...31451034b0e2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
