### PR TITLE
LPS-108830 language key

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @linolaoj,

Your pull looks good to me. I realized there is a missing `buildLang` commit, but I can add it later. 😉 I'll just wait CI outcomes again, because the last execution reported a lot of issues, although I believe they're not related.

Best.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85609. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/91438e38b61b~2...91438e38b61b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
