### PR TITLE
LPS-97212 Fix get default locale requested when an form builder is opened

### PR DESCRIPTION
**Pull request by mclomello**
@natocesarrego could u review this pr please?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
@natocesarrego the error that were found refer to search

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Good job, @mclomello! 👏 😄 

I'll forward your fix to BChan right now. Keep your hard work. 😉

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78839. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
