### PR TITLE
LPS-134038 Add missed and remove extra values correctly

### PR DESCRIPTION
**Pull request by mateussgn**
Related Issue: https://issues.liferay.com/browse/LPS-134038

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Comment by mateussgn** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
@mateussgn, after we forward this pull to Brian, I'll report all the delay we've faced to make it happen. Honestly, we're trying to move on with it many days with no success. :disappointed: 

Thanks for your hard work on it. :wink:

**Comment by mateussgn** [comment]
Unfortunately, it hadn't passed yet, which makes me disappointed. But anyway, I had talked with QAs, and those failures are not related to my modifications, in fact, the tests had passed before on https://github.com/natocesarrego/liferay-portal/pull/1135 @natocesarrego.

**Comment by natocesarrego** [comment]
@mateussgn, I've just forwarded this pull manually to Brian, please see https://github.com/brianchandotcom/liferay-portal/pull/105669.

**Pull request closed without merging**
