### PR TITLE
LPS-119402  Create hovered property

### PR DESCRIPTION
**Pull request by alinedoleron**
https://issues.liferay.com/browse/LPS-119402

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@alinedoleron, please run `ci:forward` if the relevant suite succeed. 😉

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
