### PR TITLE
[TECHNICAL SUPPORT] LPS-105813 Update clay v2 packages to 2.20.1

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relavant ticket:
https://issues.liferay.com/browse/LPS-105813

/cc @matuzalemteles

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
These failures don't seem related to the changes.

**Comment by natocesarrego** [comment]
Hey @rodrigopaulino,

I'll re-run the tests just to make sure we're good to go. Honestly, I'm little worried because the commit of this pull is changing several modules and not only the DDM modules. Let's wait the new CI results before move on.

Best.

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @natocesarrego. I believe it's standard procedure to update the dependency of all Liferay modules when there's a bug fixed in a javascript library.

@matuzalemsteles, is my assumption correct?

**Comment by matuzalemsteles** [comment]
hey @rodrigopaulino yes correct, we need to ensure that everyone is on the same version. Just one issue recently we made a new release of Clay v2 that fixed some other bugs, I sent this to Chema last week and it was merged this week on the `v2.20.2` version, so I would say that we no longer need to send this version.

**Comment by natocesarrego** [comment]
Thanks for your clarification, @matuzalemsteles. 😉 

In light of this, I'll close this pull and resolve the [LPS-105813](https://issues.liferay.com/browse/LPS-105813) as fixed by the new release of Clay mentioned by Matu ([LPS-107740](https://issues.liferay.com/browse/LPS-107740)).

**Pull request closed without merging**
