### PR TITLE
[TECHNICAL SUPPORT] LPS-100132 Use DDMForm's default locale instead of themeDisplay's since all the field values are being persisted with form's default locale

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant links:
https://issues.liferay.com/browse/LPS-100132
https://issues.liferay.com/browse/LPS-100132?focusedCommentId=1971075&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1971075

I'm not sure if Leonardo already returned from his vacations, that's why I'm sending you this pull.
Let me know if you need anything regarding this, @natocesarrego.

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @rodrigopaulino,

Leonardo only will return from his vacation next week, therefore you did correct to send the pull for me. 😉 As soon as possible, I'll review it.

Thanks.

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @natocesarrego.

Any updates on this review?

Thanks.

**Comment by natocesarrego** [comment]
Hi @rodrigopaulino,

I'm very sorry for the delay, but the days here in Recife were very busy with a lot of meetings and I couldn't review it yet. I'll do my best to review it soon.

Thanks for your understanding. 🙂

**Comment by rodrigopaulino** [comment]
Hey, @natocesarrego.

Would it be helpful if I send this to Leonardo since he's back from his vacations?

Thanks.

**Comment by natocesarrego** [comment]
Hi @rodrigopaulino,

Last week I was sick and I didn't come to the office from Wednesday to Friday, besides I got a pull request from Lino that consumed a lot my review bandwidth, therefore these are the reasons for the big delay of this pull request. Once I was out of office a few days, I'll talk to the team to reassign part of my tasks. Today, I'll provide you an update. 😉 

Thanks for your understanding.

**Comment by natocesarrego** [comment]
Hi @rodrigopaulino,

Today, I asked the Forms team to help me process all my tasks (pull requests and PTRs), therefore, with its help, I'll be able to review your pull request tomorrow.

Thanks.

**Comment by cleydyr** [comment]
Hi, @natocesarrego . Paulino is currently on vacations. I'll watch this PR in case anything is needed.

Thank you

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @cleydyr,

I discussed with Leonardo about Paulino's proposed solution and we agreed that it'll need to be changed a little. In addition, I'll create a test to cover the issue's use case to make sure it won't be reproducible again in the future. Once I get news, I let you know.

Thanks.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79958. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/93819b9b28a3~2...93819b9b28a3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80165. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/1d7ac0452498~2...1d7ac0452498) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
