### PR TITLE
LPS-125359

### PR DESCRIPTION
**Pull request by DiegoDOC**
Related Issue: https://issues.liferay.com/browse/LPS-125359

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @DiegoDOC, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@DiegoDOC, after our daily meeting today, please talk to me for we discuss about this pull, ok?

Thanks.

**Pull request closed without merging**
