### PR TITLE
LPS-97802 Unnecessary code.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:forward

**Comment by jpince** [comment]
@leoadb UpgradeDynamicDataMappingTest failing here as well, in addition to Jeyvison's PR

@alexcandidos @cvanut tagging both Test Leads since I'm not sure who this belongs to...

**Comment by leoadb** [comment]
@jpince I already sent the fix here https://github.com/leoadb/liferay-portal/pull/755

**Comment by leoadb** [comment]
@jpince an unrelated SF error is breaking the tests.

**Comment by jpince** [comment]
@leoadb yes, fix for SF is here https://github.com/brianchandotcom/liferay-portal/pull/86836

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/405. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/706779bc5604~1...706779bc5604) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
