### PR TITLE
LPS-99386 disable Senna for this form, whose response may redirect to an external domain

### PR DESCRIPTION
**Pull request by cleydyr**
https://issues.liferay.com/browse/LPS-99386

### CODE REVIEW

**Comment by cleydyr** [comment]
ci:test

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @cleydyr,

At a first moment, your solution looks good to me, but can you please provide more context about why you decided to turn off Senna to address the issue?

By the way, have you checked if there is any other place in Forms that requires this same change?

Thanks in advance for your answers.

**Comment by cleydyr** [comment]
Sure thing, @natocesarrego. 

The issue is happening because in general forms that may redirect to external domains have Senna disabled. Like happened in LPS-71981 (see https://github.com/brianchandotcom/liferay-portal/commit/509183eba2122a3ac1d4be6d29c671d0320ba9f8. That commit has been reverted.) Some pages in Commerce use that resource as well. But in Forms component, specifically, there's no use of such attribute. I'm not sure if this is the only way to circumvent that limitation, though.

Thank you

**Comment by natocesarrego** [comment]
Hi @cleydyr,

Thanks a lot for your information! Now, I feel comfortable to forward your fix. 🙂 In addition, I'll try to discuss about your fix with Bruno Basto today to check if he agrees with this fix too.

Thanks.

**Comment by natocesarrego** [comment]
Hey @cleydyr,

I discussed with Bruno Basto about this fix and he said to me that the issue reported on LPS-99386 is, probably, an issue on Senna's side. Therefore, an investigation on Senna's side would be important to help the identification of issue's root cause. In addition, I couldn't reproduce this issue on 7.1.x (471e57c152cbbd1afbf9960a46e636c1290376cb), which makes me believe that indeed this issue can be related to other part of portal, like Senna.

Lastly, I can say that your solution addresses the issue on Form's side, however is important you look for the issue's root cause before we consider your fix as the final solution.

Can you please look for the issue's root cause?

Bruno Basto said that you can reach Diego or Matuzálem to ask for help. :)

I'll close this PR for now and assign the LPS ticket back to you, once you have any update, we can discuss on the LPS.

Thanks.

**Pull request closed without merging**
