### PR TITLE
LPS-97234 Fix status validation when DDMStructure is updating

### PR DESCRIPTION
**Pull request by mclomello**
@natocesarrego could u review this pr please?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @mclomello,

Once your solution modifies the method which updates the `DDMStructures` and considering it's used in several places along the portal, I'll run all tests instead of the relevant tests only to check if no regression will be introduced.

Best.

**Comment by natocesarrego** [comment]
ci:test

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77092. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
