### PR TITLE
LPS 90833 [New Form Builder] The plus icon (repeatable) is overlapping a long label

### PR DESCRIPTION
**Pull request by mateusgomes01**
Solves [LPS-90833 ](https://issues.liferay.com/browse/LPS-90833)plus some additional refactoring.

Also applies Code Review requests by @natocesarrego & gradle formatting

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:reevaluate:1147401_7944

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@mateusgomes01, can you please rebase this branch using the latest master and resend?

Honestly, I don't think your changes are causing all these test failures.

Thanks.

**Pull request closed without merging**
