### PR TITLE
[TECHNICAL SUPPORT] LPS-111448 Only create field in JSON if it is present in origin XML

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-111448

/cc @achaparro: I sent this pull request directly to Renato because I figured it wasn't necessary to add a new upgrade process before the `UpgradeDynamicDataMapping`. I could just make the adjustments on that and prevent it from creating invalid fields. With that, we not only avoid bringing down the upgrade's performance by adding new queries but we also improve the `UpgradeDynamicDataMapping`'s performance by not having to serialize the fields that are not good.

Please let me know in case both of you have any questions related to this.

PS.: @natocesarrego, for better understanding of the approach taken in this PR, please check the **PTR** in the related LPP.

Best.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:forms

**Comment by rodrigopaulino** [comment]
ci:test:app-builder

**Comment by rodrigopaulino** [comment]
It looks like those failed tests are related to this. I'll fix them and force push everything when I'm done. Sorry for missing that!

**Comment by natocesarrego** [comment]
Hi @rodrigopaulino,

Once you said in your previous comment that this pull has related failures, I'm closing this pull. When you get ready please forward this pull to @leoadb.

Thanks.

**Pull request closed without merging**
