### PR TITLE
LPS-107976 Improved autocomplete of the text field so that a user can type naturally

### PR DESCRIPTION
**Pull request by gabrielibson**

### CODE REVIEW

**Comment by gabrielibson** [comment]
Related issue: https://issues.liferay.com/browse/LPS-107976

**Comment by gabrielibson** [comment]
ci:test:sf

**Comment by gabrielibson** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @gabrielibson,

This fix seems to be introducing regressions, therefore I'll re-run CI. Please check its results when CI finish the new run.

Thanks.

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by gabrielibson** [comment]
Hi @natocesarrego 
I checked the failed tests. They are not related to this pull request.

Thanks.

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/84805

**Comment by leoadb** [comment]
ci:close

**Pull request closed without merging**
