### PR TITLE
LPS-71029

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @dacousalr,

There is any specific reason for you create a dateFormat just for English?

After analyze the issue, I've understood that the problem is because the current code is trying to create a Javascript Date object using a date format unsupported by it. So, what do you think to remove the date format from the creation of this Javascript object and instead use only the year, month and day of the date to create it? Please take a look on the code below:

`untilDate = new Date(<%= untilJCalendar.get(java.util.Calendar.YEAR) %>, <%= untilJCalendar.get(java.util.Calendar.MONTH) %>, <%= untilJCalendar.get(java.util.Calendar.DATE) %>);`

This way you will avoid create another variable just to store the English date format to solve this issue. 😉 

I'll wait your considerations about my comment.

Regards.

**Comment by dacousalr** [comment]
Hi @natocesarrego,

Firstly, thank you for your review and yes, the root cause of this bug is the one you have mentioned.

I had considered both solutions (your proposed solution and the solution of this PR) but I decided to send this one because I think this solution is more "timezone-safe".

What do you think?

Regards

**Comment by natocesarrego** [comment]
I'm glad you've considered the timezone during your implementation, @dacousalr , it's very important. 😉

Although, the solution I've mentioned on my last comment also attends to it too. The variable **untilDate** is used to create the object **recurrence**, which is used as argument of the method **Liferay.RecurrenceUtil.getSummary(recurrence)**, please take a look on this code [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/calendar/calendar-web/src/main/resources/META-INF/resources/view_calendar_booking.jsp#L224-L234), and this **RecurrenceUtil** has support for the timezone, please see this [code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/calendar/calendar-web/src/main/resources/META-INF/resources/view_calendar_booking.jsp#L175) and then see this other [code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/calendar/calendar-web/src/main/resources/META-INF/resources/calendar_booking_recurrence_language_keys.jspf).

Considering this solution also supports timezone, I believe it's the best option only because it avoids the creation of a new variable to store the English date format.

What do you think? Does it make sense for you?

Best regards.

**Comment by dacousalr** [comment]
Thank you so much for your clarifications @natocesarrego,

I have reviewed **RecurrenceUtil** and I agree that your solution is much better and cleaner.

Can I send you a new PR with this solution or can you replace my solution with yours and forward it to Brian?

Best regards

**Comment by natocesarrego** [comment]
I'd be glad if you could send me a new PR. 😄 

Thanks for the technical discussion.

Regards.

**Comment by dacousalr** [comment]
Thanks to you!

I have already sent the new PR. This one can be closed.

Regards

**Pull request closed without merging**
