### PR TITLE
LPS-125359

### PR DESCRIPTION
**Pull request by natocesarrego**
Related Issue: https://issues.liferay.com/browse/LPS-125359

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @liferay-data-engine, can you please take a look on this pull request too?

The proposed fix needed to change the Data Engine code.

Thanks in advance.

**Comment by rodrigopaulino** [comment]
Hey, @natocesarrego. The PR looks good to me, so I tried to check if it fixes the reported behavior, but I wasn't able to reproduce the initial problem in the first place. I tested the steps in the ticket using Google Chrome and Mozilla Firefox, but I don't get the sidebar moving to the middle of the page as reported. Instead, I get this weird behavior while using the drag and drop functionality. Although this shouldn't be related because it happens both with or without this PR.

https://user-images.githubusercontent.com/11450348/119671173-f2123b00-be0f-11eb-9557-6acffdbc38e9.mov

Were you able to reproduce the initial problem? If so, from what git hash was your bundle built?

Thanks for reaching out.

**Comment by natocesarrego** [comment]
ci:test:forms-functional

**Comment by natocesarrego** [comment]
Please ignore my previous comment, it's just an internal test. :slightly_smiling_face:

**Comment by natocesarrego** [comment]
Thank you very much, @rodrigopaulino!

@DiegoDOC, can you please answer the questions asked by Rodrigo?

Thanks.

**Comment by liferay-forms** [comment]
Hey @natocesarrego, can you please check if these failures are related to your changes? Thanks

**Comment by DiegoDOC** [comment]
Hey, @rodrigopaulino. The error was successfully reproduced back when we first tried to fix it. Today I tested in both Google Chrome and Mozilla Firefox(everything up-to-date), and I am still able to reproduce the bug, the sidebar moves to the middle of the screen, yet I was unaware of the issue present with the drag and drop functionality.

**Comment by rodrigopaulino** [comment]
Thanks for answering, @DiegoDOC. When you say "everything up-to-date", do you mean your local liferay-portal repo? Could you please share in what git hash was your repo when you reproduced the behavior? Also, by watching the video I've attached before, do you see any difference from what you're currently doing to reproduce the bug?

Best.

**Comment by DiegoDOC** [comment]
Thanks for the reply @rodrigopaulino. By "everything up-do-date" I do mean my local liferay-portal repo. The git hash for when I first reproduced the behavior is  "e074ff0945d0d686a05cecf31d8f4d07b42984d8". In regards to the attached video, I am unable to see any difference from what I am currently doing. Could you maybe attach a video of you opening and closing the sidebar? I tested multiple times and the problem persists.

Best of luck.

**Comment by rodrigopaulino** [comment]
I'll try that, @DiegoDOC. I'll let you know afterwards. In the meantime, I asked Emanuel, our QA Engineer, to test this behavior too.

Thanks.

**Comment by rodrigopaulino** [comment]
Hey, @DiegoDOC. I was able to reproduce the behavior (the sidebar moving to the middle of the page) with your suggestion, which is closing the sidebar. Only this way it was possible, not by dragging and dropping the fields as reported.
What I suspect has happened is that this ticket was created before Forms stopped using their sidebar completely and moved to use Data Engine's, thus causing this slight change of behavior. Therefore, could you please update the reproduction steps in the ticket so QA Engineers can properly reproduce the issue and confirm the completion of the fix once it gets merged?
That said, I tested your proposed changes and the functionality seems to work now. This is good to go.

Good job and thanks for contributing.

**Comment by DiegoDOC** [comment]
Hey, @rodrigopaulino thanks for the reply. I'll gladly update the ticket.

Keep up the good work!

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
