### PR TITLE
LPS-103224 Improve DDM indexation to address issues associated to nested fields indexation and also to save Elasticsearch resources.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:search

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:search

**Comment by yichenroy** [comment]
Your pull request test has been aborted. We are sorry of the inconvenience but QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Comment by jorgediaz-lr** [comment]
'Just

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Search test suite reported possible related failures, I'll need to analyze/fix it before move on with the pull.

**Comment by jorgediaz-lr** [comment]
Hi @natocesarrego 

I have send you this pr https://github.com/natocesarrego/liferay-portal/pull/408 with some additional commits that fixes some of the failing ci tests.

I hope it helps

**Comment by natocesarrego** [comment]
Thanks a lot, @jorgediaz-lr. 😄 I'll check your pull soon.

**Comment by jorgediaz-lr** [comment]
No problem!! however it only fixes some of the errors, so additional work will be necessary

**Comment by natocesarrego** [comment]
Yeah, I know, @jorgediaz-lr. I just read your Jira's comment. 🙂

**Comment by natocesarrego** [comment]
Closing this pull to keep the work on https://github.com/natocesarrego/liferay-portal/pull/408.

**Pull request closed without merging**
