### PR TITLE
LPS-90515

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-90515

Hi Renato,

I applied the changes you recommended in PTR-635 and found everything to work as intended.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Good job, @ChrisKian! 😉  I'll forward your pull request to Forms team.

Thanks.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/247. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
