### PR TITLE
LPS-112951 Organizing heading levels on the forms

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
ci:test:app-builder

**Comment by natocesarrego** [comment]
Hey @linolaoj,

Forms test suite reported a related failure, please check it below:

- https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/318202/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_ViewSuccessPage_/

Can you please fix it? I think it's a very simple one. If you need some assistance or don't have enough bandwidth to do it, please talk to @brunofariasdeo or @cvanut. 😉 

Thanks.

**Comment by linolaoj** [comment]
new pull request https://github.com/natocesarrego/liferay-portal/pull/544

**Pull request closed without merging**
