### PR TITLE
LPS-102643 getting serializable number by type

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
@linolaoj sent to https://github.com/leoadb/liferay-portal/pull/663. Please close. Thanks!

**Comment by leoadb** [comment]
ci:close

**Pull request closed without merging**
