### PR TITLE
LPS-109389 Set undefined locales to empty string

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @natocesarrego 
Could you please review this pull request?
I closed the previous pull because I tough it was bad after the CSE reported me that it didn't work for him, but I figured out, I just forgot to add another LPS to his SDH.
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hey @MarcellGyopos,

Your commit message has the Jira ticket number two times, can you please fix it?

Thanks.

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@leoadb, this is a DDM pull, can you please review?

Thanks.

**Comment by MarcellGyopos** [comment]
Hi @natocesarrego ,
I did it.
Thank you,
Marci

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/86488

**Comment by leoadb** [comment]
ci:close

**Pull request closed without merging**
