### PR TITLE
LPS-121765 Add unit test to check the options quantity before and after removing an option.

### PR DESCRIPTION
**Pull request by natocesarrego**
Related Issue: https://issues.liferay.com/browse/LPS-121765

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hey @natocesarrego, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
