### PR TITLE
LPS-133652 Add a case if the record values are of Search Location field

### PR DESCRIPTION
**Pull request by marcelabc**
Related Issue: https://issues.liferay.com/browse/LPS-133652

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Great job, @marcelabc and @EliveltonR18! :smile:

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
