### PR TITLE
LPS-97302 When selecting an option from Single Selection or Multiple Selection with required and inline enabled will disable inline in form submitter

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-97302](https://issues.liferay.com/browse/LPS-97302),

Please review it,

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Good job, @NemethNorbert! 😄 👏

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81777. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/643413025883~1...643413025883) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
