### PR TITLE
LPS-97232 make any clicks on a disabled input fall through to the parent element

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86096. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/b6888af8e8b2~1...b6888af8e8b2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
