### PR TITLE
LPS-110052 Pass fieldName instead of indexes when duplicating or deleting fields using sidebar's kebab

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Triggering relevant suite to make sure no side effects will affect App Builder.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
@cvanut, Forms test suite reported a related failure, please check it below:

- https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/362882/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_Add30Fields_/

Can you please confirm if it's indeed related?

Thanks.

cc @carolmariaabb

**Comment by natocesarrego** [comment]
Talking to Cleyton offline, we concluded that the reported failure isn't related.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86416. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
