### PR TITLE
[TS] LPS-101544 

### PR DESCRIPTION
**Pull request by brianikim**
Hello @natocesarrego ,

Notes from @matthewchan1:

> https://issues.liferay.com/browse/LPS-101544
> 
> Issue:
> Changing a site's default locale in site configurations, then limiting available locales to just that language is defaulting to blank text for custom web content fields.
> 
> The main problem is that neither the current nor default translations are present in availableLocales. In this case, since there is just one availableLocales value, it will be more user-friendly to display the existing localization rather than empty fields.
> 
> Fix:
> Locale is passed from in a chain of function calls in DDMFormFieldFreeMarkerRenderer.java, so changing the locale in render() at the highest level will fix problems with both field options and titles appearing blank. I just fetched the locale in availableLocales and set it as the default language. The result is text reappears as per its definition in the Edit Structure page.

We are aware that Forms issue should have been directed to BR team, but the issue was not identified as a Forms issue until a bit too much work was committed. We will be more careful next time and redirect properly and sooner.

Please let us know if you have any questions about the fix. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Hi @brianikim,

Just to let you know, only the issues related to the Forms component should be assigned to BR Technical Support, issues associated to other components, like DDM, for example, that are assigned to the Forms team can be handled by the original Support office. 😉

Besides, you don't need to apologize for anything. 🙂

At last, I'll start the review of this pull soon.

Thanks.

**Comment by natocesarrego** [comment]
Hi @brianikim and @matthewchan1,

After analyze the issue and your proposed fix, honestly, I'm not sure if we're addressing the issue's root cause and I'll tell you guys why I'm having this feeling. The code responsible for set the label of a Structure field is this [one](https://github.com/liferay/liferay-portal/blob/70f2da48ea1b13794016df044dce38ecdc63ce75/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L942-L945) and if you check it, you'll see that the parameter **locale**, e.g. the locale to be displayed, is used to get the proper label. But, if there isn't any label for this display locale, then the default locale will be used, please check the [code](https://github.com/liferay/liferay-portal/blob/70f2da48ea1b13794016df044dce38ecdc63ce75/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L284-L296) which provides the default locale. By default, the default locale is the locale set on the form definition, however this [commit](https://github.com/liferay/liferay-portal/commit/ca10f4710dec9b92c538bd2025edc187e74eacdb) of [LPS-93619](https://issues.liferay.com/browse/LPS-93619) is overriding this mentioned locale, which, IMHO, doesn't make much sense.

Therefore, after all described above, I understand that the fix for the issue's root cause, at a first moment, should be handled in the front-end.

Can you please analyze the issue with the information I provided to you in mind?

Thanks.

**Comment by matthewchan1** [comment]
Hi @natocesarrego, 

Thank you for that insight. I had noticed the form's default locale was overridden by the themeDisplay locale, and had thought this might be intended due to consistency among portlets. It would make sense that the original default locale of a form could be preserved, however, and I plan to test the proposed change for LPS-93619 code whether it could also solve this issue. Will keep you updated as to the test results.

Best regards,
Matthew

**Comment by matthewchan1** [comment]
Removing the following line resolved our ticket LPS-101544:
ddmFormDefinition.defaultLanguageId = '<%= LocaleUtil.toLanguageId(defaultLocale) %>';

I ran through the reproduction steps for LPS-93619 and verified the original issue is still fixed as well. If this seems okay, I'd like to resend a PR to you with the aforementioned change.

**Comment by natocesarrego** [comment]
Hi @matthewchan1,

Before remove the line of code which overrides the default locale of a form, I understand that you should check which issue the fix for the [LPS-93619](https://issues.liferay.com/browse/LPS-93619) aimed to address. In light of this, I think you'll be able to find a solution to address both issues, the [LPS-93619](https://issues.liferay.com/browse/LPS-93619) and the [LPS-101544](https://issues.liferay.com/browse/LPS-101544).

In addition, the error message shared by you, indeed, can be an intended behavior, but a further analysis should be done to confirm it. One more thing, I understand that is possible/acceptable the Forms portlet present a behavior different from the Web Content/Structure, therefore you can relax regarding this difference. 🙂 

Please revisit your solution with this comment in mind, next we can move on with this pull request.

Thanks.

**Pull request closed without merging**
