### PR TITLE
[TECHNICAL SUPPORT]LPS-100416 Non-Repeatable text fields show incorrect translation on label at first load

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @natocesarrego,

We found a regression with [LPS-98659](https://issues.liferay.com/browse/LPS-98659), when made a hotfix. I simply forget about non-repeatable fields when the instance default locale and the structure's default locale is not the same.

I quickly made a fix for it, please review it. -> [LPS-100416](https://issues.liferay.com/browse/LPS-100416)

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @NemethNorbert,

I've just tested the issue's use case and I realized that the field label is correct, although the Translation Manager is not, please check the image below:

Translation manager out of sync

Can you please check it?

Thanks.

**Comment by NemethNorbert** [comment]
> Hi @NemethNorbert,
> 
> I've just tested the issue's use case and I realized that the field label is correct, although the Translation Manager is not, please check the image below:
> 
> Translation manager out of sync
> 
> Can you please check it?
> 
> Thanks.

Hey @natocesarrego,
I'm trying to resolve this issue, It looks like it will take a bit more time.
Thanks

**Comment by natocesarrego** [comment]
Ok, @NemethNorbert. Thanks for your update. I'll close this pull request, once you'll need to handle this other issue.

Best.

**Pull request closed without merging**
