### PR TITLE
LPS-118531 - Create scrollToCard function to avoid page URL to be changed

### PR DESCRIPTION
**Pull request by brunofariasdeo**
https://issues.liferay.com/browse/LPS-118531

### CODE REVIEW

**Comment by brunofariasdeo** [comment]
ci:test:sf

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@brunofariasdeo, the JS test failures seems to be related to your pull, can you please check them?

If you need some help, please let me know. 😉 

Thanks.

**Pull request closed without merging**
