### PR TITLE
[Master] LPS-114721 Accessibility - Required Fields

### PR DESCRIPTION
**Pull request by rijema**
Hi @natocesarrego , with your help and Carolina's, I delivered the fix for dxp-6 to the CSE. Now, I'm sending the addition to the branch master. Thank you!

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @rijema, did you mean that you delivered a hotfix to the customer and now you're sending the definitive solution to master, is this correct?

Besides, why the LPS-114721 doesn't have master as an affected version?

Thanks in advance for your clarifications.

**Comment by rijema** [comment]
That's right, @natocesarrego . I delivered a fix as a workaround to the customer and now I'm sending the definitive solution to the branch master, based on what we discussed in the PTR. I also added the master as an affected version, since I had forgotten it, even though I reproduced the same error.

**Comment by natocesarrego** [comment]
Thanks for your clarifications, @rijema. 🙂

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @rijema, the reported failures seems to be related, can you please check them?

At a first seen, some of the failures will be addressed through the regeneration of the snapshot files used by the JavaScript unit tests. You can regenerate the snapshot files running the command `yarn test -u` from the module's folder, like `dynamic-data-mapping-form-field-type`. If you need some assistance, please talk to Lino or Cleydyr, because both of them already handled this kind of regeneration problem. 😉 

Thanks.

**Comment by rijema** [comment]
Hi, @natocesarrego. Thank you so much for the explanation. I'm working on that!

**Pull request closed without merging**
