### PR TITLE
[TS] LPS-122681, LPS-122683

### PR DESCRIPTION
**Pull request by ChrisKian**
Related Issue: https://issues.liferay.com/browse/LPS-122683

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @ChrisKian, this pull is changing DDM component code instead of Forms code, therefore can you please send your pull to the team in charge of it (e.g. Data Engine)?

More details about components assignments and Brazilian teams, please see https://loop.liferay.com/home/-/loop/feed/21310113.

Thanks in advance. 🙂

**Comment by ChrisKian** [comment]
Thanks @natocesarrego, sent to https://github.com/jeyvison/liferay-portal/pull/897

**Pull request closed without merging**
