### PR TITLE
LPS-121135 Resize sidebar to fit all field Types selectors without overlapping

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issue: https://issues.liferay.com/browse/LPS-121135

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@alinedoleron, do you think we can create a test to this issue?

Thanks.

**Comment by alinedoleron** [comment]
> @alinedoleron, do you think we can create a test to this issue?
> 
> Thanks.

@natocesarrego, I could not create a test for this case. I tried a lot, but it didn't work. Also I asked for help to Matu and Diego and they said they think there's no way to get the css properties on the test, since the width is on css file and not on style attribute.

**Comment by natocesarrego** [comment]
Ok, @alinedoleron. Thanks.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
