### PR TITLE
LPS-101288 updating test

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79882. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/da328e728ecc~2...da328e728ecc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79884. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/8793b2449c39~2...8793b2449c39) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79910. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/9544ccfbc79a~2...9544ccfbc79a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
