### PR TITLE
LPS-167292

### PR DESCRIPTION
**Pull request by torresvictor100**

### CODE REVIEW

**Comment by torresvictor100** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
@torresvictor100, remember to start the commit messages with capital letter, e.g, "Create filter ..." instead of "create filter ..." :wink:

**Comment by torresvictor100** [comment]
ci:test:relevant

**Comment by torresvictor100** [comment]
ci:test:sf

**Comment by torresvictor100** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@torresvictor100, the semantic version error will probably be fixed after you update your local branch `master` and run the command `git rebase master`. In addition, please check the reported failures, because they may be related to your change.

**Pull request closed without merging**
