### PR TITLE
LPS-69123

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @natocesarrego,

I added a commit to avoid a NullPointerException in the case that we are updating "Following Events" from a Single Instance event.

The logic for updating "Following Events" from a Single Instance event is largely flawed, but it is being fixed with [LPS-69157](https://issues.liferay.com/browse/LPS-69157). However, as this is a NullPointerException caused by the logic withing the invokeTransition method that this fix updates, I thought it made more sense to add this commit as part of this LPS.

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:retest

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Nice job again, @mbowerman. By the way, do you mind to add an unit or an integration test to this PR? This will help us avoid regressions and make Calendar more stable. 😉

Thanks.

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
Hi @natocesarrego,

I've added a test to this PR.

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
Hi @natocesarrego,

I realized I forgot to put the @Override annotation on the invokeTransition method, so I rebased my fix and force-pushed it.

**Comment by mbowerman** [comment]
ci:stop

**Comment by mbowerman** [comment]
ci:retest

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/339. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/1dbfcaa~2...1dbfcaa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
