### PR TITLE
J cords lps 74454 revised 3

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-74454
https://issues.liferay.com/browse/LPP-26631

Resent with semantic version change.

I've gone ahead and created a new template to handle individual CalendarBooking instance deletion and also added IM templates (even though it's not yet used). I also found a way to return to this pattern:
-User is notified with Deleted template if 1 occurrence is deleted
-User is notified with Updated template if multiple occurrences are deleted

I added to the integration test to test these changes. The email notifications now look like this:
deletion notifications

### CODE REVIEW

**Comment by joshuacords** [comment]
Hello @natocesarrego, do you know when you'll be able to get to reviewing these changes?

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @joshuacords,

I'm finishing to review your pull, I just need to execute your integration test and see the semantic version commit. By the way, once your last commit has introduced a major version increase, this fix can't be backported to 7.0.x. I'll try to circumvent it.

Regards.

**Comment by joshuacords** [comment]
Thanks @natocesarrego, if you can figure out a way to that would be great but I just couldn't think of a better way of passing around the start time. 
Would it be acceptable to keep the older notifyCalendarBookingRecipients() and getInstance() methods and had them forward to the new method signatures passing null form the serviceContext? Wouldn't that reduce it to a minor version change?

**Comment by natocesarrego** [comment]
Hi @joshuacords,

I was planning to do exactly what you've said! 😃 I'll try to do that and I let you know the results.

Best.

**Comment by natocesarrego** [comment]
Hi @joshuacords,

I've tested the solution we've discussed in order to circumvent the major version bump and it's worked. I'll just double check if it's ok to move on with this kind of solution to avoid rework from our side in the future.

Best.

**Comment by joshuacords** [comment]
That's great @natocesarrego! Let me know how it goes.

**Comment by natocesarrego** [comment]
Hey @joshuacords,

Have you had any problem to run the integration test created by you? I'm receiving a **NullPointException** when executing the call to the method **MailServiceTestUtil.getMailMessages**. Actually, it's happening to almost all methods of the  **CalendarBookingLocalServiceTest**.

In addition, I've circumvented the major version bump and we'll be able to backport it. 🎉 😄 By the way, your fix is working nicely in my machine too, good job!

Best.

**Comment by joshuacords** [comment]
Hello @natocesarrego, the Tests were working fine before I submitted PR and in the process of creating it all the other tests were working properly. I'm not sure what the issue you're running into is - if you need me to rerun the tests let me know.

**Comment by natocesarrego** [comment]
Don't worry, @joshuacords, I'll ask for one of my coworkers to execute the tests here, because, apparently, the issue is in my machine.

Thanks.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/479. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/6557b815f3a1~5...6557b815f3a1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
