### PR TITLE
LPS-163650 Allow change property default.portlet.decorator.id through Instance Settings

### PR DESCRIPTION
**Pull request by torresvictor100**

### CODE REVIEW

**Comment by torresvictor100** [comment]
ci:test:sf

**Comment by torresvictor100** [comment]
ci:test:relevant

**Comment by torresvictor100** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Fowarded: https://github.com/liferay-usm/liferay-portal/pull/882

**Pull request closed without merging**
