### PR TITLE
LPS-121007 also copy form permissions

### PR DESCRIPTION
**Pull request by linolaoj**
Related Issue: https://issues.liferay.com/browse/LPS-121007

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @linolaoj, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @linolaoj, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@linolaoj, please fix conflicts and resend to user `liferay-forms`. More details in https://liferay.slack.com/archives/CL5QZC5TN/p1600432758000400. Besides, from now on, you don't need to trigger CI commands anymore, since yesterday we're delegating this manual work to a bot. 😉 🤖 

Thanks.

**Pull request closed without merging**
