### PR TITLE
[TECHNICAL-SUPPORT] LPS-78180 fix value if the field is not localizable

### PR DESCRIPTION
**Pull request by rolandpakai**
Please review my changes.

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @rolandpakai,

I realized you send a new pull request (https://github.com/natecavanaugh/liferay-portal/pull/4128) with these changes to be reviewed by another reviewer, thus should I review it or not?

Best.

**Comment by rolandpakai** [comment]
Yes, please review that one too :)
Sorry for the inconvenience, i messed up you names.

**Comment by natocesarrego** [comment]
No problem, @rolandpakai, and thanks for the clarification. 😃 

Best.

**Comment by natocesarrego** [comment]
ci:test

**Comment by natocesarrego** [comment]
Hi @rolandpakai,

I'm closing this pull, because I'll review the pull sent by natecavanaugh. Please check https://github.com/natocesarrego/liferay-portal/pull/111 to track the review progress.

Best.

**Pull request closed without merging**
