### PR TITLE
[TS] LPS-103913 Site Administrator is not able to add Widget Templates

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-103913](https://issues.liferay.com/browse/LPS-103913)

Hi Renato,

I hope you can review my pull request.

**Issue:** Site Administrator is unable to add Widget Templates, while in Liferay 6.2 it was possible.

**Background:** There was a [change how we check permission for ADD_PORTLET_DISPLAY_TEMPLATE action](https://github.com/rafaprax/liferay-portal/commit/1075f365620c9c8bfe185dc2754f988f3ee6fef0#diff-828e5de6ff3d44f3db56fbcb2044539c) introduced in [LPS-63392](https://issues.liferay.com/browse/LPS-103913).

From that point, we don't pass groupId parameter which eventually would be necessary for AdvancedPermissionChecker to know if the user has admin rights on the group.

Actually, the code - including the permission checking code - changed a little bit since then, but the issue is still present. When looking at the actual parameters, seemingly we pass `_ddmWebRequestHelper.getScopeGroupId()`, but debugging reveals that it is mapped to `plid` at the end. (See formal parameters in comments.)

```
PortletPermissionUtil.contains(
	_ddmWebRequestHelper.getPermissionChecker(),   // PermissionChecker permissionChecker
	_ddmWebRequestHelper.getScopeGroupId(),   // long plid
	resourceName,   // String portletId
	ActionKeys.ADD_PORTLET_DISPLAY_TEMPLATE)   // String actionId
```

Please let me know if there is anything else I could help you with.

Thank you in advance,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
@natocesarrego , once you had a chance to take a look into this change, please let me know if it is good enough to be delivered as an SDH.

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Hi @natocesarrego ,

I have rebased and restarted the tests. Please let me know if I can help you with anything else.

Thank you!

**Comment by natocesarrego** [comment]
Hi @istvansajtos,

First of all, sorry for the delay to review this pull, but I was out of office all last week and Leonardo Barros, the backup reviewer, couldn't process all pull requests in my queue, actually, he only was able to process part of it. But, don't worry, I'll start to review your pull right now and soon I'll give you a feedback regarding your fix. 🙂 

Best.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hi @istvansajtos,

Your solution makes sense to me and I don't see any impediment to deliver it as a SDH. 🙂 

Additionally, I'll just double check if the last CI report is valid or not before forward your pull.

By the way, congratulations for the great pull request! 👏 👏 You described the issue and your solution and also shared the original code which introduced the problem, good job! Keep pull requests like this one coming and will be a pleasure review them. 😄 

Thanks.

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Thanks for the update @natocesarrego ! Please feel free to contact me if there is anything I can help you with.

**Comment by natocesarrego** [comment]
Thanks for your support, @istvansajtos. 😄

Well, after analyze the last outcome from CI, I can confirm that your fix isn't introducing regressions. I'll forward it right now.

Best.

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80968. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
