### PR TITLE
LPS-109868 Separator field with nested fields has no translations

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @natocesarrego 

Could you please review this pull request?

Separator fields do not have a `dataType` field, but they are necessary for their localizations to be updated.
This does not pose a problem if they contain no data, but if they have nested fields, the new translations won't be added.

Thank you and best regards,
István

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hi @natocesarrego 

I know you have a lot to do nowadays. I was just wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @IstvanD,

I was waiting the outcomes from CI before review it, however CI execution failed. 😞 I just checked your pull and it looks great! Let's wait CI results, if it fails again, then I'll forward your pull, ok?

Thanks.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86175. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
