### PR TITLE
LPS-126479

### PR DESCRIPTION
**Pull request by mlan0**

### CODE REVIEW

**Comment by mlan0** [comment]
ci:test:sf

**Comment by mlan0** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @mlan0, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
@mlan0, please rebase and send again. Let's see if it'll solve the reported failures. They look awkward.

**Pull request closed without merging**
