### PR TITLE
LPS-121426 Update snapshots

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issue: https://issues.liferay.com/browse/LPS-121426

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hey @alinedoleron, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please fix the source formatter issues and resend? Thanks

**Comment by alinedoleron** [comment]
New pr: https://github.com/natocesarrego/liferay-portal/pull/866

**Pull request closed without merging**
