### PR TITLE
LPS-107854 DDM Form Instance does not have storage type when upgrading from 7.0

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Good to go. Waiting CI results.

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85815. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
