### PR TITLE
LPS-98228 Recreate CKEditor when drag ddm-text-html field

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @natocesarrego

Please check it and push it forward,

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
Hi @natocesarrego

could you please push this forward?

Thanks, Roland

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81199. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/6870e24e27ff~2...6870e24e27ff) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81200. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/42627af94c84~2...42627af94c84) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
