### PR TITLE
[TECHNICAL SUPPORT] LPS-131983 WCAG error for missing label association with input fields in Liferay Forms

### PR DESCRIPTION
**Pull request by NemethNorbert**
Related Issue: https://issues.liferay.com/browse/LPS-131983

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
Hey @natocesarrego,

I fixed the test in text.js and updated all the snapshots. Please review my changes

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @NemethNorbert, can you please check if these failures are related to your changes? Thanks

**Comment by NemethNorbert** [comment]
Hey @natocesarrego,

the tests are green when I run them locally, and the Jenkins console does not provide more information. Could you help me pinpoint what is the remaining problem?

Thanks,

**Comment by carolmariaabb** [comment]
Hi @NemethNorbert , 

It appears that the `DatePicker has a predefinedValue` test is using the server's time zone, which is different from yours.

```
- Snapshot  - 2
+ Received  + 2

- value="Tue Jun 02 2020 00:00:00 GMT+0200 (Central European Summer Time)"
+ value="Tue Jun 02 2020 00:00:00 GMT-0700 (Pacific Daylight Time)"
```

**Comment by NemethNorbert** [comment]
Hey @natocesarrego,

The tests are green now, can you follow up on the review please?
Thanks

**Comment by carolmariaabb** [comment]
Hi @NemethNorbert ,

Renato is sick so he is out of office until next week. From what I could see [here](https://github.com/natocesarrego/liferay-portal/pull/1025#issuecomment-839179842), he has already approved the changes. I also reviewed it and it's ok for me.  Therefore, I'll forward this pull.

Thanks!

/cc @natocesarrego

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by NemethNorbert** [comment]
Thank you @carolmariaabb for your review and pushing forward the solution

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
