### PR TITLE
LPS-103508 Add catch in case of invalid characters for field name

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82533. [See changes here.](https://github.com/natocesarrego/liferay-portal/compare/adb9ab248bd7~1...adb9ab248bd7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hey @carolmariaabb,

I added one more [commit](https://github.com/brianchandotcom/liferay-portal/pull/82533/commits/adb9ab248bd7a086ed2b3992e1ba0fef560dbc8a) to your solution due to source format requirements. I reordered the `catch` statement introduced by you to keep the alphabetic order. If you still have some doubt about this source format commit, please let me know.

Best.

**Pull request closed without merging**
