### PR TITLE
LPS-132001

### PR DESCRIPTION
**Pull request by mlan0**
Related Issue: https://issues.liferay.com/browse/LPS-132001

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Hi @mlan0,

As far as I know, the user should be able to see the Preview even if the form is not saved (this is the current behavior in versions 7.3.x, 7.2.x and 7.1.x). Have you discussed this solution with someone from the Forms team?

Feel free to talk to me so we can discuss it. Thanks 😄

**Pull request closed without merging**
