### PR TITLE
LPS-109805 Fixing visibility expression upgrade

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-109805

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:forms

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
Closing once this is still in progress.

**Pull request closed without merging**
